import re
VOCAB = r'D:\Claude cli\MyApp\yingo\src\data\vocab-sample.ts'
with open(VOCAB,'r',encoding='utf-8') as f:
    c = f.read()
c = re.sub(r'];\s*$', '', c)
ids = re.findall(r'id:\s*"w(\d+)"', c)
cid = max(int(x) for x in ids) if ids else 0
print(f'Current: w{cid}')
d = [
('aftermath','/ˈɑːftəmæθ/','n. 后果','result','Aftermath of the storm.','风暴后果�?),
('backlash','/ˈbæklæʃ/','n. 强烈反对','strong reaction','Public backlash against the policy.','公众对政策的强烈反对�?),
('breakthrough','/ˈbreɪkθruː/','n. 突破','major advance','Medical breakthrough.','医学突破�?),
('catalyst','/ˈkætəlɪst/','n. 催化�?,'trigger','Education as a catalyst.','教育作为催化剂�?),
('drawback','/ˈdrɔːbæk/','n. 缺点','disadvantage','The main drawback.','主要缺点�?),
('fallout','/ˈfɔːlaʊt/','n. 后果','consequences','Political fallout.','政治后果�?),
('groundwork','/ˈɡraʊndwɜːk/','n. 基础','preparation','Lay the groundwork.','打基础�?),
('handicap','/ˈhændikæp/','n. 障碍','disadvantage','Overcome a handicap.','克服障碍�?),
('interplay','/ˈɪntəpleɪ/','n. 相互影响','interaction','Interplay of factors.','因素间相互影响�?),
('landmark','/ˈlændmɑːk/','n. 里程�?,'significant event','A landmark ruling.','里程碑式裁决�?),
('layout','/ˈleɪaʊt/','n. 布局','arrangement','The layout of the building.','建筑布局�?),
('lifespan','/ˈlaɪfspæn/','n. 使用寿命','duration','Product lifespan.','产品使用寿命�?),
('livelihood','/ˈlaɪvlihʊd/','n. 生活','means of support','Earn a livelihood.','谋生�?),
('mainstream','/ˈmeɪnstriːm/','n./adj. 主流','conventional','Mainstream culture.','主流文化�?),
('milestone','/ˈmaɪlstəʊn/','n. 重要节点','key point','A major milestone.','重要节点�?),
('offset','/ˈɒfset/','n. 抵消','compensation','Carbon offset.','碳补偿�?),
('onset','/ˈɒnset/','n. 开�?,'beginning','Onset of winter.','冬季开始�?),
('outbreak','/ˈaʊtbreɪk/','n. 爆发','sudden start','Disease outbreak.','疾病爆发�?),
('outlet','/ˈaʊtlet/','n. 出口;销�?,'release or market','Retail outlet.','零售店�?),
('outset','/ˈaʊtset/','n. 开�?,'start','From the outset.','从一开始�?),
('outskirts','/ˈaʊtskɜːts/','n. 郊区','outer edge','On the outskirts of the city.','在城市郊区�?),
('overhaul','/ˈəʊvəhɔːl/','n. 大修','major repair','System overhaul.','系统大修�?),
('override','/ˌəʊvəˈraɪd/','v. 推翻','to overrule','Override the decision.','推翻决定�?),
('oversight','/ˈəʊvəsaɪt/','n. 监督;疏忽','supervision or error','Government oversight.','政府监督�?),
('precedent','/ˈpresɪdənt/','n. 先例','previous case','Set a precedent.','开创先例�?),
('prospects','/ˈprɒspekts/','n. 前景','future chances','Career prospects.','职业前景�?),
('rationale','/ˌræʃəˈnɑːl/','n. 理由','reasoning','The rationale behind the decision.','决定背后的理由�?),
('repercussion','/ˌriːpəˈkʌʃn/','n. 反响','impact','Global repercussions.','全球影响�?),
('scope','/skəʊp/','n. 范围','range','Within the scope of the project.','在项目范围内�?),
('setback','/ˈsetbæk/','n. 挫折','reversal','A temporary setback.','暂时挫折�?),
('stalemate','/ˈsteɪlmeɪt/','n. 僵局','deadlock','Political stalemate.','政治僵局�?),
('stance','/stæns/','n. 立场','position','Take a firm stance.','采取坚定立场�?),
('threshold','/ˈθreʃhəʊld/','n. 阈�?,'limit','Pain threshold.','疼痛阈值�?),
('turnout','/ˈtɜːnaʊt/','n. 出席人数','attendance','Voter turnout was high.','投票率很高�?),
('upsurge','/ˈʌpsɜːdʒ/','n. 高涨','sharp rise','An upsurge in demand.','需求高涨�?),
('void','/vɔɪd/','n. 空白','empty space','Fill the void.','填补空白�?),
('watershed','/ˈwɔːtəʃed/','n. 转折�?,'turning point','A watershed moment.','转折时刻�?),
('whereabouts','/ˈweərəbaʊts/','n. 下落','location','Unknown whereabouts.','下落不明�?),
('afterthought','/ˈɑːftəθɔːt/','n. 事后想法','later idea','An afterthought.','事后想法�?),
('counterpart','/ˈkaʊntəpɑːt/','n. 对应的人或物','equivalent','His counterpart in the US.','他在美国的对应人�?),
('downside','/ˈdaʊnsaɪd/','n. 不利�?,'disadvantage','The downside of technology.','技术的不利面�?),
('upside','/ˈʌpsaɪd/','n. 好处','advantage','The upside is clear.','好处很明显�?),
('foreground','/ˈfɔːɡraʊnd/','n. 前景','front','In the foreground.','在前景中�?),
('background','/ˈbækɡraʊnd/','n. 背景','context','Cultural background.','文化背景�?),
('underlie','/ˌʌndəˈlaɪ/','v. 构成基础','to be basis of','Factors underlie the problem.','因素构成问题基础�?),
('undermine','/ˌʌndəˈmaɪn/','v. 破坏','to weaken','Undermine trust.','破坏信任�?),
('undergo','/ˌʌndəˈɡəʊ/','v. 经历','to experience','Undergo training.','经历培训�?),
('undertake','/ˌʌndəˈteɪk/','v. 承担','to take on','Undertake responsibility.','承担责任�?),
('oversee','/ˌəʊvəˈsiː/','v. 监督','to supervise','Oversee the project.','监督项目�?),
('overlook','/ˌəʊvəˈlʊk/','v. 忽视','to miss','Do not overlook details.','不要忽视细节�?),
('overtake','/ˌəʊvəˈteɪk/','v. 超越','to surpass','China overtook Japan.','中国超越了日本�?),
('overthrow','/ˌəʊvəˈθrəʊ/','v. 推翻','to remove from power','Overthrow the dictator.','推翻独裁者�?),
('overwhelm','/ˌəʊvəˈwelm/','v. 压�?,'to overcome completely','Feel overwhelmed.','感到不知所措�?),
('withstand','/wɪðˈstænd/','v. 承受','to resist','Withstand pressure.','承受压力�?),
('withdraw','/wɪðˈdrɔː/','v. 撤回','to remove','Withdraw the application.','撤回申请�?),
('withhold','/wɪðˈhəʊld/','v. 扣留','to hold back','Withhold information.','扣留信息�?),
('integrate','/ˈɪntɪɡreɪt/','v. 合并','to combine','Integrate data sources.','合并数据源�?),
('disintegrate','/dɪsˈɪntɪɡreɪt/','v. 瓦解','to fall apart','The empire disintegrated.','帝国瓦解了�?),
('coordinate','/kəʊˈɔːdɪneɪt/','v. 配合','to work together','Coordinate with the team.','与团队配合�?),
('subordinate','/səˈbɔːdɪnət/','adj. 下级�?,'lower in rank','Subordinate staff.','下级员工�?),
('insubordinate','/ˌɪnsəˈbɔːdɪnət/','adj. 不服从的','disobedient','Insubordinate behavior.','不服从行为�?),
('collaborate','/kəˈlæbəreɪt/','v. 合作','to work together','Collaborate on the project.','在项目上合作�?),
('elaborate','/ɪˈlæbərət/','adj. 精心�?,'detailed','An elaborate design.','精心设计�?),
('decorate','/ˈdekəreɪt/','v. 装饰','to adorn','Decorate the room.','装饰房间�?),
('commemorate','/kəˈmeməreɪt/','v. 庆祝','to celebrate','Commemorate the anniversary.','庆祝周年�?),
('accelerate','/əkˈseləreɪt/','v. 加快','to speed up','Accelerate development.','加快发展�?),
('decelerate','/diːˈseləreɪt/','v. 减�?,'to slow down','Decelerate the process.','减速过程�?),
('proliferate','/prəˈlɪfəreɪt/','v. 繁殖','to multiply','Ideas proliferate.','想法繁殖�?),
('generate','/ˈdʒenəreɪt/','v. 发电','to produce','Generate renewable energy.','产生可再生能源�?),
('regenerate','/riːˈdʒenəreɪt/','v. 再生','to regrow','Regenerate damaged tissue.','再生受损组织�?),
('degenerate','/dɪˈdʒenəreɪt/','v. 退�?,'to decline','Health degenerates.','健康退化�?),
('operate','/ˈɒpəreɪt/','v. 运营','to function','The system operates well.','系统运行良好�?),
('cooperate','/kəʊˈɒpəreɪt/','v. 合作','to work jointly','Cooperate with authorities.','与当局合作�?),
('tolerate','/ˈtɒləreɪt/','v. 容忍','to endure','Cannot tolerate injustice.','不能容忍不公正�?),
('elaborate','/ɪˈlæbəreɪt/','v. 详细说明','to expand on','Please elaborate.','请详细说明�?),
('collaborate','/kəˈlæbəreɪt/','v. 协作','to cooperate','Collaborate with partners.','与合作伙伴协作�?),
('integrate','/ˈɪntɪɡreɪt/','v. 综合','to unify','Integrate theory and practice.','理论与实践相结合�?),
('migrate','/maɪˈɡreɪt/','v. 移居','to relocate','Migrate to another country.','移居另一个国家�?),
('emigrate','/ˈemɪɡreɪt/','v. 移出','to leave a country','Emigrate from China.','从中国移出�?),
('immigrate','/ˈɪmɪɡreɪt/','v. 移入','to enter a country','Immigrate to Canada.','移入加拿大�?),
('navigate','/ˈnævɪɡeɪt/','v. 导航','to find way','Navigate the system.','操作系统�?),
('designate','/ˈdezɪɡneɪt/','v. 指定','to appoint','Designate a leader.','指定领导者�?),
('eliminate','/ɪˈlɪmɪneɪt/','v. 排除','to remove','Eliminate the possibility.','排除可能性�?),
('discriminate','/dɪˈskrɪmɪneɪt/','v. 区分;歧视','to distinguish unfairly','Discriminate between right and wrong.','区分对错�?),
('substantiate','/səbˈstænʃieɪt/','v. 证明','to provide evidence','Substantiate your claim.','证明你的声明�?),
('authenticate','/ɔːˈθentɪkeɪt/','v. 认证','to verify genuine','Authenticate the signature.','认证签名�?),
('facilitate','/fəˈsɪlɪteɪt/','v. 推动','to make easier','Facilitate communication.','推动沟通�?),`n('precipitate','/prɪˈsɪpɪteɪt/','v. 促使','to cause suddenly','Precipitate a crisis.','促使危机�?),
('reciprocate','/rɪˈsɪprəkeɪt/','v. 回报','to give in return','Reciprocate the kindness.','回报善意�?),
('incorporate','/ɪnˈkɔːpəreɪt/','v. 纳入','to include','Incorporate new data.','纳入新数据�?),
]
for w in d:
    cid += 1
    wr,ph,m,me,ex,et = w[0],w[1],w[2],w[3],w[4],w[5]
    r = w[6] if len(w) > 6 else ''
    rs = f', roots: "{r}"' if r else ''
    c += f'  {{ id: "w{cid:03d}", word: "{wr}", phonetic: "{ph}", meaning: "{m}", meaningEn: "{me}", example: "{ex}", exampleTranslation: "{et}"{rs}, level: "core" as const, tags: ["高频"] }},\n'
c += '];\n'
with open(VOCAB,'w',encoding='utf-8') as f:
    f.write(c)
print(f'Added {len(d)} words, total: {cid}')
