import re
VOCAB = r'D:\Claude cli\MyApp\yingo\src\data\vocab-sample.ts'
with open(VOCAB,'r',encoding='utf-8') as f:
    c = f.read()
c = re.sub(r'];\s*$', '', c)
ids = re.findall(r'id:\s*"w(\d+)"', c)
cid = max(int(x) for x in ids) if ids else 0
print(f'Current: w{cid}')
d = [
('hierarchy','/ˈhaɪərɑːki/','n. 等级','ranking system','Social hierarchy.','社会等级制度。','hier(神圣)+archy'),
('autonomy','/ɔːˈtɒnəmi/','n. 自主权','self-governance','Personal autonomy matters.','个人自主权很重要。','auto+nomy'),
('anarchy','/ˈænəki/','n. 无政府状态','no rule','Descent into anarchy.','陷入无政府状态。','an+archy'),
('monopoly','/məˈnɒpəli/','n. 垄断','exclusive control','Break the monopoly.','打破垄断。','mono+poly'),
('meritocracy','/ˌmerɪˈtɒkrəsi/','n. 精英管理','rule by merit','A meritocracy values talent.','精英管理重视人才。','merit+ocracy'),
('plutocracy','/pluːˈtɒkrəsi/','n. 财阀统治','rule by wealth','Plutocracy undermines democracy.','财阀统治破坏民主。','pluto+ocracy'),
('theocracy','/θiˈɒkrəsi/','n. 神权政治','rule by religion','A theocratic state.','神权国家。','theo+ocracy'),
('bureaucracy','/bjʊˈrɒkrəsi/','n. 官僚机构','complex admin','Reduce bureaucracy.','减少官僚机构。','bureau+cracy'),
('democracy','/dɪˈmɒkrəsi/','n. 民主制度','people power','Representative democracy.','代议制民主。','demo+cracy'),
('aristocracy','/ˌærɪˈstɒkrəsi/','n. 贵族','upper class','The landed aristocracy.','地主贵族。','aristo+cracy'),
('chronic','/ˈkrɒnɪk/','adj. 慢性的','long-term','Chronic disease management.','慢性病管理。','chron+ic'),
('acoustic','/əˈkuːstɪk/','adj. 声学的','relating to sound','Acoustic properties of the hall.','大厅声学特性。'),
('cosmetic','/kɒzˈmetɪk/','adj. 化妆的','beauty-related','Cosmetic surgery is common.','整形手术很常见。'),
('dramatic','/drəˈmætɪk/','adj. 戏剧性的','striking','Dramatic improvement.','戏剧性改善。'),
('erratic','/ɪˈrætɪk/','adj. 不稳定的','irregular','Erratic weather patterns.','不稳定天气模式。'),
('frantic','/ˈfræntɪk/','adj. 狂乱的','wildly anxious','Frantic search efforts.','狂乱搜索行动。'),
('gigantic','/dʒaɪˈɡæntɪk/','adj. 巨大的','enormous','A gigantic task.','巨大任务。'),
('hectic','/ˈhektɪk/','adj. 忙碌的','very busy','A hectic schedule.','忙碌日程。'),
('hypnotic','/hɪpˈnɒtɪk/','adj. 催眠的','sleep-inducing','A hypnotic rhythm.','催眠节奏。',
('idyllic','/ɪˈdɪlɪk/','adj. 田园诗般的','perfect and peaceful','An idyllic countryside.','田园诗般的乡村。'),
('ironic','/aɪˈrɒnɪk/','adj. 讽刺的','opposite to expected','An ironic twist.','讽刺性转折。'),
('lunatic','/ˈluːnətɪk/','adj. 疯狂的','crazy','A lunatic idea.','疯狂想法。'),
('nostalgic','/nɒˈstældʒɪk/','adj. 怀旧的','longing for past','A nostalgic feeling.','怀旧感。'),
('organic','/ɔːˈɡænɪk/','adj. 有机的','natural','Organic food is healthier.','有机食品更健康。'),
('pathetic','/pəˈθetɪk/','adj. 可怜的','pitiful','A pathetic attempt.','可怜的尝试。'),
('poetic','/pəʊˈetɪk/','adj. 诗意的','like poetry','A poetic description.','诗意描述。'),
('prolific','/prəˈlɪfɪk/','adj. 高产的','very productive','A prolific author.','高产作家。'),
('rhetoric','/ˈretərɪk/','adj. 修辞的','persuasive language','Empty rhetoric.','空洞修辞。'),
('stoic','/ˈstəʊɪk/','adj. 坚忍的','enduring calmly','A stoic response.','坚忍回应。'),
('toxic','/ˈtɒksɪk/','adj. 有害的','poisonous','Toxic relationship.','有害关系。','tox+ic'),
('tropic','/ˈtrɒpɪk/','n. 热带','hot region','Tropical tropics.','热带地区。'),
('chaotic','/keɪˈɒtɪk/','adj. 混乱的','disordered','A chaotic scene.','混乱场景。'),
('exotic','/ɪɡˈzɒtɪk/','adj. 异国的','foreign','Exotic flowers.','异国花卉。'),
('robotic','/rəʊˈbɒtɪk/','adj. 机器人的','like a robot','Robotic movements.','机器人动作。'),
('symbolic','/sɪmˈbɒlɪk/','adj. 象征性的','representing something','A symbolic gesture.','象征性姿态。'),
('empiric','/ɪmˈpɪrɪk/','adj. 经验的','based on experience','Empiric evidence.','经验证据。'),
('generic','/dʒəˈnerɪk/','adj. 通用的','not specific','A generic solution.','通用解决方案。'),
('heroic','/hɪˈrəʊɪk/','adj. 英勇的','brave','A heroic effort.','英勇努力。'),
('intrinsic','/ɪnˈtrɪnsɪk/','adj. 内在的','inherent','Intrinsic value.','内在价值。'),
('neurotic','/njʊˈrɒtɪk/','adj. 神经质的','anxious','Neurotic behavior.','神经质行为。'),
('patriotic','/ˌpætriˈɒtɪk/','adj. 爱国的','loving country','Patriotic sentiment.','爱国情怀。'),
('pedagogic','/ˌpedəˈɡɒdʒɪk/','adj. 教育学的','about teaching','Pedagogic innovation.','教育创新。'),
('strategic','/strəˈtiːdʒɪk/','adj. 战略上的','planned approach','Strategic planning.','战略规划。'),
('systemic','/sɪˈstemɪk/','adj. 系统性的','whole system','Systemic reform needed.','需要系统性改革。'),
('empiricism','/ɪmˈpɪrɪsɪzəm/','n. 经验主义','knowledge from experience','Scientific empiricism.','科学经验主义。'),
('skepticism','/ˈskeptɪsɪzəm/','n. 怀疑主义','doubt','Healthy skepticism.','健康怀疑主义。'),
('nihilism','/ˈnaɪɪlɪzəm/','n. 虚无主义','rejection of values','Philosophical nihilism.','哲学虚无主义。'),
('altruism','/ˈæltruɪzəm/','n. 利他主义','selflessness','Pure altruism.','纯粹利他主义。'),
('egoism','/ˈiːɡəʊɪzəm/','n. 利己主义','self-interest','Rational egoism.','理性利己主义。'),
('hedonism','/ˈhedənɪzəm/','n. 享乐主义','pleasure seeking','Cultural hedonism.','文化享乐主义。'),
('stoicism','/ˈstəʊɪsɪzəm/','n. 斯多葛主义','endurance philosophy','Practice stoicism.','实践斯多葛主义。'),
('empiricism','/ɪmˈpɪrɪsɪzəm/','n. 经验论','learning through senses','British empiricism.','英国经验论。'),
('rationalism','/ˈræʃnəlɪzəm/','n. 理性主义','reason-based philosophy','Enlightenment rationalism.','启蒙理性主义。'),
('pragmatism','/ˈpræɡmətɪzəm/','n. 实用主义','practical philosophy','American pragmatism.','美国实用主义。'),
('fatalism','/ˈfeɪtəlɪzəm/','n. 宿命论','belief in fate','Cultural fatalism.','文化宿命论。'),
('empiricist','/ɪmˈpɪrɪsɪst/','n. 经验主义者','one who believes in experience','An empiricist approach.','经验主义者方法。'),
('rationalist','/ˈræʃnəlɪst/','n. 理性主义者','reason believer','A rationalist view.','理性主义者观点。'),
('idealist','/aɪˈdɪəlɪst/','n. 理想主义者','perfection seeker','An incurable idealist.','不可救药的理想主义者。'),
('realist','/ˈrɪəlɪst/','n. 现实主义者','practical person','A pragmatic realist.','务实现实主义者。'),
('pluralist','/ˈplʊərəlɪst/','n. 多元主义者','believing in diversity','A pluralist society.','多元主义者社会。'),
('absolutist','/ˈæbsəluːtɪst/','n. 绝对主义者','extreme position','An absolutist view.','绝对主义者观点。'),
('individualist','/ˌɪndɪˈvɪdʒuəlɪst/','n. 个人主义者','independent person','An individualist approach.','个人主义者方法。'),
('collectivist','/kəˈlektɪvɪst/','n. 集体主义者','group-oriented','A collectivist culture.','集体主义者文化。'),
('extremist','/ɪkˈstriːmɪst/','n. 极端主义者','radical person','Religious extremist.','宗教极端主义者。'),
('activist','/ˈæktɪvɪst/','n. 活动家','campaigner','Environmental activist.','环保活动家。'),
('advocate','/ˈædvəkeɪt/','n. 倡导者','supporter','A patient advocate.','患者倡导者。'),
('analyst','/ˈænəlɪst/','n. 分析师','data expert','Financial analyst.','金融分析师。'),
('theorist','/ˈθɪərɪst/','n. 理论家','thinker','A political theorist.','政治理论家。'),
('practitioner','/prækˈtɪʃnə/','n. 从业者','professional','Medical practitioner.','医疗从业者。'),
('benefactor','/ˈbenɪfæktə/','n. 恩人','supporter','A wealthy benefactor.','富有的恩人。','bene(好)+fact(做)+or'),
('malefactor','/ˈmælɪfæktə/','n. 罪犯','wrongdoer','A convicted malefactor.','被判罪的罪犯。','male(坏)+fact(做)+or'),
('detractor','/dɪˈtræktə/','n. 诋毁者','critic','His detractors are vocal.','他的诋毁者很大声。'),
('contractor','/ˈkɒntræktə/','n. 承包商','builder','Independent contractor.','独立承包商。'),
('instructor','/ɪnˈstrʌktə/','n. 指导员','teacher','A fitness instructor.','健身指导员。'),
('director','/dəˈrektə/','n. 导演;董事','leader','Film director.','电影导演。'),
('inspector','/ɪnˈspektə/','n. 检查员','examiner','Safety inspector.','安全检查员。'),
('supervisor','/ˈsuːpəvaɪzə/','n. 主管','manager','Project supervisor.','项目主管。'),
('advisor','/ədˈvaɪzə/','n. 顾问','counselor','Financial advisor.','财务顾问。'),
('censor','/ˈsensə/','n. 审查员','content controller','Government censor.','政府审查员。'),
('predecessor','/ˈpriːdɪsesə/','n. 前任','previous holder','My predecessor in the role.','我在该职位的前任。','pre+de+cess(走)+or'),
('successor','/səkˈsesə/','n. 继任者','next holder','Appoint a successor.','任命继任者。'),
('antecessor','/ˌæntɪˈsesə/','n. 先行者','one who goes before','An antecessor in the field.','该领域的先行者。'),
('ancestor','/ˈænsestə/','n. 祖先','forefather','Distant ancestors.','远祖。','ante(前)+cess(走)+or'),
('conqueror','/ˈkɒŋkərə/','n. 征服者','one who conquers','William the Conqueror.','征服者威廉。'),
('governor','/ˈɡʌvənə/','n. 州长','state leader','State governor.','州长。'),
('counselor','/ˈkaʊnsələ/','n. 顾问','advisor','School counselor.','学校辅导员。'),
('chancellor','/ˈtʃɑːnsələ/','n. 总理;校长','top official','German chancellor.','德国总理。'),
('bachelor','/ˈbætʃələ/','n. 学士;单身汉','first degree','Bachelor of Arts.','文学学士。'),
('volunteer','/ˌvɒlənˈtɪə/','n. 志愿者','free helper','Volunteer at the shelter.','在收容所做志愿者。'),
('profiteer','/ˌprɒfɪˈtɪə/','n. 奸商','excess profit maker','War profiteer.','战争奸商。'),
('mutineer','/ˌmjuːtɪˈnɪə/','n. 叛变者','rebel','A ship mutineer.','船上叛变者。'),
('commander','/kəˈmɑːndə/','n. 司令官','military leader','Air force commander.','空军司令官。'),
]
for w in d:
    cid += 1
    wr,ph,m,me,ex,et = w[0],w[1],w[2],w[3],w[4],w[5]
    r = w[6] if len(w) > 6 else ''
    rs = f', roots: "{r}"' if r else ''
    c += f'  {{ id: "w{cid:03d}", word: "{wr}", phonetic: "{ph}", meaning: "{m}", meaningEn: "{me}", example: "{ex}", exampleTranslation: "{et}"{rs}, level: "core" as const, tags: ["高频"] }},\n'
c += '];\n'
with open(VOCAB,'w',encoding='utf-8') as f:
    f.write(c)
print(f'Added {len(d)} words, total: {cid}')