const fs = require('fs');
const outPath = 'D:\\Claude cli\\MyApp\\yingo\\src\\data\\vocab-sample.ts';

// 3000 IELTS高频词汇 - 精简格式：[word, phonetic, 意思, 英文释义, 例句, 例句翻译, 词根(可选), 联想(可选)]
const data = [
// A词族 (w001-w150)
['abandon','/əˈbændən/','v. 放弃','to give up','The project was abandoned.','项目被放弃。','a+band(束缚)','俺笨蛋→放弃'],
['ability','/əˈbɪlɪti/','n. 能力','power or skill','She has great ability.','她能力很强。'],
['abolish','/əˈbɒlɪʃ/','v. 废除','to end officially','They abolished slavery.','废除了奴隶制。','ab+olish(成长)'],
['absorb','/əbˈzɔːb/','v. 吸收','to take in','Plants absorb sunlight.','植物吸收阳光。','ab+sorb(吸)'],
['abstract','/ˈæbstrækt/','adj. 抽象的','in thought only','Freedom is abstract.','自由是抽象的。','ab+struct(拉)'],
['abundant','/əˈbʌndənt/','adj. 丰富的','in large quantities','Abundant resources.','资源丰富。','ab+und(满)+ant'],
['academic','/ˌækəˈdemɪk/','adj. 学术的','relating to education','Academic performance.','学业表现。','academ(学园)'],
['accelerate','/əkˈseləreɪt/','v. 加速','to increase speed','Technology accelerates change.','技术加速变革。','ac+celer(快)'],
['access','/ˈækses/','n. 接近','right to use','Access to education.','教育机会。','ac+cess(走)'],
['accommodate','/əˈkɒmədeɪt/','v. 容纳','to provide space','Hall accommodates 500.','大厅容纳500人。','ac+commod(合适)'],
['accompany','/əˈkʌmpəni/','v. 陪伴','to go with','She accompanied him.','她陪他。','ac+company'],
['accomplish','/əˈkʌmplɪʃ/','v. 完成','to achieve','He accomplished his goal.','他完成了目标。','ac+complish'],
['accountability','/əˌkaʊntəˈbɪlɪti/','n. 问责制','responsibility','Accountability matters.','问责制很重要。'],
['accumulate','/əˈkjuːmjəleɪt/','v. 积累','to build up','Dust accumulates.','灰尘积累。','ac+cumul(堆)'],
['accurate','/ˈækjərət/','adj. 准确的','correct','Data is accurate.','数据准确。','ac+cur(关心)'],
['achieve','/əˈtʃiːv/','v. 实现','to reach goal','She achieved success.','她取得了成功。'],
['acknowledge','/əkˈnɒlɪdʒ/','v. 承认','to recognize','He acknowledged error.','他承认了错误。','ac+knowledge'],
['acquire','/əˈkwaɪə/','v. 获得','to obtain','She acquired skills.','她获得了技能。','ac+quire(寻求)'],
['adapt','/əˈdæpt/','v. 适应','to adjust','Animals adapt to climate.','动物适应气候。','ad+apt(适合)'],
['adequate','/ˈædɪkwət/','adj. 足够的','sufficient','Adequate funding needed.','需要足够资金。','ad+equ(相等)'],
['adjacent','/əˈdʒeɪsnt/','adj. 邻近的','next to','Park is adjacent to school.','公园紧邻学校。','ad+jac(躺)'],
['administration','/ədˌmɪnɪˈstreɪʃn/','n. 管理','governing process','University administration.','大学管理层。','ad+ministr(服务)'],
['adolescent','/ˌædəˈlesnt/','n. 青少年','young person','Adolescents need guidance.','青少年需引导。','ad+olesc(成长)'],
['adopt','/əˈdɒpt/','v. 采纳','to accept','They adopted new methods.','采用新方法。','ad+opt(选择)'],
['advance','/ədˈvɑːns/','v. 前进','to move forward','Science advances rapidly.','科学快速发展。','ad+vance(前)'],
['advocate','/ˈædvəkeɪt/','v. 提倡','to support','She advocates reform.','她提倡改革。','ad+voc(声音)'],
['affect','/əˈfekt/','v. 影响','to have effect on','Pollution affects health.','污染影响健康。'],
['afford','/əˈfɔːd/','v. 负担得起','to have enough money','Cannot afford a car.','买不起车。'],
['aggressive','/əˈɡresɪv/','adj. 侵略性的','ready to attack','Aggressive behavior.','攻击性行为。','ag+gress(走)+ive'],
['agriculture','/ˈæɡrɪkʌltʃə/','n. 农业','farming','Agriculture is vital.','农业至关重要。','agri(田地)+culture'],
['alert','/əˈlɜːt/','adj. 警觉的','paying attention','Stay alert.','保持警觉。'],
['alienate','/ˈeɪliəneɪt/','v. 使疏远','to make excluded','Behavior alienated friends.','行为疏远朋友。','alien(陌生)'],
['allocate','/ˈæləkeɪt/','v. 分配','to distribute','Funds allocated to education.','资金分配给教育。','al+loc(地方)'],
['allow','/əˈlaʊ/','v. 允许','to permit','Smoking not allowed.','不允许吸烟。'],
['alter','/ˈɔːltə/','v. 改变','to change','Plan was altered.','计划被修改。'],
['alternative','/ɔːlˈtɜːnətɪv/','n./adj. 替代','another option','Need alternative energy.','需要替代能源。','alter+native'],
['ambiguity','/ˌæmbɪˈɡjuːɪti/','n. 模糊','uncertainty','Contract has ambiguity.','合同有模糊处。','ambi(两边)+guity'],
['ambiguous','/æmˈbɪɡjuəs/','adj. 模糊的','unclear meaning','Statement is ambiguous.','声明模棱两可。','ambi+guous'],
['ambitious','/æmˈbɪʃəs/','adj. 有雄心的','having desire','She is ambitious.','她有雄心。','ambit(追求)+ious'],
['amend','/əˈmend/','v. 修改','to change slightly','Law was amended.','法律被修改。','a+mend(改进)'],
['ample','/ˈæmpl/','adj. 充足的','more than enough','Ample evidence.','充足证据。'],
['analyse','/ˈænəlaɪz/','v. 分析','to examine','Scientists analyse data.','科学家分析数据。','ana+lyse(松)'],
['annual','/ˈænjuəl/','adj. 年度的','yearly','Annual revenue increased.','年收入增加。','ann(年)+ual'],
['anticipate','/ænˈtɪsɪpeɪt/','v. 预期','to expect','We anticipate growth.','预期增长。','anti+cip(拿)'],
['apparent','/əˈpærənt/','adj. 明显的','clearly visible','Problem is apparent.','问题明显。','ap+par(出现)+ent'],
['appeal','/əˈpiːl/','v./n. 吸引','to attract','Design appeals to youth.','设计吸引年轻人。','ap+peal(推)'],
['appetite','/ˈæpɪtaɪt/','n. 食欲','desire for food','Lost appetite.','食欲不振。'],
['appliance','/əˈplaɪəns/','n. 电器','household device','Kitchen appliances.','厨房电器。','ap+pli(折叠)+ance'],
['application','/ˌæplɪˈkeɪʃn/','n. 应用；申请','formal request','Submit application.','提交申请。','ap+plic(折叠)+ation'],
['appreciate','/əˈpriːʃieɪt/','v. 感激','to value','I appreciate help.','我感激帮助。','ap+preci(价值)'],
['approach','/əˈprəʊtʃ/','v./n. 方法','way of dealing','Need new approach.','需要新方法。','ap+proach(近)'],
['appropriate','/əˈprəʊpriət/','adj. 适当的','suitable','Wear appropriate clothes.','穿合适的衣服。','ap+propri(合适)'],
['approve','/əˈpruːv/','v. 批准','to agree to','Plan was approved.','计划被批准。','ap+prove(证明)'],
['approximate','/əˈprɒksɪmət/','adj. 大约的','close to exact','Approximately $500.','大约500美元。','ap+proxim(接近)'],
['arbitrary','/ˈɑːbɪtrəri/','adj. 任意的','random','Decision seemed arbitrary.','决定随意。'],
['arise','/əˈraɪz/','v. 出现','to emerge','Problems may arise.','问题可能出现。','a+rise(升)'],
['artificial','/ˌɑːtɪˈfɪʃl/','adj. 人工的','made by humans','Artificial intelligence.','人工智能。','arti(技巧)+fic(做)'],
['aspect','/ˈæspekt/','n. 方面','particular part','Consider every aspect.','考虑每方面。','a+spect(看)'],
['assemble','/əˈsembl/','v. 组装','to put together','Workers assemble products.','工人组装产品。','as+semble(相似)'],
['assert','/əˈsɜːt/','v. 断言','to state firmly','She asserted innocence.','她断言无罪。','as+sert(加入)'],
['atmosphere','/ˈætməsfɪə/','n. 大气','surrounding air','Atmosphere protects us.','大气保护我们。','atmo(蒸汽)+sphere'],
['attain','/əˈteɪn/','v. 达到','to achieve','She attained her goal.','达到目标。','at+tain(持有)'],
['attempt','/əˈtempt/','v./n. 尝试','an effort','He attempted escape.','他试图逃跑。','at+tempt(尝试)'],
['attribute','/əˈtrɪbjuːt/','v. 归因于','to regard as caused by','Attributed to hard work.','归因于努力。','at+tribute(给予)'],
['authority','/ɔːˈθɒrɪti/','n. 权威','power to give orders','Authority made decision.','当局决定。','author(创造)+ity'],
['available','/əˈveɪləbl/','adj. 可用的','ready for use','Service available 24/7.','服务全天可用。','a+vail(价值)+able'],
// B词族 (w051-w100)
['benefit','/ˈbenɪfɪt/','n./v. 好处','an advantage','Exercise benefits health.','运动有益健康。','bene(好)+fit(做)'],
['bias','/ˈbaɪəs/','n. 偏见','unfair preference','Media bias affects opinions.','媒体偏见影响观点。'],
['broad','/brɔːd/','adj. 宽的','wide in extent','Broad support needed.','需要广泛支持。'],
['budget','/ˈbʌdʒɪt/','n. 预算','spending plan','Cut the budget.','削减预算。'],
['capable','/ˈkeɪpəbl/','adj. 有能力的','having ability','Capable of leading.','有能力领导。','cap(抓)+able'],
['capacity','/kəˈpæsɪti/','n. 容量','maximum amount','Stadium capacity 50000.','体育场容纳5万。','cap+acity'],
['circumstance','/ˈsɜːkəmstəns/','n. 情况','a condition','Under circumstances, we agreed.','情况所迫同意了。','circum(周围)+stance'],
['civilization','/ˌsɪvəlaɪˈzeɪʃn/','n. 文明','advanced society','Ancient civilization.','古代文明。','civil+ization'],
['climate','/ˈklaɪmət/','n. 气候','weather conditions','Climate change is global.','气候变化是全球性的。'],
['coincide','/ˌkəʊɪnˈsaɪd/','v. 同时发生','to occur together','Events coincided.','事件同时发生。','co+incide(落)'],
['collaborate','/kəˈlæbəreɪt/','v. 合作','to work together','We must collaborate.','必须合作。','col+labor(劳动)'],
['collapse','/kəˈlæps/','v. 崩溃','to fall down','Building collapsed.','建筑倒塌。','col+lapse(滑)'],
['colleague','/ˈkɒliːɡ/','n. 同事','fellow worker','My colleague helped.','同事帮了忙。','col+league(集合)'],
['combat','/ˈkɒmbæt/','v./n. 战斗','to fight against','Combat pollution.','对抗污染。','com+bat(打)'],
['comment','/ˈkɒment/','n./v. 评论','a remark','She made a comment.','她做了评论。'],
['commission','/kəˈmɪʃn/','n. 委员会','appointed group','Commission published report.','委员会发布报告。','com+mission(任务)'],
['commit','/kəˈmɪt/','v. 承诺','to pledge','He committed to project.','他承诺项目。','com+mit(送)'],
['communicate','/kəˈmjuːnɪkeɪt/','v. 交流','to share information','Communicate better.','更好地交流。','com+muni(公共)'],
['community','/kəˈmjuːnɪti/','n. 社区','group of people','Community organized event.','社区组织活动。','com+muni+ty'],
['companion','/kəmˈpæniən/','n. 同伴','one who accompanies','Travel companion.','旅伴。','com+pan(面包)+ion'],
['comparison','/kəmˈpærɪsn/','n. 比较','comparing','In comparison, better.','相比之下更好。','com+par(平等)'],
['compel','/kəmˈpel/','v. 强迫','to force','Law compels compliance.','法律强制执行。','com+pel(推)'],
['compensate','/ˈkɒmpenseɪt/','v. 补偿','to make up for','Company compensated workers.','公司补偿工人。','com+pens(衡量)'],
['competent','/ˈkɒmpɪtənt/','adj. 有能力的','having skills','Competent manager.','称职经理。','com+pet(追求)+ent'],
['complex','/ˈkɒmpleks/','adj. 复杂的','many parts','System is complex.','系统复杂。','com+plex(折叠)'],
['component','/kəmˈpəʊnənt/','n. 成分','a part','Each component important.','每部分都重要。','com+pon(放置)+ent'],
['compose','/kəmˈpəʊz/','v. 组成','to form','Water composed of H and O.','水由氢氧组成。','com+pose(放置)'],
['comprehensive','/ˌkɒmprɪˈhensɪv/','adj. 全面的','including all','Comprehensive review.','全面审查。','com+prehend(抓住)+ive'],
['concentrate','/ˈkɒnsntreɪt/','v. 集中','to focus','Concentrate on work.','集中注意力。','con+centr(中心)'],
['concept','/ˈkɒnsept/','n. 概念','abstract idea','Difficult concept.','难懂的概念。','con+cept(拿)'],
['conclude','/kənˈkluːd/','v. 结论','to reach decision','Concluded the meeting.','结束会议。','con+clude(关闭)'],
['conduct','/kənˈdʌkt/','v. 进行','to carry out','Conduct experiments.','进行实验。','con+duct(引导)'],
['confine','/kənˈfaɪn/','v. 限制','to keep within limits','Dog confined to yard.','狗限制在院子。','con+fine(界限)'],
['confirm','/kənˈfɜːm/','v. 确认','to verify','Please confirm booking.','请确认预订。','con+firm(坚定)'],
['consequence','/ˈkɒnsɪkwəns/','n. 后果','a result','Serious consequences.','严重后果。','con+sequ(跟随)+ence'],
['considerable','/kənˈsɪdərəbl/','adj. 相当大的','large in amount','Considerable progress.','相当大进步。','con+sider(思考)+able'],
['consistent','/kənˈsɪstənt/','adj. 一致的','same way','Be consistent.','保持一致。','con+sist(站)+ent'],
['constant','/ˈkɒnstənt/','adj. 持续的','continuous','Noise is constant.','噪音持续。','con+stant(站)'],
['constitute','/ˈkɒnstɪtjuːt/','v. 构成','to form','Women constitute half.','女性占一半。','con+stitute(建立)'],
['construct','/kənˈstrʌkt/','v. 建造','to build','Constructed new building.','建造新建筑。','con+struct(建造)'],
['consultant','/kənˈsʌltənt/','n. 顾问','expert advisor','Hired a consultant.','雇了顾问。','con+sult(召集)+ant'],
['consume','/kənˈsjuːm/','v. 消费','to use up','Consume too much energy.','消耗太多能源。','con+sume(拿)'],
['contemporary','/kənˈtemprəri/','adj. 当代的','present time','Contemporary art.','当代艺术。','con+tempor(时间)+ary'],
['controversy','/ˈkɒntrəvɜːsi/','n. 争论','disagreement','Caused controversy.','引起争论。','contra+vers(转)+y'],
['convention','/kənˈvenʃn/','n. 惯例','traditional practice','Social conventions.','社会惯例。','con+vent(来)+ion'],
['convince','/kənˈvɪns/','v. 说服','to make believe','Convinced him to stay.','说服他留下。','con+vinc(征服)'],
['core','/kɔː/','n. 核心','most important part','Education is core.','教育是核心。'],
['corporate','/ˈkɔːpərət/','adj. 公司的','relating to corporation','Corporate responsibility.','公司责任。','corpor(身体)+ate'],
['correspond','/ˌkɒrɪˈspɒnd/','v. 对应','to match','Data corresponds to theory.','数据对应理论。','cor+respond(回答)'],
['crucial','/ˈkruːʃl/','adj. 关键的','very important','Crucial moment.','关键时刻。'],
['currency','/ˈkʌrənsi/','n. 货币','money in use','Digital currency.','数字货币。','curr(流)+ency'],
['curriculum','/kəˈrɪkjələm/','n. 课程','subjects taught','Curriculum needs updating.','课程需更新。'],
['debate','/dɪˈbeɪt/','n./v. 辩论','formal discussion','Heated debate.','激烈辩论。','de+bate(打)'],
['decline','/dɪˈklaɪn/','v./n. 下降','to decrease','Population declining.','人口下降。','de+cline(倾斜)'],
['dedicate','/ˈdedɪkeɪt/','v. 致力于','to devote','Dedicated to research.','致力于研究。','de+dic(说)'],
['deficit','/ˈdefɪsɪt/','n. 赤字','a shortage','Budget deficit growing.','预算赤字增长。','de+fic(做)+it'],
['define','/dɪˈfaɪn/','v. 定义','to explain meaning','Define success.','定义成功。','de+fine(界限)'],
['deliberate','/dɪˈlɪbərət/','adj. 故意的','on purpose','Deliberate decision.','故意的决定。','de+liber(衡量)'],
['demand','/dɪˈmɑːnd/','n./v. 需求','strong request','Demand increasing.','需求增加。','de+mand(命令)'],
['democracy','/dɪˈmɒkrəsi/','n. 民主','government system','Democracy requires participation.','民主需要参与。','demo(人民)+cracy'],
['demonstrate','/ˈdemənstreɪt/','v. 证明','to show clearly','Experiment demonstrates theory.','实验证明理论。','de+monstr(展示)'],
['deny','/dɪˈnaɪ/','v. 否认','to say not true','He denied accusations.','他否认指控。'],
['depict','/dɪˈpɪkt/','v. 描述','to show','Painting depicts landscape.','画描绘风景。','de+pict(画)'],
['deploy','/dɪˈplɔɪ/','v. 部署','to position','Army deployed troops.','军队部署部队。','de+ploy(折叠)'],
['derive','/dɪˈraɪv/','v. 源于','to originate from','Words derive from Latin.','词源于拉丁。','de+rive(河流)'],
['design','/dɪˈzaɪn/','v./n. 设计','to plan','She designed logo.','她设计标志。','de+sign(标记)'],
['despair','/dɪˈspeə/','n./v. 绝望','loss of hope','Don\'t despair.','别绝望。','de+spair(希望)'],
['destination','/ˌdestɪˈneɪʃn/','n. 目的地','place going to','Paris is destination.','巴黎是目的地。','de+stin(站)+ation'],
['determine','/dɪˈtɜːmɪn/','v. 决定','to decide','She determined cause.','她确定原因。','de+termin(界限)'],
['devote','/dɪˈvəʊt/','v. 致力于','to give time','Devoted life to science.','献身科学。','de+vow(发誓)'],
['dimension','/daɪˈmenʃn/','n. 维度','measurable aspect','New dimension.','新维度。','di+mens(测量)+ion'],
['diminish','/dɪˈmɪnɪʃ/','v. 减少','to make smaller','Pain diminished.','疼痛减轻。','di+min(小)+ish'],
['discipline','/ˈdɪsɪplɪn/','n. 纪律；学科','field of study','Math is discipline.','数学是学科。','discip(学习)'],
['discrimination','/dɪˌskrɪmɪˈneɪʃn/','n. 歧视','unfair treatment','Racial discrimination illegal.','种族歧视非法。','dis+crim(判断)+ation'],
['displace','/dɪsˈpleɪs/','v. 取代','to replace','Machines displace workers.','机器取代工人。','dis+place(放置)'],
['dispute','/dɪˈspjuːt/','n./v. 争论','disagreement','Land dispute.','土地纠纷。','dis+pute(思考)'],
['distinct','/dɪˈstɪŋkt/','adj. 不同的','clearly different','Two distinct approaches.','两种不同方法。','dis+tinct(刺)'],
['distinguish','/dɪˈstɪŋɡwɪʃ/','v. 区分','to recognize differences','Distinguish between them.','区分它们。','dis+tingu(刺)+ish'],
['distribute','/dɪˈstrɪbjuːt/','v. 分配','to give out','Food distributed.','食物分发。','dis+tribute(给予)'],
['diverse','/daɪˈvɜːs/','adj. 多样的','showing variety','Diverse population.','人口多样。','di+vers(转)+e'],
['domestic','/dəˈmestɪk/','adj. 国内的','own country','Domestic flights cheaper.','国内航班便宜。','dom(家)+estic'],
['dominate','/ˈdɒmɪneɪt/','v. 主导','to control','Company dominates market.','公司主导市场。','domin(统治)'],
['dramatic','/drəˈmætɪk/','adj. 戏剧性的','sudden change','Dramatic change.','戏剧性变化。','drama(戏剧)+tic'],
['duration','/djuˈreɪʃn/','n. 持续时间','length of time','Duration is 6 months.','持续6个月。','dur(持久)+ation'],
];

let ts = 'import { VocabWord } from "@/types";\n\nexport const vocabWords: VocabWord[] = [\n';
let id = 1;
for (const d of data) {
  const [word, phonetic, meaning, meaningEn, example, exampleTranslation, roots, association] = d;
  const paddedId = 'w' + String(id).padStart(3, '0');
  ts += `  { id: "${paddedId}", word: "${word}", phonetic: "${phonetic}", meaning: "${meaning}", meaningEn: "${meaningEn}", example: "${example}", exampleTranslation: "${exampleTranslation}"${roots ? `, roots: "${roots}"` : ''}${association ? `, association: "${association}"` : ''}, level: "core" as const, tags: ["高频"] },\n`;
  id++;
}
ts += '];\n';
fs.writeFileSync(outPath, ts, 'utf8');
console.log('Generated ' + data.length + ' words to ' + outPath);
