import re
VOCAB = r'D:\Claude cli\MyApp\yingo\src\data\vocab-sample.ts'
with open(VOCAB,'r',encoding='utf-8') as f:
    c = f.read()
c = re.sub(r'];\s*$', '', c)
ids = re.findall(r'id:\s*"w(\d+)"', c)
cid = max(int(x) for x in ids) if ids else 0
print(f'Current: w{cid}')
d = [
('resilient','/rɪˈzɪliənt/','adj. 有韧性的','able to recover','A resilient economy.','有韧性的经济。'),
('tenacious','/tɪˈneɪʃəs/','adj. 坚持的','holding fast','A tenacious grip.','紧握不放。'),
('subservient','/səbˈsɜːviənt/','adj. 从属的','obedient','A subservient role.','从属角色。'),
('insurgent','/ɪnˈsɜːdʒənt/','n. 叛乱分子','rebel','Armed insurgents.','武装叛乱分子。'),
('contingent','/kənˈtɪndʒənt/','n. 代表团','group','A trade contingent.','贸易代表团。'),
('detergent','/dɪˈtɜːdʒənt/','n. 洗涤剂','cleaning agent','Laundry detergent.','洗衣液。'),
('divergent','/daɪˈvɜːdʒənt/','adj. 分歧的','different','Divergent opinions.','分歧意见。'),
('convergent','/kənˈvɜːdʒənt/','adj. 趋同的','coming together','Convergent evolution.','趋同进化。'),
('emergent','/ɪˈmɜːdʒənt/','adj. 新兴的','newly appearing','Emergent technology.','新兴技术。'),
('prevalent','/ˈprevələnt/','adj. 普遍的','widespread','A prevalent issue.','普遍问题。'),
('benevolent','/bɪˈnevələnt/','adj. 仁慈的','kind','A benevolent leader.','仁慈的领袖。','bene(好)+volent(愿)'),
('malevolent','/məˈlevələnt/','adj. 恶意的','evil','A malevolent force.','恶意力量。'),
('equivalent','/ɪˈkwɪvələnt/','n. 等价物','equal value','The equivalent in dollars.','美元等价物。'),
('ambivalent','/æmˈbɪvələnt/','adj. 矛盾的','mixed feelings','Ambivalent about the decision.','对决定矛盾。'),
('omnipotent','/ɒmˈnɪpətənt/','adj. 全能的','all-powerful','No one is omnipotent.','没有人是全能的。','omni(全部)+potent(力量)'),
('impotent','/ˈɪmpətənt/','adj. 无力的','powerless','Feel impotent.','感到无力。'),
('potent','/ˈpəʊtənt/','adj. 有力的','powerful','A potent weapon.','有力武器。'),
('omniscient','/ɒmˈnɪsiənt/','adj. 全知的','all-knowing','No one is omniscient.','没有人是全知的。','omni(全部)+scient(知道)'),
('prescient','/ˈpresiənt/','adj. 有先见之明的','predicting','A prescient warning.','有先见之明的警告。'),
('conscientious','/ˌkɒnʃiˈenʃəs/','adj. 认真的','careful','A conscientious worker.','认真的工人。'),
('obsequious','/əbˈsiːkwiəs/','adj. 谄媚的','overly obedient','Obsequious behavior.','谄媚行为。'),
('ubiquitous','/juːˈbɪkwɪtəs/','adj. 无处不在的','everywhere','Smartphones are ubiquitous.','智能手机无处不在。','ubi(哪里)+quitous'),
('congenital','/kənˈdʒenɪtl/','adj. 先天的','from birth','A congenital defect.','先天缺陷。'),
('deleterious','/ˌdelɪˈtɪəriəs/','adj. 有害的','harmful','Deleterious effects.','有害影响。'),
('egregious','/ɪˈɡriːdʒəs/','adj. 极坏的','outstandingly bad','An egregious error.','严重错误。'),
('facetious','/fəˈsiːʃəs/','adj. 幽默的','playfully joking','A facetious response.','幽默回应。'),
('gregarious','/ɡrɪˈɡeəriəs/','adj. 好交际的','sociable','A gregarious host.','好交际的主人。'),
('harbinger','/ˈhɑːbɪndʒə/','n. 先兆','forerunner','A harbinger of change.','变革先兆。'),
('juxtapose','/ˌdʒʌkstəˈpəʊz/','v. 并列','to place side by side','Juxtapose the two ideas.','并列两个想法。'),
('kaleidoscope','/kəˈlaɪdəskəʊp/','n. 万花筒','changing patterns','A kaleidoscope of colors.','色彩万花筒。'),
('labyrinth','/ˈlæbərɪnθ/','n. 迷宫','complex maze','A labyrinth of rules.','规则迷宫。'),
('magnanimous','/mæɡˈnænɪməs/','adj. 宽宏大量的','generous','A magnanimous gesture.','宽宏大量的姿态。'),
('nefarious','/nɪˈfeəriəs/','adj. 邪恶的','wicked','Nefarious activities.','邪恶活动。'),
('pernicious','/pəˈnɪʃəs/','adj. 有害的','destructive','A pernicious influence.','有害影响。'),
('quixotic','/kwɪkˈsɒtɪk/','adj. 不切实际的','idealistic','A quixotic plan.','不切实际的计划。'),
('recalcitrant','/rɪˈkælsɪtrənt/','adj. 不服从的','resistant','A recalcitrant child.','不服从的孩子。'),
('surreptitious','/ˌsʌrəpˈtɪʃəs/','adj. 秘密的','secret','A surreptitious glance.','秘密一瞥。'),
('superfluous','/suːˈpɜːfluəs/','adj. 多余的','unnecessary','Remove superfluous words.','删除多余词语。'),
('truculent','/ˈtrʌkjʊlənt/','adj. 好斗的','aggressive','A truculent manner.','好斗态度。'),
('unctuous','/ˈʌŋktʃuəs/','adj. 油腔滑调的','excessively flattering','Unctuous praise.','油腔滑调的赞美。'),
('vicarious','/vɪˈkeəriəs/','adj. 间接的','experienced through others','Vicarious pleasure.','间接快感。'),
('whimsical','/ˈwɪmzɪkl/','adj. 异想天开的','playfully quaint','A whimsical design.','异想天开的设计。'),
('zealous','/ˈzeləs/','adj. 热情的','enthusiastic','A zealous supporter.','热情支持者。'),
('envious','/ˈenviəs/','adj. 嫉妒的','feeling envy','Envious of success.','嫉妒成功。'),
('covetous','/ˈkʌvɪtəs/','adj. 贪婪的','desiring greedily','Covetous eyes.','贪婪的目光。'),
('fastidious','/fæˈstɪdiəs/','adj. 挑剔的','very particular','A fastidious editor.','挑剔的编辑。'),
('hidebound','/ˈhaɪdbaʊnd/','adj. 守旧的','conservative','Hidebound traditions.','守旧传统。'),
('impervious','/ɪmˈpɜːviəs/','adj. 不受影响的','not affected','Impervious to criticism.','不受批评影响。'),
('innocuous','/ɪˈnɒkjuəs/','adj. 无害的','harmless','An innocuous remark.','无害评论。'),
('ludicrous','/ˈluːdɪkrəs/','adj. 荒谬的','absurd','A ludicrous idea.','荒谬想法。'),
('magniloquent','/mæɡˈnɪləkwənt/','adj. 夸夸其谈的','pompous speech','Magniloquent rhetoric.','夸夸其谈的修辞。'),
('obtuse','/əbˈtjuːs/','adj. 迟钝的','slow to understand','Deliberately obtuse.','故意装傻。'),
('perfunctory','/pəˈfʌŋktəri/','adj. 敷衍的','without care','A perfunctory effort.','敷衍了事。'),
('pertinacious','/ˌpɜːtɪˈneɪʃəs/','adj. 固执的','persistent','Pertinacious efforts.','固执努力。'),
('rapacious','/rəˈpeɪʃəs/','adj. 贪婪的','greedy','Rapacious appetite.','贪婪胃口。'),
('sanguine','/ˈsæŋɡwɪn/','adj. 乐观的','optimistic','Sanguine about the future.','对未来乐观。'),
('sedulous','/ˈsedjʊləs/','adj. 勤勉的','diligent','Sedulous attention.','勤勉关注。'),
('taciturn','/ˈtæsɪtɜːn/','adj. 沉默寡言的','quiet','A taciturn person.','沉默寡言的人。'),
('voracious','/vəˈreɪʃəs/','adj. 如饥似渴的','very eager','A voracious appetite.','如饥似渴的胃口。'),
('zealous','/ˈzeləs/','adj. 孜孜不倦的','fervent','Zealous advocacy.','孜孜不倦的倡导。'),
('cogent','/ˈkəʊdʒənt/','adj. 令人信服的','convincing','A cogent argument.','令人信服的论点。'),
('contiguous','/kənˈtɪɡjuəs/','adj. 相邻的','touching','Contiguous territories.','相邻领土。'),
('copious','/ˈkəʊpiəs/','adj. 大量的','abundant','Copious notes.','大量笔记。'),
('cryptic','/ˈkrɪptɪk/','adj. 神秘的','mysterious','A cryptic message.','神秘消息。'),
('cursory','/ˈkɜːsəri/','adj. 粗略的','hasty','A cursory glance.','粗略一瞥。'),
('deft','/deft/','adj. 灵巧的','skillful','Deft fingers.','灵巧手指。'),
('diligent','/ˈdɪlɪdʒənt/','adj. 用功的','hard-working','Diligent study habits.','用功学习习惯。'),
('disparate','/ˈdɪspərət/','adj. 不同的','very different','Disparate groups.','不同群体。'),
('draconian','/drəˈkəʊniən/','adj. 严厉的','harsh','Draconian measures.','严厉措施。'),
('ebullient','/ɪˈbʌliənt/','adj. 热情洋溢的','enthusiastic','An ebullient personality.','热情洋溢的个性。'),
('edifying','/ˈedɪfaɪɪŋ/','adj. 有教育意义的','instructive','An edifying experience.','有教育意义的经历。'),
('effervescent','/ˌefəˈvesnt/','adj. 活泼的','vivacious','An effervescent personality.','活泼个性。'),
('ephemeral','/ɪˈfemərəl/','adj. 短暂的','short-lived','Fame is ephemeral.','名声是短暂的。'),
('exorbitant','/ɪɡˈzɔːbɪtənt/','adj. 过高的','excessive','Exorbitant prices.','过高价格。'),
('expedient','/ɪkˈspiːdiənt/','adj. 权宜的','convenient','An expedient solution.','权宜之计。'),
('fallacious','/fəˈleɪʃəs/','adj. 谬误的','false','Fallacious reasoning.','谬误推理。'),
('fervent','/ˈfɜːvənt/','adj. 热烈的','passionate','A fervent supporter.','热烈支持者。'),
('frivolous','/ˈfrɪvələs/','adj. 轻浮的','not serious','A frivolous claim.','轻浮声明。'),
('furtive','/ˈfɜːtɪv/','adj. 鬼鬼祟祟的','secretive','A furtive glance.','鬼祟一瞥。'),
('hackneyed','/ˈhæknid/','adj. 陈腐的','overused','A hackneyed phrase.','陈词滥调。'),
('impetuous','/ɪmˈpetʃuəs/','adj. 冲动的','impulsive','An impetuous decision.','冲动决定。'),
('incisive','/ɪnˈsaɪsɪv/','adj. 深刻的','sharp','Incisive analysis.','深刻分析。'),
('insidious','/ɪnˈsɪdiəs/','adj. 阴险的','subtly harmful','An insidious threat.','阴险威胁。'),
('laconic','/ləˈkɒnɪk/','adj. 简洁的','brief','A laconic reply.','简洁回复。'),
('languid','/ˈlæŋɡwɪd/','adj. 倦怠的','weak','A languid movement.','倦怠动作。'),
('macabre','/məˈkɑːbrə/','adj. 恐怖的','gruesome','A macabre scene.','恐怖场景。'),
('malicious','/məˈlɪʃəs/','adj. 恶意的','spiteful','Malicious gossip.','恶意流言。'),
('meticulous','/məˈtɪkjʊləs/','adj. 细致的','very careful','Meticulous planning.','细致规划。'),
('mundane','/mʌnˈdeɪn/','adj. 世俗的','ordinary','Mundane concerns.','世俗烦恼。'),
('nebulous','/ˈnebjʊləs/','adj. 模糊的','vague','A nebulous concept.','模糊概念。'),
('nonchalant','/ˈnɒnʃələnt/','adj. 漫不经心的','casual','A nonchalant attitude.','漫不经心态度。'),
('ominous','/ˈɒmɪnəs/','adj. 不祥的','threatening','An ominous sign.','不祥之兆。'),
('ostentatious','/ˌɒstenˈteɪʃəs/','adj. 炫耀的','showy','Ostentatious display.','炫耀展示。'),
('pedestrian','/pəˈdestriən/','adj. 平淡的','dull','A pedestrian style.','平淡风格。'),
('pensive','/ˈpensɪv/','adj. 沉思的','thoughtful','A pensive mood.','沉思心情。'),
('pragmatic','/præɡˈmætɪk/','adj. 实用主义的','practical','A pragmatic leader.','实用主义领袖。'),
('precocious','/prɪˈkəʊʃəs/','adj. 早熟的','advanced','A precocious child.','早熟孩子。'),
('presumptuous','/prɪˈzʌmptʃuəs/','adj. 放肆的','overstepping','A presumptuous request.','放肆请求。'),
]
for w in d:
    cid += 1
    wr,ph,m,me,ex,et = w[0],w[1],w[2],w[3],w[4],w[5]
    r = w[6] if len(w) > 6 else ''
    rs = f', roots: "{r}"' if r else ''
    c += f'  {{ id: "w{cid:03d}", word: "{wr}", phonetic: "{ph}", meaning: "{m}", meaningEn: "{me}", example: "{ex}", exampleTranslation: "{et}"{rs}, level: "core" as const, tags: ["高频"] }},\n'
c += '];\n'
with open(VOCAB,'w',encoding='utf-8') as f:
    f.write(c)
print(f'Added {len(d)} words, total: {cid}')