import re
VOCAB = r'D:\Claude cli\MyApp\yingo\src\data\vocab-sample.ts'
with open(VOCAB,'r',encoding='utf-8') as f:
    c = f.read()
c = re.sub(r'];\s*$', '', c)
ids = re.findall(r'id:\s*"w(\d+)"', c)
cid = max(int(x) for x in ids) if ids else 0
print(f'Current: w{cid}')
d = [
('quantify','/ˈkwɒntɪfaɪ/','v. 量化','to measure','Quantify the results.','量化结果。','quant(量)+ify'),
('rectify','/ˈrektɪfaɪ/','v. 纠正','to correct','Rectify the error.','纠正错误。','rect(正确)+ify'),
('signify','/ˈsɪɡnɪfaɪ/','v. 表示','to indicate','What does it signify?','这表示什么？','sign(标记)+ify'),
('simplify','/ˈsɪmplɪfaɪ/','v. 简化','to make simple','Simplify the process.','简化流程。'),
('specify','/ˈspesɪfaɪ/','v. 指定','to state exactly','Specify the requirements.','指定要求。'),
('testify','/ˈtestɪfaɪ/','v. 作证','to give evidence','Testify in court.','在法庭作证。'),
('verify','/ˈverɪfaɪ/','v. 验证','to confirm','Verify the data.','验证数据。','ver(真实)+ify'),
('modify','/ˈmɒdɪfaɪ/','v. 改变','to alter','Modify the design.','改变设计。','mod(方式)+ify'),
('diversify','/daɪˈvɜːsɪfaɪ/','v. 多样化','to vary','Diversify investments.','多样化投资。'),
('intensify','/ɪnˈtensɪfaɪ/','v. 加强','to strengthen','Intensify efforts.','加大力度。'),
('magnify','/ˈmæɡnɪfaɪ/','v. 放大','to enlarge','Magnify the image.','放大图像。','magn(大)+ify'),
('justify','/ˈdʒʌstɪfaɪ/','v. 辩护','to defend','Justify your actions.','为你的行为辩护。'),
('notify','/ˈnəʊtɪfaɪ/','v. 通知','to inform','Notify the team.','通知团队。','not(标记)+ify'),
('ratify','/ˈrætɪfaɪ/','v. 批准','to approve','Ratify the treaty.','批准条约。'),
('gratify','/ˈɡrætɪfaɪ/','v. 使满意','to please','Gratify the audience.','使观众满意。'),
('nullify','/ˈnʌlɪfaɪ/','v. 使无效','to void','Nullify the contract.','使合同无效。'),
('clarify','/ˈklærɪfaɪ/','v. 澄清','to make clear','Clarify your position.','澄清你的立场。'),
('exemplify','/ɪɡˈzemplɪfaɪ/','v. 例证','to illustrate','Exemplify the theory.','例证理论。'),
('stratify','/ˈstrætɪfaɪ/','v. 分层','to arrange in layers','Stratify the data.','将数据分层。'),
('ossify','/ˈɒsɪfaɪ/','v. 僵化','to become rigid','Bureaucracy ossifies.','官僚体制僵化。'),
('petrify','/ˈpetrɪfaɪ/','v. 使石化;使害怕','to frighten greatly','The threat petrified them.','威胁吓坏了他们。'),
('intensify','/ɪnˈtensɪfaɪ/','v. 激化','to make intense','Intensify the conflict.','激化冲突。'),
('jeopardize','/ˈdʒepədaɪz/','v. 危害','to endanger','Jeopardize the mission.','危害任务。'),
('mobilize','/ˈməʊbɪlaɪz/','v. 动员','to organize','Mobilize resources.','动员资源。'),
('neutralize','/ˈnjuːtrəlaɪz/','v. 抵消','to counteract','Neutralize the threat.','抵消威胁。'),
('normalize','/ˈnɔːməlaɪz/','v. 正常化','to make normal','Normalize relations.','关系正常化。'),
('prioritize','/praɪˈɒrɪtaɪz/','v. 优先处理','to rank importance','Prioritize tasks.','优先处理任务。'),
('scrutinize','/ˈskruːtɪnaɪz/','v. 审查','to examine closely','Scrutinize the contract.','审查合同。'),
('sterilize','/ˈsterɪlaɪz/','v. 消毒','to make sterile','Sterilize the equipment.','消毒设备。'),
('subsidize','/ˈsʌbsɪdaɪz/','v. 资助','to fund','Subsidize education.','资助教育。'),
('summarize','/ˈsʌməraɪz/','v. 概括','to give summary','Summarize the findings.','概括发现。'),
('symbolize','/ˈsɪmbəlaɪz/','v. 象征','to represent','The dove symbolizes peace.','鸽子象征和平。'),
('synchronize','/ˈsɪŋkrənaɪz/','v. 同步','to align in time','Synchronize watches.','同步手表。'),
('synthetic','/sɪnˈθetɪk/','adj. 合成的','artificial','Synthetic materials.','合成材料。'),
('systemic','/sɪˈstemɪk/','adj. 系统的','affecting whole system','Systemic change is needed.','需要系统性变革。'),
('empirical','/ɪmˈpɪrɪkl/','adj. 经验的','based on data','Empirical findings.','经验发现。'),
('endemic','/enˈdemɪk/','adj. 地方性的','native to a region','Endemic species.','地方性物种。'),
('epidemic','/ˌepɪˈdemɪk/','n. 流行病','widespread disease','Flu epidemic spreads.','流感流行病蔓延。','epi(在上)+dem(人民)+ic'),
('pandemic','/pænˈdemɪk/','n. 大流行病','global disease','COVID-19 was a pandemic.','新冠是大流行病。','pan(全部)+dem(人民)+ic'),
('sporadic','/spəˈrædɪk/','adj. 零星的','occasional','Sporadic outbreaks.','零星爆发。'),
('chronic','/ˈkrɒnɪk/','adj. 长期的','persistent','Chronic unemployment.','长期失业。'),
('erratic','/ɪˈrætɪk/','adj. 不稳定的','unpredictable','Erratic behavior.','不稳定行为。'),
('eclectic','/ɪˈklektɪk/','adj. 兼收并蓄的','varied','An eclectic taste.','兼收并蓄的品味。'),
('dynamic','/daɪˈnæmɪk/','adj. 活跃的','energetic','A dynamic leader.','活跃领袖。'),
('static','/ˈstætɪk/','adj. 停滞的','unchanging','Static growth.','停滞增长。'),
('prolific','/prəˈlɪfɪk/','adj. 多产的','very productive','A prolific writer.','多产作家。'),
('systematic','/ˌsɪstəˈmætɪk/','adj. 有条理的','organized','A systematic review.','有条理的审查。'),
('empiric','/ɪmˈpɪrɪk/','adj. 经验主义的','based on experience','Empiric approach.','经验主义方法。'),
('dogmatic','/dɒɡˈmætɪk/','adj. 教条的','stubborn beliefs','Dogmatic views.','教条观点。'),
('pragmatic','/præɡˈmætɪk/','adj. 务实的','practical','Pragmatic solution.','务实方案。'),
('enigmatic','/ˌenɪɡˈmætɪk/','adj. 神秘的','mysterious','An enigmatic smile.','神秘微笑。'),
('axiomatic','/ˌæksɪˈmætɪk/','adj. 不言而喻的','self-evident','An axiomatic truth.','不言而喻的真理。'),
('emblematic','/ˌembləˈmætɪk/','adj. 象征性的','symbolic','Emblematic of change.','变革象征。'),
('phlegmatic','/fleɡˈmætɪk/','adj. 冷静的','calm','A phlegmatic response.','冷静回应。'),
('schematic','/skiːˈmætɪk/','adj. 图解的','diagrammatic','A schematic diagram.','示意图。'),
('problematic','/ˌprɒbləˈmætɪk/','adj. 有问题的','difficult','A problematic situation.','有问题的局面。'),
('idiomatic','/ˌɪdiəˈmætɪk/','adj. 地道的','using idioms','Idiomatic English.','地道英语。'),
('aromatic','/ˌærəˈmætɪk/','adj. 芳香的','fragrant','Aromatic herbs.','芳香草药。'),
('cinematic','/ˌsɪnɪˈmætɪk/','adj. 电影的','relating to film','Cinematic experience.','电影体验。'),
('oceanic','/ˌəʊʃiˈænɪk/','adj. 海洋的','relating to ocean','Oceanic research.','海洋研究。'),
('volcanic','/vɒlˈkænɪk/','adj. 火山的','from volcano','Volcanic eruption.','火山喷发。'),
('organic','/ɔːˈɡænɪk/','adj. 有机的','natural','Organic farming is popular.','有机农业很流行。'),
('mechanic','/mɪˈkænɪk/','n. 技工','repair person','Car mechanic.','汽车技工。'),
('titanic','/taɪˈtænɪk/','adj. 巨大的','enormous','A titanic effort.','巨大努力。'),
('botanic','/bəˈtænɪk/','adj. 植物的','relating to plants','Botanic garden.','植物园。'),
('ocean','/ˈəʊʃn/','n. 海洋','vast sea','Cross the ocean.','跨越海洋。'),
('atmosphere','/ˈætməsfɪə/','n. 大气层','air surrounding earth','Protect the atmosphere.','保护大气层。'),
('biosphere','/ˈbaɪəsfɪə/','n. 生物圈','living world','The biosphere is fragile.','生物圈很脆弱。'),
('hemisphere','/ˈhemɪsfɪə/','n. 半球','half sphere','Northern hemisphere.','北半球。'),
('stratosphere','/ˈstrætəsfɪə/','n. 平流层','upper atmosphere','Stratospheric ozone.','平流层臭氧。'),
('lithosphere','/ˈlɪθəsfɪə/','n. 岩石圈','earth crust','The tectonic lithosphere.','构造岩石圈。'),
('sphere','/sfɪə/','n. 领域','area of activity','In every sphere of life.','在生活的每个领域。'),
('cashmere','/ˈkæʃmɪə/','n. 羊绒','fine wool','Cashmere sweater.','羊绒毛衣。'),
('pioneer','/ˌpaɪəˈnɪə/','n. 先驱','early adopter','A pioneer in the field.','该领域先驱。'),
('volunteer','/ˌvɒlənˈtɪə/','n. 志愿者','unpaid helper','A volunteer program.','志愿者项目。'),
('mutineer','/ˌmjuːtɪˈnɪə/','n. 叛变者','rebel','A mutineer on the ship.','船上的叛变者。'),
('engineer','/ˌendʒɪˈnɪə/','n. 工程师','technical expert','Software engineer.','软件工程师。'),
('auctioneer','/ˌɔːkʃəˈnɪə/','n. 拍卖师','auction conducter','The auctioneer sold the painting.','拍卖师卖出了画。'),
('profiteer','/ˌprɒfɪˈtɪə/','n. 牟利者','person making excess profit','War profiteer.','战争牟利者。'),
('commander','/kəˈmɑːndə/','n. 指挥官','military leader','A naval commander.','海军指挥官。'),
('philosopher','/fɪˈlɒsəfə/','n. 哲学家','thinker','A Greek philosopher.','希腊哲学家。'),
('astronomer','/əˈstrɒnəmə/','n. 天文学家','star scientist','An astronomer studies stars.','天文学家研究恒星。'),
('biologist','/baɪˈɒlədʒɪst/','n. 生物学家','life scientist','A marine biologist.','海洋生物学家。'),
('geologist','/dʒiˈɒlədʒɪst/','n. 地质学家','earth scientist','A geologist studies rocks.','地质学家研究岩石。'),
('ecologist','/ɪˈkɒlədʒɪst/','n. 生态学家','environmental scientist','An ecologist studies ecosystems.','生态学家研究生态系统。'),
('archaeologist','/ˌɑːkiˈɒlədʒɪst/','n. 考古学家','ancient artifacts expert','An archaeologist excavates ruins.','考古学家挖掘遗迹。'),
('psychologist','/saɪˈkɒlədʒɪst/','n. 心理学家','mind expert','A clinical psychologist.','临床心理学家。'),
('sociologist','/ˌsəʊʃiˈɒlədʒɪst/','n. 社会学家','society expert','A sociologist studies behavior.','社会学家研究行为。'),
('economist','/ɪˈkɒnəmɪst/','n. 经济学家','economy expert','A Nobel economist.','诺贝尔经济学家。'),
('statistician','/ˌstætɪˈstɪʃn/','n. 统计学家','data expert','A statistician analyzes data.','统计学家分析数据。'),
('mathematician','/ˌmæθəməˈtɪʃn/','n. 数学家','math expert','A brilliant mathematician.','杰出数学家。'),
('physicist','/ˈfɪzɪsɪst/','n. 物理学家','physics expert','A theoretical physicist.','理论物理学家。'),
('chemist','/ˈkemɪst/','n. 化学家','chemistry expert','An organic chemist.','有机化学家。'),
]
for w in d:
    cid += 1
    wr,ph,m,me,ex,et = w[0],w[1],w[2],w[3],w[4],w[5]
    r = w[6] if len(w) > 6 else ''
    rs = f', roots: "{r}"' if r else ''
    c += f'  {{ id: "w{cid:03d}", word: "{wr}", phonetic: "{ph}", meaning: "{m}", meaningEn: "{me}", example: "{ex}", exampleTranslation: "{et}"{rs}, level: "core" as const, tags: ["高频"] }},\n'
c += '];\n'
with open(VOCAB,'w',encoding='utf-8') as f:
    f.write(c)
print(f'Added {len(d)} words, total: {cid}')