import re
VOCAB = r'D:\Claude cli\MyApp\yingo\src\data\vocab-sample.ts'
with open(VOCAB,'r',encoding='utf-8') as f:
    c = f.read()
c = re.sub(r'];\s*$', '', c)
ids = re.findall(r'id:\s*"w(\d+)"', c)
cid = max(int(x) for x in ids) if ids else 0
print(f'Current: w{cid}')
d = [
('implication','/ˌɪmplɪˈkeɪʃn/','n. 含义','consequence','The implications are serious.','含义很严重。','im+plic(折叠)+ation'),
('ramification','/ˌræmɪfɪˈkeɪʃn/','n. 后果','consequence','Consider the ramifications.','考虑后果。'),
('repercussion','/ˌriːpəˈkʌʃn/','n. 影响','consequence','Economic repercussions.','经济影响。'),
('aftermath','/ˈɑːftəmæθ/','n. 余波','consequences','Aftermath of the earthquake.','地震余波。'),
('culmination','/ˌkʌlmɪˈneɪʃn/','n. 顶点','highest point','The culmination of years of work.','多年工作的顶点。'),
('genesis','/ˈdʒenəsɪs/','n. 起源','origin','The genesis of the idea.','想法的起源。'),
('antithesis','/ænˈtɪθəsɪs/','n. 对立面','direct opposite','The antithesis of freedom.','自由的对立面。'),
('synthesis','/ˈsɪnθəsɪs/','n. 综合','combination','A synthesis of ideas.','思想综合。'),
('hypothesis','/haɪˈpɒθəsɪs/','n. 前提','assumption','Based on the hypothesis.','基于前提。'),
('parenthesis','/pəˈrenθəsɪs/','n. 括号','bracket','Words in parenthesis.','括号中的词。'),
('prognosis','/prɒɡˈnəʊsɪs/','n. 预后','forecast','The prognosis is positive.','预后良好。'),
('diagnosis','/ˌdaɪəɡˈnəʊsɪs/','n. 诊断','identification','Accurate diagnosis is crucial.','准确诊断很关键。'),
('thesis','/ˈθiːsɪs/','n. 论点','argument','Support your thesis.','支持你的论点。'),
('crisis','/ˈkraɪsɪs/','n. 危机','emergency','Economic crisis.','经济危机。'),
('analysis','/əˈnæləsɪs/','n. 分析','detailed examination','Data analysis is essential.','数据分析很关键。'),
('axis','/ˈæksɪs/','n. 轴','central line','The earth rotates on its axis.','地球绕轴旋转。'),
('basis','/ˈbeɪsɪs/','n. 基础','foundation','On a voluntary basis.','在自愿基础上。'),
('emphasis','/ˈemfəsɪs/','n. 强调','stress','Place emphasis on quality.','强调质量。'),
('ellipsis','/ɪˈlɪpsɪs/','n. 省略','omission','Use an ellipsis for brevity.','用省略号表示简洁。'),
('oasis','/əʊˈeɪsɪs/','n. 绿洲','refuge','An oasis in the desert.','沙漠中的绿洲。'),
('nemesis','/ˈneməsɪs/','n. 天敌','arch enemy','His own nemesis.','他自己的天敌。'),
('synopsis','/sɪˈnɒpsɪs/','n. 概要','summary','A synopsis of the book.','书的概要。'),
('abrupt','/əˈbrʌpt/','adj. 突然的','sudden and unexpected','An abrupt departure.','突然离开。','ab+rupt(断)'),
('corrupt','/kəˈrʌpt/','adj. 腐败的','dishonest','Corrupt officials.','腐败官员。','cor+rupt(破)'),
('disrupt','/dɪsˈrʌpt/','v. 扰乱','to interrupt','Disrupt the market.','扰乱市场。','dis+rupt(破)'),
('erupt','/ɪˈrʌpt/','v. 爆发','to explode','Volcanoes erupt.','火山爆发。','e+rupt(破)'),
('interrupt','/ˌɪntəˈrʌpt/','v. 打断','to break in','Do not interrupt.','不要打断。'),
('bankrupt','/ˈbæŋkrʌpt/','adj. 破产的','unable to pay','The company went bankrupt.','公司破产了。'),
('construct','/kənˈstrʌkt/','v. 建造','to build','Construct a building.','建造建筑。','con+struct(建造)'),
('instruct','/ɪnˈstrʌkt/','v. 指导','to teach','Instruct the students.','指导学生。'),
('obstruct','/əbˈstrʌkt/','v. 阻碍','to block','Obstruct the passage.','阻碍通道。'),
('destruct','/dɪˈstrʌkt/','v. 破坏','to destroy','Self-destruct mechanism.','自毁机制。'),
('infrastructure','/ˈɪnfrəstrʌktʃə/','n. 基础设施','basic facilities','Transport infrastructure.','交通基础设施。'),
('superstructure','/ˈsuːpəstrʌktʃə/','n. 上层建筑','built above','Social superstructure.','社会上层建筑。'),
('manufacture','/ˌmænjuˈfæktʃə/','v. 制造','to produce','Manufacture goods.','制造商品。','manu(手)+fact(做)+ure'),
('architecture','/ˈɑːkɪtektʃə/','n. 建筑学','art of building','Modern architecture.','现代建筑学。','archi(主要)+tect(建造)+ure'),
('lecture','/ˈlektʃə/','n. 讲课','educational talk','Attend a lecture.','参加讲座。'),
('literature','/ˈlɪtrətʃə/','n. 文学','written works','English literature.','英国文学。'),
('agriculture','/ˈæɡrɪkʌltʃə/','n. 农业','farming','Sustainable agriculture.','可持续农业。','agri(田地)+culture'),
('horticulture','/ˈhɔːtɪkʌltʃə/','n. 园艺','garden art','Study horticulture.','学习园艺。','horti(花园)+culture'),
('aquaculture','/ˈækwəkʌltʃə/','n. 水产养殖','fish farming','Aquaculture is growing.','水产养殖在增长。','aqua(水)+culture'),
('silviculture','/ˈsɪlvɪkʌltʃə/','n. 林学','forest management','Silviculture practices.','林学实践。'),
('subculture','/ˈsʌbkʌltʃə/','n. 亚文化','cultural subgroup','Youth subculture.','青年亚文化。'),
('counterculture','/ˈkaʊntəkʌltʃə/','n. 反文化','opposing culture','The counterculture movement.','反文化运动。'),
('enculturation','/ɪnˌkʌltʃəˈreɪʃn/','n. 文化适应','cultural learning','Enculturation begins at birth.','文化适应从出生开始。'),
('acculturation','/əˌkʌltʃəˈreɪʃn/','n. 文化融合','cultural exchange','Immigrant acculturation.','移民文化融合。'),
('multicultural','/ˌmʌltɪˈkʌltʃərəl/','adj. 多元文化的','many cultures','A multicultural society.','多元文化社会。'),
('cross-cultural','/ˌkrɒsˈkʌltʃərəl/','adj. 跨文化的','between cultures','Cross-cultural understanding.','跨文化理解。'),
('intercultural','/ˌɪntəˈkʌltʃərəl/','adj. 文化间的','between cultures','Intercultural dialogue.','文化间对话。'),
('substantive','/ˈsʌbstəntɪv/','adj. 实质性的','meaningful','Substantive progress.','实质性进展。'),
('provisional','/prəˈvɪʒənl/','adj. 临时的','temporary','A provisional government.','临时政府。'),
('contingent','/kənˈtɪndʒənt/','adj. 有条件的','dependent on','Contingent on funding.','取决于资金。'),
('mandatory','/ˈmændətəri/','adj. 强制的','required','Mandatory attendance.','强制出席。'),
('obligatory','/əˈblɪɡətəri/','adj. 义务的','required','An obligatory step.','必要步骤。'),
('voluntary','/ˈvɒləntəri/','adj. 自愿的','by choice','Voluntary participation.','自愿参与。'),
('discretionary','/dɪˈskreʃənəri/','adj. 自由决定的','optional','Discretionary spending.','可自由支配支出。'),
('compulsory','/kəmˈpʌlsəri/','adj. 必须的','forced','Compulsory education.','义务教育。'),
('preliminary','/prɪˈlɪmɪnəri/','adj. 初步的','initial','Preliminary results.','初步结果。'),
('supplementary','/ˌsʌplɪˈmentəri/','adj. 补充的','additional','Supplementary materials.','补充材料。'),
('complementary','/ˌkɒmplɪˈmentəri/','adj. 互补的','completing','Complementary skills.','互补技能。'),
('contradictory','/ˌkɒntrəˈdɪktəri/','adj. 矛盾的','opposing','Contradictory statements.','矛盾陈述。'),
('preparatory','/prɪˈpærətəri/','adj. 预备的','preparing','Preparatory course.','预备课程。'),
('explanatory','/ɪkˈsplænətəri/','adj. 解释的','explaining','An explanatory note.','解释性说明。'),
('conciliatory','/kənˈsɪliətəri/','adj. 安抚的','appeasing','A conciliatory tone.','安抚语气。'),
('inflammatory','/ɪnˈflæmətəri/','adj. 煽动性的','provoking','Inflammatory language.','煽动性语言。'),
('legendary','/ˈledʒəndəri/','adj. 传奇的','famous','A legendary figure.','传奇人物。'),
('momentous','/məˈmentəs/','adj. 重大的','very important','A momentous decision.','重大决定。'),
('catastrophic','/ˌkætəˈstrɒfɪk/','adj. 灾难性的','disastrous','A catastrophic event.','灾难性事件。'),
('systematic','/ˌsɪstəˈmætɪk/','adj. 系统的','methodical','A systematic approach.','系统方法。'),
('empirical','/ɪmˈpɪrɪkl/','adj. 经验的','based on observation','Empirical research.','经验研究。'),
('theoretical','/ˌθɪəˈretɪkl/','adj. 理论的','based on theory','Theoretical framework.','理论框架。'),
('hypothetical','/ˌhaɪpəˈθetɪkl/','adj. 假设的','supposed','A hypothetical scenario.','假设场景。'),
('practical','/ˈpræktɪkl/','adj. 实际的','realistic','Practical experience.','实际经验。'),
('conventional','/kənˈvenʃənl/','adj. 传统的','traditional','Conventional methods.','传统方法。'),
('unconventional','/ˌʌnkənˈvenʃənl/','adj. 非常规的','not traditional','An unconventional approach.','非常规方法。'),
('rational','/ˈræʃənl/','adj. 理性的','logical','A rational decision.','理性决定。','rat(计算)+ional'),
('irrational','/ɪˈræʃənl/','adj. 不理性的','not logical','Irrational behavior.','不理性的行为。'),
('empirical','/ɪmˈpɪrɪkl/','adj. 经验主义的','experiential','Empirical knowledge.','经验知识。'),
('intuitive','/ɪnˈtjuːɪtɪv/','adj. 直觉的','instinctive','An intuitive interface.','直觉界面。'),
('analytical','/ˌænəˈlɪtɪkl/','adj. 分析的','examination-based','Analytical skills are valued.','分析技能受重视。'),
('critical','/ˈkrɪtɪkl/','adj. 批判的;关键的','very important','Critical thinking is essential.','批判性思维很重要。'),
('strategic','/strəˈtiːdʒɪk/','adj. 战略的','planned','Strategic planning.','战略规划。'),
('tactical','/ˈtæktɪkl/','adj. 战术的','practical actions','Tactical decision.','战术决定。'),
('logistical','/ləˈdʒɪstɪkl/','adj. 物流的','relating to logistics','Logistical challenges.','物流挑战。'),
('empirical','/ɪmˈpɪrɪkl/','adj. 实验的','tested','Empirical evidence is needed.','需要实验证据。'),
('pedagogical','/ˌpedəˈɡɒdʒɪkl/','adj. 教学的','about teaching','Pedagogical approach.','教学方法。'),
('ideological','/ˌaɪdiəˈlɒdʒɪkl/','adj. 意识形态的','relating to beliefs','Ideological differences.','意识形态差异。'),
('methodological','/ˌmeθədəˈlɒdʒɪkl/','adj. 方法论的','about methods','Methodological rigor.','方法论严谨。'),
('chronological','/ˌkrɒnəˈlɒdʒɪkl/','adj. 按时间的','in time order','Chronological order.','按时间顺序。','chron(时间)+ological'),
('psychological','/ˌsaɪkəˈlɒdʒɪkl/','adj. 心理的','mental','Psychological effects.','心理影响。'),
('physiological','/ˌfɪziəˈlɒdʒɪkl/','adj. 生理的','body functions','Physiological responses.','生理反应。'),
('anthropological','/ˌænθrəpəˈlɒdʒɪkl/','adj. 人类学的','study of humans','Anthropological research.','人类学研究。'),
('archaeological','/ˌɑːkiəˈlɒdʒɪkl/','adj. 考古学的','ancient study','Archaeological discoveries.','考古发现。'),
('ecological','/ˌiːkəˈlɒdʒɪkl/','adj. 生态的','relating to ecology','Ecological balance.','生态平衡。'),
('technological','/ˌteknəˈlɒdʒɪkl/','adj. 技术的','relating to tech','Technological advancement.','技术进步。'),
]
for w in d:
    cid += 1
    wr,ph,m,me,ex,et = w[0],w[1],w[2],w[3],w[4],w[5]
    r = w[6] if len(w) > 6 else ''
    rs = f', roots: "{r}"' if r else ''
    c += f'  {{ id: "w{cid:03d}", word: "{wr}", phonetic: "{ph}", meaning: "{m}", meaningEn: "{me}", example: "{ex}", exampleTranslation: "{et}"{rs}, level: "core" as const, tags: ["高频"] }},\n'
c += '];\n'
with open(VOCAB,'w',encoding='utf-8') as f:
    f.write(c)
print(f'Added {len(d)} words, total: {cid}')