import re
VOCAB = r'D:\Claude cli\MyApp\yingo\src\data\vocab-sample.ts'
with open(VOCAB,'r',encoding='utf-8') as f:
    c = f.read()
c = re.sub(r'];\s*$', '', c)
ids = re.findall(r'id:\s*"w(\d+)"', c)
cid = max(int(x) for x in ids) if ids else 0
print(f'Current: w{cid}')
d = [
('assertive','/əˈsɜːtɪv/','adj. 自信的','confident','Be assertive in negotiations.','谈判中要自信。'),
('amenable','/əˈmiːnəbl/','adj. 顺从的','willing to cooperate','Amenable to suggestions.','乐于接受建议。'),
('adamant','/ˈædəmənt/','adj. 坚定的','firmly decided','She was adamant.','她很坚定。'),
('indifferent','/ɪnˈdɪfərənt/','adj. 冷漠的','unconcerned','Indifferent to praise.','对表扬冷漠。'),
('complacent','/kəmˈpleɪsnt/','adj. 自满的','self-satisfied','Do not become complacent.','不要自满。'),
('contemptuous','/kənˈtemptʃuəs/','adj. 轻蔑的','showing contempt','A contemptuous look.','轻蔑的眼神。'),
('compassionate','/kəmˈpæʃənət/','adj. 有同情心的','showing sympathy','A compassionate doctor.','有同情心的医生。'),
('indignant','/ɪnˈdɪɡnənt/','adj. 愤慨的','angry at unfairness','Indignant at the accusation.','对指控感到愤慨。'),
('eloquent','/ˈeləkwənt/','adj. 雄辩的','fluent and persuasive','An eloquent speech.','雄辩的演讲。','e+loqu(说)+ent'),
('coherent','/kəʊˈhɪərənt/','adj. 有条理的','logically connected','A coherent plan.','有条理的计划。'),
('gregarious','/ɡrɪˈɡeəriəs/','adj. 爱交际的','sociable','A gregarious personality.','爱交际的性格。'),
('tenacious','/tɪˈneɪʃəs/','adj. 坚韧的','persistent','A tenacious negotiator.','坚韧的谈判者。'),
('notorious','/nəʊˈtɔːriəs/','adj. 臭名昭著的','famous for bad','A notorious criminal.','臭名昭著的罪犯。'),
('precarious','/prɪˈkeəriəs/','adj. 不稳定的','unstable','A precarious situation.','不稳定局势。'),
('audacious','/ɔːˈdeɪʃəs/','adj. 大胆的','bold','An audacious plan.','大胆计划。'),
('capricious','/kəˈprɪʃəs/','adj. 变化无常的','unpredictable','Capricious weather.','变化无常的天气。'),
('contentious','/kənˈtenʃəs/','adj. 有争议的','controversial','A contentious issue.','有争议的问题。'),
('facetious','/fəˈsiːʃəs/','adj. 滑稽的','joking inappropriate','A facetious remark.','滑稽的评论。'),
('atrocious','/əˈtrəʊʃəs/','adj. 糟糕的','terrible','Atrocious conditions.','糟糕的条件。'),
('ferocious','/fəˈrəʊʃəs/','adj. 凶猛的','fierce','A ferocious storm.','猛烈的风暴。'),
('voracious','/vəˈreɪʃəs/','adj. 贪婪的','very eager','A voracious reader.','贪婪的读者。'),
('sagacious','/səˈɡeɪʃəs/','adj. 睿智的','wise','A sagacious leader.','睿智的领袖。'),
('perspicacious','/ˌpɜːspɪˈkeɪʃəs/','adj. 敏锐的','perceptive','Perspicacious analysis.','敏锐的分析。'),
('pugnacious','/pʌɡˈneɪʃəs/','adj. 好斗的','combative','A pugnacious attitude.','好斗的态度。'),
('loquacious','/ləˈkweɪʃəs/','adj. 话多的','talkative','A loquacious host.','话多的主人。'),
('sequacious','/sɪˈkweɪʃəs/','adj. 盲从的','following blindly','Sequacious followers.','盲从的追随者'),
('vivacious','/vɪˈveɪʃəs/','adj. 活泼的','lively','A vivacious child.','活泼的孩子。'),
('tenacity','/tɪˈnæsəti/','n. 坚韧','determination','His tenacity is admirable.','他的坚韧令人钦佩。'),
('audacity','/ɔːˈdæsəti/','n. 大胆','boldness','The audacity of the plan.','计划的大胆。'),
('tenacity','/tɪˈnæsəti/','n. 坚持','persistence','Show tenacity in adversity.','逆境中展现坚持。'),
('sagacity','/səˈɡæsəti/','n. 睿智','wisdom','Leadership requires sagacity.','领导力需要睿智。'),
('tenacity','/tɪˈnæsəti/','n. 韧性','resilience','Mental tenacity is key.','心智韧性是关键。'),
('efficacy','/ˈefɪkəsi/','n. 功效','effectiveness','Drug efficacy is proven.','药物功效被证实。'),
('propensity','/prəˈpensəti/','n. 倾向','tendency','A propensity for risk.','冒险倾向。'),
('felicity','/fɪˈlɪsəti/','n. 幸福','great happiness','A life of felicity.','幸福的生活。'),
('paucity','/ˈpɔːsəti/','n. 少量','scarcity','A paucity of evidence.','证据不足。'),
('propensity','/prəˈpensəti/','n. 习性','natural inclination','A propensity to exaggerate.','夸张的习性。'),
('animosity','/ˌænɪˈmɒsəti/','n. 仇恨','strong hostility','Personal animosity.','个人仇恨。'),
('verbosity','/vɜːˈbɒsəti/','n. 冗长','wordiness','Reduce verbosity.','减少冗长。'),
('proclivity','/prəˈklɪvəti/','n. 癖好','inclination','A proclivity for detail.','对细节的癖好。'),
('disparity','/dɪˈspærəti/','n. 不平等','inequality','Income disparity.','收入差距。'),
('parity','/ˈpærəti/','n. 平等','equality','Gender parity.','性别平等。'),
('solidarity','/ˌsɒlɪˈdærəti/','n. 团结','unity','Show solidarity.','展现团结。'),
('familiarity','/fəˌmɪliˈærəti/','n. 熟悉','knowledge of','Familiarity with the topic.','熟悉话题。'),
('peculiarity','/pɪˌkjuːliˈærəti/','n. 特性','unusual feature','A cultural peculiarity.','文化特性。'),
('polarity','/pəˈlærəti/','n. 极性','opposite poles','Political polarity.','政治极性。'),
('clarity','/ˈklærəti/','n. 清晰','clearness','Clarity of thought.','思维清晰。'),
('prosperity','/prɒˈsperəti/','n. 繁荣','wealth','Economic prosperity.','经济繁荣。'),
('severity','/sɪˈverəti/','n. 严重性','harshness','Severity of the crisis.','危机的严重性。'),
('celebrity','/sɪˈlebrəti/','n. 名人','famous person','A Hollywood celebrity.','好莱坞名人。'),
('authority','/ɔːˈθɒrəti/','n. 权威','power or expert','An authority on the subject.','该主题的权威。'),
('priority','/praɪˈɒrəti/','n. 优先','top concern','Safety is a priority.','安全是优先事项。'),
('minority','/maɪˈnɒrəti/','n. 少数','small group','Ethnic minority.','少数民族。'),
('majority','/məˈdʒɒrəti/','n. 多数','larger group','The majority agrees.','多数人同意。'),
('ethnic','/ˈeθnɪk/','adj. 民族的','cultural group','Ethnic diversity.','民族多样性。'),
('indigenous','/ɪnˈdɪdʒɪnəs/','adj. 本土的','native','Indigenous peoples.','原住民。'),
('cosmopolitan','/ˌkɒzməˈpɒlɪtən/','adj. 国际化的','diverse','A cosmopolitan city.','国际化城市。'),
('patriarchal','/ˌpeɪtriˈɑːkl/','adj. 父权制的','male-dominated','Patriarchal society.','父权制社会。'),
('matriarchal','/ˌmeɪtriˈɑːkl/','adj. 母权制的','female-dominated','Matriarchal culture.','母权制文化。'),
('hierarchical','/ˌhaɪəˈrɑːkl/','adj. 等级制的','ranked','Hierarchical structure.','等级制结构。'),
('egalitarian','/ɪˌɡælɪˈteəriən/','adj. 平等主义的','believing in equality','Egalitarian society.','平等主义社会。'),
('coexistence','/ˌkəʊɪɡˈzɪstəns/','n. 共存','living together','Peaceful coexistence.','和平共处。'),
('assimilation','/əˌsɪmɪˈleɪʃn/','n. 同化','cultural absorption','Cultural assimilation.','文化同化。'),
('segregation','/ˌseɡrɪˈɡeɪʃn/','n. 隔离','separation','Racial segregation.','种族隔离。','se+greg(群)+ation'),
('integration','/ˌɪntɪˈɡreɪʃn/','n. 融合','combining','Social integration.','社会融合。'),
('cohesion','/kəʊˈhiːʒn/','n. 凝聚力','unity','Social cohesion.','社会凝聚力。'),
('stereotype','/ˈsteriətaɪp/','n. 刻板印象','fixed idea','Break stereotypes.','打破刻板印象。'),
('prejudice','/ˈpredʒʊdɪs/','n. 偏见','preconceived opinion','Overcome prejudice.','克服偏见。','pre+judice(判断)'),
('tolerance','/ˈtɒlərəns/','n. 容忍','acceptance','Cultural tolerance.','文化容忍。'),
('bigotry','/ˈbɪɡətri/','n. 偏执','intolerance','Fight bigotry.','反对偏执。'),
('xenophobia','/ˌzenəˈfəʊbiə/','n. 仇外','fear of foreigners','Xenophobia is harmful.','仇外是有害的。','xeno(外)+phobia(怕)'),
('nationalism','/ˈnæʃnəlɪzəm/','n. 民族主义','patriotic feeling','Rise of nationalism.','民族主义兴起。'),
('patriotism','/ˈpætriətɪzəm/','n. 爱国主义','love of country','Express patriotism.','表达爱国主义。'),
('sovereignty','/ˈsɒvrənti/','n. 主权','independence','National sovereignty.','国家主权。'),
('autonomy','/ɔːˈtɒnəmi/','n. 自治','self-governance','Regional autonomy.','区域自治。','auto(自己)+nomy(法则)'),
('democracy','/dɪˈmɒkrəsi/','n. 民主','people rule','Democratic election.','民主选举。','demo(人民)+cracy(统治)'),
('totalitarian','/təˌtælɪˈteəriən/','adj. 极权的','authoritarian','Totalitarian regime.','极权政权。'),
('anarchy','/ˈænəki/','n. 无政府状态','no government','Descent into anarchy.','陷入无政府状态。','an+archy(统治)'),
('oligarchy','/ˈɒlɪɡɑːki/','n. 寡头统治','rule by few','Corporate oligarchy.','企业寡头。'),
('bureaucracy','/bjʊˈrɒkrəsi/','n. 官僚','complex admin','Government bureaucracy.','政府官僚机构。'),
('lobbying','/ˈlɒbiɪŋ/','n. 游说','political influence','Corporate lobbying.','企业游说。'),
('advocacy','/ˈædvəkəsi/','n. 倡导','public support','Health advocacy.','健康倡导。'),
('referendum','/ˌrefəˈrendəm/','n. 公民投票','public vote','Hold a referendum.','举行公民投票。'),
('constituency','/kənˈstɪtʃuənsi/','n. 选区','voting district','Serve the constituency.','服务选区。'),
('coalition','/ˌkəʊəˈlɪʃn/','n. 联盟','alliance','Form a coalition.','组成联盟。'),
('diplomacy','/dɪˈpləʊməsi/','n. 外交','international relations','Skilled diplomacy.','熟练外交。'),
('treaty','/ˈtriːti/','n. 条约','formal agreement','Peace treaty.','和平条约。'),
('sanction','/ˈsæŋkʃn/','n. 制裁','penalty','Impose sanctions.','实施制裁。'),
('embargo','/ɪmˈbɑːɡəʊ/','n. 禁运','trade ban','Oil embargo.','石油禁运。'),
('ceasefire','/ˈsiːsfaɪə/','n. 停火','truce','Call for ceasefire.','呼吁停火。'),
('armistice','/ˈɑːmɪstɪs/','n. 停战协定','peace agreement','Sign an armistice.','签署停战协定。'),
('annexation','/ˌænekˈseɪʃn/','n. 吞并','territorial seizure','Annexation is illegal.','吞并是非法的。'),
('sovereignty','/ˈsɒvrənti/','n. 统治权','supreme power','Respect sovereignty.','尊重主权。'),
('espionage','/ˈespiənɑːʒ/','n. 间谍活动','spying','Corporate espionage.','企业间谍活动。'),
('propaganda','/ˌprɒpəˈɡændə/','n. 宣传','misleading info','Political propaganda.','政治宣传。'),
('censorship','/ˈsensəʃɪp/','n. 审查','content suppression','Press censorship.','新闻审查。'),
('dissident','/ˈdɪsɪdənt/','n. 异见者','opponent','Political dissident.','政治异见者。'),
('exile','/ˈeksaɪl/','n./v. 流放','banishment','Forced exile.','被迫流放。'),
('asylum','/əˈsaɪləm/','n. 庇护','protection','Seek asylum.','寻求庇护。'),
('refugee','/ˌrefjuˈdʒiː/','n. 难民','displaced person','Refugee camp.','难民营。'),
('emigrant','/ˈemɪɡrənt/','n. 移民','person leaving','Emigrant to Canada.','移民去加拿大。'),
('immigrant','/ˈɪmɪɡrənt/','n. 移民','person arriving','Immigrant workers.','移民工人。'),
('diaspora','/daɪˈæspərə/','n. 离散','scattered population','The global diaspora.','全球离散社群。'),
('assimilate','/əˈsɪmɪleɪt/','v. 同化','to absorb','Assimilate into culture.','融入文化。'),
('integrate','/ˈɪntɪɡreɪt/','v. 融入','to combine','Integrate into society.','融入社会。'),
('segregate','/ˈseɡrɪɡeɪt/','v. 隔离','to separate','Segregate waste.','垃圾分类。'),
('alienate','/ˈeɪliəneɪt/','v. 疏远','to estrange','Alienate allies.','疏远盟友。'),
('ostracize','/ˈɒstrəsaɪz/','v. 排斥','to exclude','Socially ostracized.','社会排斥。'),
('embrace','/ɪmˈbreɪs/','v. 拥抱;接受','to accept','Embrace diversity.','拥抱多样性。'),
]
for w in d:
    cid += 1
    wr,ph,m,me,ex,et = w[0],w[1],w[2],w[3],w[4],w[5]
    r = w[6] if len(w) > 6 else ''
    rs = f', roots: "{r}"' if r else ''
    c += f'  {{ id: "w{cid:03d}", word: "{wr}", phonetic: "{ph}", meaning: "{m}", meaningEn: "{me}", example: "{ex}", exampleTranslation: "{et}"{rs}, level: "core" as const, tags: ["高频"] }},\n'
c += '];\n'
with open(VOCAB,'w',encoding='utf-8') as f:
    f.write(c)
print(f'Added {len(d)} words, total: {cid}')