import re
VOCAB = r'D:\Claude cli\MyApp\yingo\src\data\vocab-sample.ts'
with open(VOCAB,'r',encoding='utf-8') as f:
    c = f.read()
c = re.sub(r'];\s*$', '', c)
ids = re.findall(r'id:\s*"w(\d+)"', c)
cid = max(int(x) for x in ids) if ids else 0
print(f'Current: w{cid}')
d = [
('pragmatic','/præɡˈmætɪk/','adj. 务实的','practical approach','A pragmatic solution works.','务实的方案有效。','pragm(实践)+atic'),
('skeptical','/ˈskeptɪkl/','adj. 怀疑的','doubtful','Scientists are skeptical.','科学家们持怀疑态度。'),
('ambiguous','/æmˈbɪɡjuəs/','adj. 模糊的','unclear meaning','The statement is ambiguous.','声明模棱两可。','ambi(两边)+guous'),
('explicit','/ɪkˈsplɪsɪt/','adj. 明确的','clearly stated','Give explicit instructions.','给出明确指示。','ex+plic(折叠)+it'),
('implicit','/ɪmˈplɪsɪt/','adj. 含蓄的','implied','An implicit understanding.','含蓄的理解。','im+plic(折叠)+it'),
('arbitrary','/ˈɑːbɪtrəri/','adj. 任意的','random choice','An arbitrary decision.','一个任意的决定。'),
('trivial','/ˈtrɪviəl/','adj. 琐碎的','of little importance','A trivial matter.','一件琐事。'),
('substantial','/səbˈstænʃl/','adj. 大量的','considerable','Substantial improvement.','显著改善。','sub+stant(站)+ial'),
('marginal','/ˈmɑːdʒɪnl/','adj. 边缘的','minor or slight','Marginal cost increase.','边际成本增加。','margin(边缘)+al'),
('integral','/ˈɪntɪɡrəl/','adj. 不可或缺的','essential','Teamwork is integral.','团队合作不可或缺。','integr(完整)+al'),
('paramount','/ˈpærəmaʊnt/','adj. 至高无上的','supreme','Safety is paramount.','安全至上。'),
('trivial','/ˈtrɪviəl/','adj. 微不足道的','insignificant','Do not ignore trivial details.','不要忽视微小细节。'),
('respective','/rɪˈspektɪv/','adj. 各自的','relating to each','In their respective fields.','在他们各自的领域。'),
('preliminary','/prɪˈlɪmɪnəri/','adj. 初步的','introductory','Preliminary results are promising.','初步结果有希望。','pre+limin(门槛)+ary'),
('tentative','/ˈtentətɪv/','adj. 暂定的','not final','A tentative plan.','暂定计划。','tent(尝试)+ative'),
('robust','/rəˈbʌst/','adj. 强健的','strong and healthy','A robust economy.','强健的经济。'),
('rigorous','/ˈrɪɡərəs/','adj. 严格的','extremely thorough','Rigorous testing is required.','需要严格测试。','rigor(严格)+ous'),
('stringent','/ˈstrɪndʒənt/','adj. 严格的','strict rules','Stringent regulations apply.','适用严格规定。'),
('lenient','/ˈliːniənt/','adj. 宽容的','not strict','Lenient punishment.','宽容的处罚。'),
('viable','/ˈvaɪəbl/','adj. 可行的','capable of working','A viable solution.','可行的解决方案。','vi(生命)+able'),
('feasible','/ˈfiːzəbl/','adj. 可行的','possible to do','Is the plan feasible?','计划可行吗？'),
('plausible','/ˈplɔːzəbl/','adj. 似乎可信的','seeming reasonable','A plausible explanation.','似乎合理的解释。'),
('conceivable','/kənˈsiːvəbl/','adj. 可想象的','imaginable','Every conceivable option.','每个可想象的选项。'),
('inevitable','/ɪnˈevɪtəbl/','adj. 不可避免的','unavoidable','Change is inevitable.','变革不可避免。','in+evit(避免)+able'),
('concurrent','/kənˈkʌrənt/','adj. 同时发生的','happening together','Concurrent events.','同时发生的事件。'),
('chronic','/ˈkrɒnɪk/','adj. 慢性的','long-lasting','Chronic pain persists.','慢性疼痛持续。','chron(时间)+ic'),
('acute','/əˈkjuːt/','adj. 急性的;敏锐的','sharp or severe','Acute shortage of supplies.','物资严重短缺。'),
('obsolete','/ˈɒbsəliːt/','adj. 过时的','no longer used','Technology becomes obsolete.','技术变得过时。'),
('innate','/ɪˈneɪt/','adj. 天生的','inborn quality','Innate ability.','天生的能力。'),
('prone','/prəʊn/','adj. 易于的','likely to','Prone to errors.','容易出错。'),
('immune','/ɪˈmjuːn/','adj. 免疫的','resistant','Immune to criticism.','对批评免疫。'),
('susceptible','/səˈseptəbl/','adj. 易受影响的','vulnerable','Susceptible to disease.','易患疾病。'),
('coherent','/kəʊˈhɪərənt/','adj. 连贯的','logical and clear','A coherent argument.','连贯的论点。'),
('comprehensive','/ˌkɒmprɪˈhensɪv/','adj. 全面的','thorough','A comprehensive review.','全面审查。'),
('concise','/kənˈsaɪs/','adj. 简洁的','brief and clear','A concise summary.','简洁的总结。'),
('elaborate','/ɪˈlæbərət/','adj. 详尽的','complex and detailed','An elaborate plan.','详尽的计划。','e+labor+ate'),
('redundant','/rɪˈdʌndənt/','adj. 冗余的','unnecessary','Remove redundant words.','删除冗余词语。'),
('conspicuous','/kənˈspɪkjuəs/','adj. 显眼的','easily noticed','A conspicuous error.','一个显眼的错误。'),
('inherent','/ɪnˈhɪərənt/','adj. 固有的','existing naturally','Inherent risk is present.','存在固有风险。'),
('intrinsic','/ɪnˈtrɪnsɪk/','adj. 内在的','belonging naturally','Intrinsic motivation matters.','内在动机很重要。'),
('extrinsic','/ɪkˈstrɪnsɪk/','adj. 外在的','coming from outside','Extrinsic factors influence.','外在因素影响。'),
('tangible','/ˈtændʒəbl/','adj. 有形的','able to touch','Tangible results.','有形的成果。'),
('intangible','/ɪnˈtændʒəbl/','adj. 无形的','not physical','Intangible cultural heritage.','无形文化遗产。'),
('quantifiable','/ˈkwɒntɪfaɪəbl/','adj. 可量化的','measurable','Quantifiable outcomes.','可量化的成果。'),
('peripheral','/pəˈrɪfərəl/','adj. 外围的','not central','Peripheral vision.','周边视觉。'),
('pivotal','/ˈpɪvətl/','adj. 关键的','of crucial importance','A pivotal moment.','关键时刻。'),
('radical','/ˈrædɪkl/','adj. 根本的;激进的','drastic','Radical changes needed.','需要根本性变革。','radic(根)+al'),
('superficial','/ˌsuːpəˈfɪʃl/','adj. 表面的','shallow','A superficial analysis.','表面分析。','super+fic(面)+ial'),
('profound','/prəˈfaʊnd/','adj. 深刻的','very deep','A profound insight.','深刻见解。','pro+found(底)'),
('mundane','/mʌnˈdeɪn/','adj. 平凡的','ordinary','Mundane daily tasks.','平凡的日常任务。'),
('exquisite','/ɪkˈskwɪzɪt/','adj. 精美的','beautifully made','Exquisite craftsmanship.','精美工艺。'),
('rigid','/ˈrɪdʒɪd/','adj. 僵硬的','inflexible','Rigid rules.','僵硬的规则。'),
('flexible','/ˈfleksəbl/','adj. 灵活的','adaptable','Flexible working hours.','灵活的工作时间。','flex(弯曲)+ible'),
('transparent','/trænsˈpærənt/','adj. 透明的','see-through; open','Transparent governance.','透明治理。'),
('opaque','/əʊˈpeɪk/','adj. 不透明的','not transparent','Opaque financial practices.','不透明的财务操作。'),
('authentic','/ɔːˈθentɪk/','adj. 真实的','genuine','An authentic experience.','真实体验。'),
('spurious','/ˈspjʊəriəs/','adj. 虚假的','false','Spurious claims.','虚假声明。'),
('compatible','/kəmˈpætəbl/','adj. 兼容的','able to work together','Compatible devices.','兼容设备。'),
('contradictory','/ˌkɒntrəˈdɪktəri/','adj. 矛盾的','conflicting','Contradictory evidence.','矛盾的证据。'),
('paradoxical','/ˌpærəˈdɒksɪkl/','adj. 悖论的','seemingly contradictory','A paradoxical situation.','悖论式情境。'),
('analogous','/əˈnæləɡəs/','adj. 类似的','comparable','An analogous case.','类似案例。'),
('disparate','/ˈdɪspərət/','adj. 迥然不同的','very different','Disparate views exist.','存在迥然不同的观点。'),
('homogeneous','/ˌhɒməˈdʒiːniəs/','adj. 同质的','uniform','A homogeneous mixture.','均匀混合物。'),
('heterogeneous','/ˌhetərəˈdʒiːniəs/','adj. 异质的','diverse','A heterogeneous population.','异质化人口。'),
('volatile','/ˈvɒlətaɪl/','adj. 不稳定的','unstable','Volatile market conditions.','不稳定市场状况。'),
('static','/ˈstætɪk/','adj. 静态的','unchanging','Static prices.','静态价格。'),
('dynamic','/daɪˈnæmɪk/','adj. 动态的','constantly changing','Dynamic environment.','动态环境。','dynam(力量)+ic'),
('progressive','/prəˈɡresɪv/','adj. 进步的','advancing','Progressive policies.','进步政策。'),
('conservative','/kənˈsɜːvətɪv/','adj. 保守的','traditional','Conservative approach.','保守方法。'),
('prudent','/ˈpruːdnt/','adj. 谨慎的','careful and wise','A prudent investment.','谨慎投资。'),
('reckless','/ˈrekləs/','adj. 鲁莽的','careless','Reckless driving is dangerous.','鲁莽驾驶很危险。'),
('diligent','/ˈdɪlɪdʒənt/','adj. 勤奋的','hardworking','A diligent student.','勤奋的学生。'),
('lethargic','/ləˈθɑːdʒɪk/','adj. 昏昏欲睡的','sluggish','Feeling lethargic after lunch.','午餐后昏昏欲睡。'),
('meticulous','/məˈtɪkjələs/','adj. 一丝不苟的','extremely careful','Meticulous attention to detail.','一丝不苟地关注细节。'),
('spontaneous','/spɒnˈteɪniəs/','adj. 自发的','unplanned','A spontaneous decision.','自发决定。'),
('deliberate','/dɪˈlɪbərət/','adj. 故意的','intentional','A deliberate choice.','故意的选择。','de+liber(衡量)+ate'),
('authentic','/ɔːˈθentɪk/','adj. 可信的','trustworthy','Authentic source.','可信来源。'),
('valid','/ˈvælɪd/','adj. 有效的','acceptable','A valid argument.','有效论点。'),
('obsolete','/ˈɒbsəliːt/','adj. 淘汰的','outdated','Obsolete technology.','淘汰技术。'),
('prompt','/prɒmpt/','adj. 迅速的','quick','Prompt response.','迅速回应。'),
('abrupt','/əˈbrʌpt/','adj. 突然的','sudden','An abrupt change.','突然变化。','ab+rupt(断)'),
('simultaneous','/ˌsɪmlˈteɪniəs/','adj. 同时的','at same time','Simultaneous events.','同时事件。'),
('subsequent','/ˈsʌbsɪkwənt/','adj. 随后的','coming after','Subsequent events confirmed it.','随后的事件证实了。'),
('preceding','/prɪˈsiːdɪŋ/','adj. 前面的','coming before','In the preceding chapter.','在前一章中。'),
('consecutive','/kənˈsekjʊtɪv/','adj. 连续的','following in order','Five consecutive wins.','五连胜。'),
('intermittent','/ˌɪntəˈmɪtənt/','adj. 间歇的','not continuous','Intermittent rain.','间歇性降雨。'),
('constant','/ˈkɒnstənt/','adj. 恒定的','unchanging','Constant temperature.','恒定温度。'),
('variable','/ˈveəriəbl/','adj. 可变的','able to change','Variable interest rates.','可变利率。'),
('equivalent','/ɪˈkwɪvələnt/','adj. 等价的','equal in value','Equivalent amount.','等价金额。','equi+val+ent'),
('compatible','/kəmˈpætəbl/','adj. 相容的','able to coexist','Compatible interests.','相容利益。'),
('prevalent','/ˈprevələnt/','adj. 流行的','widespread','A prevalent belief.','流行看法。','pre+val(力量)+ent'),
('negligible','/ˈneɡlɪdʒəbl/','adj. 可忽略的','insignificant','Negligible impact.','可忽略影响。'),
]
for w in d:
    cid += 1
    wr,ph,m,me,ex,et = w[0],w[1],w[2],w[3],w[4],w[5]
    r = w[6] if len(w) > 6 else ''
    rs = f', roots: "{r}"' if r else ''
    c += f'  {{ id: "w{cid:03d}", word: "{wr}", phonetic: "{ph}", meaning: "{m}", meaningEn: "{me}", example: "{ex}", exampleTranslation: "{et}"{rs}, level: "core" as const, tags: ["高频"] }},\n'
c += '];\n'
with open(VOCAB,'w',encoding='utf-8') as f:
    f.write(c)
print(f'Added {len(d)} words, total: {cid}')