import re
VOCAB = r'D:\Claude cli\MyApp\yingo\src\data\vocab-sample.ts'
with open(VOCAB,'r',encoding='utf-8') as f:
    c = f.read()
c = re.sub(r'];\s*$', '', c)
ids = re.findall(r'id:\s*"w(\d+)"', c)
cid = max(int(x) for x in ids) if ids else 0
print(f'Current: w{cid}')
d = [
('aftermath','/ˈɑːftəmæθ/','n. 后果','result','Aftermath of the storm.','风暴后果。',''),
('backlash','/ˈbæklæʃ/','n. 强烈反对','strong reaction','Public backlash against policy.','公众强烈反对政策。',''),
('breakthrough','/ˈbreɪkθruː/','n. 突破','major advance','Medical breakthrough.','医学突破。',''),
('catalyst','/ˈkætəlɪst/','n. 催化剂','trigger','Education is a catalyst.','教育是催化剂。',''),
('drawback','/ˈdrɔːbæk/','n. 缺点','disadvantage','The main drawback.','主要缺点。',''),
('fallout','/ˈfɔːlaʊt/','n. 后果','consequences','Political fallout.','政治后果。',''),
('groundwork','/ˈɡraʊndwɜːk/','n. 基础','preparation','Lay the groundwork.','打基础。',''),
('interplay','/ˈɪntəpleɪ/','n. 相互影响','interaction','Interplay of factors.','因素间相互影响。',''),
('landmark','/ˈlændmɑːk/','n. 里程碑','significant event','A landmark ruling.','里程碑裁决。',''),
('layout','/ˈleɪaʊt/','n. 布局','arrangement','The layout of the building.','建筑布局。',''),
('lifespan','/ˈlaɪfspæn/','n. 寿命','duration','Product lifespan.','产品寿命。',''),
('livelihood','/ˈlaɪvlihʊd/','n. 生计','means of support','Earn a livelihood.','谋生。',''),
('mainstream','/ˈmeɪnstriːm/','adj. 主流的','conventional','Mainstream culture.','主流文化。',''),
('milestone','/ˈmaɪlstəʊn/','n. 重要节点','key point','A major milestone.','重要节点。',''),
('offset','/ˈɒfset/','n. 抵消','compensation','Carbon offset.','碳补偿。',''),
('onset','/ˈɒnset/','n. 开始','beginning','Onset of winter.','冬季开始。',''),
('outbreak','/ˈaʊtbreɪk/','n. 爆发','sudden start','Disease outbreak.','疾病爆发。',''),
('outlet','/ˈaʊtlet/','n. 出口;销路','release or market','Retail outlet.','零售店。',''),
('outset','/ˈaʊtset/','n. 开端','start','From the outset.','从一开始。',''),
('precedent','/ˈpresɪdənt/','n. 先例','previous case','Set a precedent.','开创先例。',''),
('prospects','/ˈprɒspekts/','n. 前景','future chances','Career prospects.','职业前景。',''),
('rationale','/ˌræʃəˈnɑːl/','n. 理由','reasoning','The rationale is clear.','理由很清楚。',''),
('scope','/skəʊp/','n. 范围','range','Within the scope of study.','在研究范围内。',''),
('setback','/ˈsetbæk/','n. 挫折','reversal','A temporary setback.','暂时挫折。',''),
('stalemate','/ˈsteɪlmeɪt/','n. 僵局','deadlock','Political stalemate.','政治僵局。',''),
('stance','/stæns/','n. 立场','position','Take a firm stance.','采取坚定立场。',''),
('threshold','/ˈθreʃhəʊld/','n. 阈值','limit','Pain threshold.','疼痛阈值。',''),
('turnout','/ˈtɜːnaʊt/','n. 出席人数','attendance','Voter turnout was high.','投票率很高。',''),
('void','/vɔɪd/','n. 空白','empty space','Fill the void.','填补空白。',''),
('watershed','/ˈwɔːtəʃed/','n. 转折点','turning point','A watershed moment.','转折时刻。',''),
('counterpart','/ˈkaʊntəpɑːt/','n. 对应物','equivalent','His counterpart in the US.','他在美国的对应人。',''),
('downside','/ˈdaʊnsaɪd/','n. 不利面','disadvantage','The downside of tech.','技术的不利面。',''),
('upside','/ˈʌpsaɪd/','n. 好处','advantage','The upside is clear.','好处很明显。',''),
('background','/ˈbækɡraʊnd/','n. 背景','context','Cultural background.','文化背景。',''),
('underlie','/ˌʌndəˈlaɪ/','v. 构成基础','to be basis of','Factors underlie the issue.','因素构成问题基础。',''),
('undermine','/ˌʌndəˈmaɪn/','v. 暗中破坏','to weaken','Undermine confidence.','暗中破坏信心。',''),
('undergo','/ˌʌndəˈɡəʊ/','v. 经历','to experience','Undergo surgery.','经历手术。',''),
('undertake','/ˌʌndəˈteɪk/','v. 承担','to take on','Undertake a task.','承担任务。',''),
('oversee','/ˌəʊvəˈsiː/','v. 监督','to supervise','Oversee operations.','监督运营。',''),
('overlook','/ˌəʊvəˈlʊk/','v. 忽视','to miss','Overlook a detail.','忽视细节。',''),
('overtake','/ˌəʊvəˈteɪk/','v. 超越','to surpass','Overtake a competitor.','超越竞争对手。',''),
('overwhelm','/ˌəʊvəˈwelm/','v. 使不知所措','to overcome','Feel overwhelmed.','感到不知所措。',''),
('withstand','/wɪðˈstænd/','v. 经受住','to resist','Withstand pressure.','经受住压力。',''),
('withdraw','/wɪðˈdrɔː/','v. 撤回','to remove','Withdraw the offer.','撤回提议。',''),
('withhold','/wɪðˈhəʊld/','v. 扣留','to hold back','Withhold information.','扣留信息。',''),
('collaborate','/kəˈlæbəreɪt/','v. 合作','to work together','Collaborate on research.','合作研究。',''),
('coordinate','/kəʊˈɔːdɪneɪt/','v. 协调','to organize','Coordinate efforts.','协调努力。',''),
('subordinate','/səˈbɔːdɪnət/','adj. 下级的','lower rank','Subordinate staff.','下级员工。',''),
('corroborate','/kəˈrɒbəreɪt/','v. 证实','to confirm','Corroborate the evidence.','证实证据。',''),
('accelerate','/əkˈseləreɪt/','v. 加速','to speed up','Accelerate progress.','加速进步。','ac+celer(快)+ate'),
('decelerate','/diːˈseləreɪt/','v. 减速','to slow down','Decelerate growth.','减速增长。',''),
('regenerate','/riːˈdʒenəreɪt/','v. 再生','to regrow','Regenerate tissue.','再生组织。',''),
('degenerate','/dɪˈdʒenəreɪt/','v. 退化','to decline','Health degenerates.','健康退化。',''),
('operate','/ˈɒpəreɪt/','v. 运营','to function','Operate efficiently.','高效运营。',''),
('cooperate','/kəʊˈɒpəreɪt/','v. 合作','to work jointly','Cooperate with others.','与他人合作。',''),
('tolerate','/ˈtɒləreɪt/','v. 容忍','to endure','Cannot tolerate abuse.','不能容忍虐待。',''),
('precipitate','/prɪˈsɪpɪteɪt/','v. 促使','to cause','Precipitate a crisis.','促使危机。',''),
('reciprocate','/rɪˈsɪprəkeɪt/','v. 回报','to give in return','Reciprocate kindness.','回报善意。',''),
('navigate','/ˈnævɪɡeɪt/','v. 导航','to find way','Navigate the system.','操作系统。',''),
('designate','/ˈdezɪɡneɪt/','v. 指定','to appoint','Designate a leader.','指定领导。',''),
('discriminate','/dɪˈskrɪmɪneɪt/','v. 区分','to distinguish','Discright from wrong.','区分对错。',''),
('substantiate','/səbˈstænʃieɪt/','v. 证实','to prove','Substantiate claims.','证实声明。',''),
('authenticate','/ɔːˈθentɪkeɪt/','v. 验证','to verify','Authenticate the data.','验证数据。',''),
('reconcile','/ˈrekənsaɪl/','v. 调和','to settle','Reconcile differences.','调和分歧。',''),
('contemplate','/ˈkɒntəmpleɪt/','v. 考虑','to think about','Contemplate the options.','考虑选项。',''),
('consolidate','/kənˈsɒlɪdeɪt/','v. 合并','to combine','Consolidate resources.','合并资源。',''),
('dissipate','/ˈdɪsɪpeɪt/','v. 消散','to scatter','Fog dissipates.','雾气消散了。',''),
('culminate','/ˈkʌlmɪneɪt/','v. 达到顶点','to end in','Efforts culminate in success.','努力以成功告终。',''),
('nominate','/ˈnɒmɪneɪt/','v. 提名','to propose','Nominate a candidate.','提名候选人。',''),
('fascinate','/ˈfæsɪneɪt/','v. 使着迷','to attract strongly','The discovery fascinates.','这个发现令人着迷。',''),
('predominate','/prɪˈdɒmɪneɪt/','v. 占主导','to be dominant','Green predominate in nature.','绿色在自然界占主导。',''),
('subordinate','/səˈbɔːdɪneɪt/','v. 使从属','to rank below','Subordinate personal desires.','使个人欲望从属。',''),
('contaminate','/kənˈtæmɪneɪt/','v. 污染','to make impure','Contaminate the water.','污染水源。',''),
('dissiminate','/dɪˈsemɪneɪt/','v. 散布','to spread','Disseminate information.','散布信息。',''),
('discern','/dɪˈsɜːn/','v. 辨别','to detect','Discern the truth.','辨别真相。',''),
('ascertain','/ˌæsəˈteɪn/','v. 确定','to find out','Ascertain the cause.','确定原因。',''),
('discipline','/ˈdɪsɪplɪn/','v. 训练','to train','Discipline yourself.','训练自己。',''),
('deteriorate','/dɪˈtɪəriəreɪt/','v. 恶化','to worsen','Conditions deteriorate.','条件恶化。',''),
('fabricate','/ˈfæbrɪkeɪt/','v. 捏造;制造','to make up','Fabricate a story.','捏造故事。',''),
('speculate','/ˈspekjuleɪt/','v. 推测','to guess','Speculate about the future.','推测未来。',''),
('manipulate','/məˈnɪpjuleɪt/','v. 操控','to control','Manipulate the data.','操控数据。',''),
('circulate','/ˈsɜːkjuleɪt/','v. 传播','to spread','Information circulates.','信息传播。',''),
('postulate','/ˈpɒstjuleɪt/','v. 假定','to assume','Postulate a theory.','假定一个理论。',''),
('stimulate','/ˈstɪmjuleɪt/','v. 刺激','to encourage','Stimulate growth.','刺激增长。',''),
('accumulate','/əˈkjuːmjuleɪt/','v. 积累','to build up','Accumulate knowledge.','积累知识。','ac+cumul(堆)+ate'),
('formulate','/ˈfɔːmjuleɪt/','v. 制定','to create','Formulate a plan.','制定计划。',''),
('legislate','/ˈledʒɪsleɪt/','v. 立法','to make laws','Leglate for equality.','为平等立法。',''),
('speculate','/ˈspekjuleɪt/','v. 投机','to invest risky','Speculate on stocks.','投机股票。',''),
('regulate','/ˈreɡjuleɪt/','v. 管理','to control','Regulate the market.','管理市场。',''),
('manipulate','/məˈnɪpjuleɪt/','v. 操作','to handle','Manipulate machinery.','操作机械。',''),
('congratulate','/kənˈɡrætʃuleɪt/','v. 祝贺','to praise','Congratulate the winner.','祝贺获胜者。',''),
('calculate','/ˈkælkjuleɪt/','v. 计算','to compute','Calculate the cost.','计算成本。',''),
('circulate','/ˈsɜːkjuleɪt/','v. 循环','to move around','Blood circulates.','血液循环。',''),
('articulate','/ɑːˈtɪkjuleɪt/','v. 表达','to express','Articulate your ideas.','表达你的想法。',''),
('exonerate','/ɪɡˈzɒnəreɪt/','v. 免除','to clear of blame','Exonerate the accused.','免除被告罪责。',''),
('exasperate','/ɪɡˈzæspəreɪt/','v. 激怒','to annoy','Exasperate the opponent.','激怒对手。',''),
]
for w in d:
    cid += 1
    wr,ph,m,me,ex,et = w[0],w[1],w[2],w[3],w[4],w[5]
    r = w[6] if len(w) > 6 else ''
    rs = f', roots: "{r}"' if r else ''
    c += f'  {{ id: "w{cid:03d}", word: "{wr}", phonetic: "{ph}", meaning: "{m}", meaningEn: "{me}", example: "{ex}", exampleTranslation: "{et}"{rs}, level: "core" as const, tags: ["高频"] }},\n'
c += '];\n'
with open(VOCAB,'w',encoding='utf-8') as f:
    f.write(c)
print(f'Added {len(d)} words, total: {cid}')