const fs = require('fs');
const p = 'D:\\Claude cli\\MyApp\\yingo\\src\\data\\vocab-sample.ts';
let c = fs.readFileSync(p,'utf8').replace(/\];\s*$/,'');
const d = [
// I词族
['identical','/aɪˈdentɪkl/','adj. 相同的','exactly the same','Identical twins.','同卵双胞胎。','ident(相同)+ical'],
['identify','/aɪˈdentɪfaɪ/','v. 识别','to recognize','Identify the problem.','识别问题。','ident+ify'],
['ignore','/ɪɡˈnɔː/','v. 忽视','to pay no attention','Ignore warnings.','忽视警告。','ig+nore(知道)'],
['illustrate','/ˈɪləstreɪt/','v. 说明','to explain by examples','Illustrate the point.','说明观点。','il+lustr(光)+ate'],
['image','/ˈɪmɪdʒ/','n. 形象','a representation','Public image.','公众形象。'],
['immediate','/ɪˈmiːdiət/','adj. 立即的','happening at once','Immediate action.','立即行动。','im+medi(中间)+ate'],
['immense','/ɪˈmens/','adj. 巨大的','extremely large','Immense impact.','巨大影响。','im+mense(测量)'],
['immune','/ɪˈmjuːn/','adj. 免疫的','resistant to disease','Immune system.','免疫系统。','im+mune(公共)'],
['impact','/ˈɪmpækt/','n./v. 影响','a strong effect','Major impact.','重大影响。','im+pact(压)'],
['implement','/ˈɪmplɪment/','v. 实施','to put into effect','Implement the plan.','实施计划。','im+ple(填满)+ment'],
['implication','/ˌɪmplɪˈkeɪʃn/','n. 含义；影响','possible effect','Far-reaching implications.','深远影响。','im+plic(折叠)+ation'],
['implicit','/ɪmˈplɪsɪt/','adj. 隐含的','implied but not stated','Implicit assumption.','隐含假设。','im+plic(折叠)+it'],
['impose','/ɪmˈpəʊz/','v. 强加','to force upon','Impose restrictions.','强加限制。','im+pose(放置)'],
['impress','/ɪmˈpres/','v. 给...深刻印象','to make someone admire','Impressed by quality.','对质量印象深刻。','im+press(压)'],
['incentive','/ɪnˈsentɪv/','n. 激励','something that motivates','Financial incentive.','财务激励。','in+cent(唱)+ive'],
['incident','/ˈɪnsɪdənt/','n. 事件','a single occurrence','Serious incident.','严重事件。','in+cid(落)+ent'],
['incline','/ɪnˈklaɪn/','v. 倾向','to lean towards','Inclined to agree.','倾向于同意。','in+cline(倾斜)'],
['incredible','/ɪnˈkredəbl/','adj. 难以置信的','extremely good','Incredible achievement.','难以置信的成就。','in+cred(相信)+ible'],
['independent','/ˌɪndɪˈpendənt/','adj. 独立的','not depending on others','Independent country.','独立国家。','in+depend(悬挂)+ent'],
['index','/ˈɪndeks/','n. 索引；指数','a list or measure','Price index.','价格指数。'],
['indicate','/ˈɪndɪkeɪt/','v. 表明','to show or suggest','Data indicates growth.','数据表明增长。','in+dic(说)+ate'],
['individual','/ˌɪndɪˈvɪdʒuəl/','n./adj. 个人','a single person','Individual rights.','个人权利。','in+divid(分开)+ual'],
['inevitable','/ɪnˈevɪtəbl/','adj. 不可避免的','certain to happen','Inevitable change.','不可避免的变化。','in+evitable'],
['influence','/ˈɪnfluəns/','n./v. 影响','to have effect on','Major influence.','重大影响。','in+flu(流)+ence'],
['infrastructure','/ˈɪnfrəstrʌktʃə/','n. 基础设施','basic systems','Build infrastructure.','建设基础设施。','infra(下面)+structure'],
['initial','/ɪˈnɪʃl/','adj. 最初的','first or beginning','Initial stage.','初始阶段。','init(开始)+ial'],
['innovate','/ˈɪnəveɪt/','v. 创新','to introduce new methods','Must innovate to survive.','必须创新求生存。','in+nov(新)+ate'],
['insight','/ˈɪnsaɪt/','n. 洞察力','deep understanding','Gain insight.','获得洞察。','in+sight(看)'],
['inspect','/ɪnˈspekt/','v. 检查','to examine closely','Inspect the damage.','检查损坏。','in+spect(看)'],
['instance','/ˈɪnstəns/','n. 例子','an example','For instance.','例如。','in+stant(站)+e'],
['institute','/ˈɪnstɪtjuːt/','n./v. 机构；建立','an organization','Research institute.','研究所。','in+stitute(建立)'],
['instrument','/ˈɪnstrəmənt/','n. 工具','a device for measuring','Scientific instruments.','科学仪器。','in+stru(建造)+ment'],
['integrate','/ˈɪntɪɡreɪt/','v. 整合','to combine into whole','Integrate technology.','整合技术。','in+tegr(完整)+ate'],
['intellectual','/ˌɪntəˈlektʃuəl/','adj. 智力的','relating to thinking','Intellectual property.','知识产权。','intel(之间)+lect(选择)+ual'],
['intense','/ɪnˈtens/','adj. 强烈的','very great or strong','Intense heat.','酷热。','in+tens(伸)+e'],
['interact','/ˌɪntərˈækt/','v. 互动','to communicate with','Interact with others.','与他人互动。','inter(之间)+act'],
['interpret','/ɪnˈtɜːprɪt/','v. 解释','to explain meaning','Interpret data.','解释数据。','inter+pret(价值)'],
['interval','/ˈɪntəvl/','n. 间隔','a gap between things','Time interval.','时间间隔。','inter+val(强)'],
['intimate','/ˈɪntɪmət/','adj. 亲密的','very close relationship','Intimate friend.','亲密朋友。','in+tim(触摸)+ate'],
['investigate','/ɪnˈvestɪɡeɪt/','v. 调查','to examine thoroughly','Investigate the cause.','调查原因。','in+vestig(追踪)+ate'],
['involve','/ɪnˈvɒlv/','v. 涉及','to include as necessary','Involve all parties.','涉及所有方。','in+volve(转)'],
['isolate','/ˈaɪsəleɪt/','v. 隔离','to separate from others','Isolate the patient.','隔离病人。','isol(岛)+ate'],
// J-K词族
['justify','/ˈdʒʌstɪfaɪ/','v. 证明...正当','to show reason for','Justify the decision.','证明决定正当。','just(正义)+ify'],
['keen','/kiːn/','adj. 热衷的','eager or enthusiastic','Keen interest.','浓厚兴趣。'],
// L词族
['landscape','/ˈlændskeɪp/','n. 风景','a view of scenery','Natural landscape.','自然风景。','land(地)+scape(景)'],
['launch','/lɔːntʃ/','v./n. 发射','to start or set in motion','Launch product.','发布产品。'],
['layer','/ˈleɪə/','n. 层','a single thickness','Upper layer.','上层。'],
['league','/liːɡ/','n. 联盟','a group of teams','Football league.','足球联赛。'],
['legislation','/ˌledʒɪsˈleɪʃn/','n. 立法','laws collectively','New legislation.','新立法。','legis(法律)+lation'],
['legitimate','/lɪˈdʒɪtɪmət/','adj. 合法的','lawful','Legitimate concern.','正当担忧。','legitim(法律)+ate'],
['leisure','/ˈleʒə/','n. 闲暇','free time','Leisure activities.','休闲活动。'],
['liberal','/ˈlɪbərəl/','adj. 自由的','open to new ideas','Liberal views.','自由观点。','liber(自由)+al'],
['likewise','/ˈlaɪkwaɪz/','adv. 同样地','in the same way','Do likewise.','同样做。','like+wise'],
['limit','/ˈlɪmɪt/','n./v. 限制','a boundary','Set limits.','设定限制。'],
['link','/lɪŋk/','n./v. 联系','a connection','Strong link.','强联系。'],
['literature','/ˈlɪtrətʃə/','n. 文学；文献','written works','Scientific literature.','科学文献。','liter(文字)+ature'],
['locate','/ləʊˈkeɪt/','v. 位于','to find or place','Located in Shanghai.','位于上海。','loc(地方)+ate'],
['logic','/ˈlɒdʒɪk/','n. 逻辑','reasoning','Follow logic.','遵循逻辑。','log(说)+ic'],
['loyal','/ˈlɔɪəl/','adj. 忠诚的','faithful','Loyal supporter.','忠实支持者。','loy(法律)+al'],
// M词族
['magnificent','/mæɡˈnɪfɪsn/','adj. 壮丽的','extremely beautiful','Magnificent view.','壮丽景色。','magn(大)+fic+ent'],
['maintain','/meɪnˈteɪn/','v. 维持','to keep in good condition','Maintain order.','维持秩序。','main(手)+tain(持有)'],
['majority','/məˈdʒɒrɪti/','n. 多数','the larger number','Majority vote.','多数票。','major(大)+ity'],
['manage','/ˈmænɪdʒ/','v. 管理','to be in charge of','Manage resources.','管理资源。','man(手)+age'],
['manipulate','/məˈnɪpjuleɪt/','v. 操纵','to handle or control','Manipulate data.','操纵数据。','mani(手)+pul(填)+ate'],
['massive','/ˈmæsɪv/','adj. 巨大的','large and heavy','Massive investment.','巨额投资。','mass(大量)+ive'],
['mature','/məˈtjʊə/','adj. 成熟的','fully developed','Mature decision.','成熟决定。'],
['mechanism','/ˈmekənɪzəm/','n. 机制','a system of parts','Defense mechanism.','防御机制。','mechan(机器)+ism'],
['media','/ˈmiːdiə/','n. 媒体','means of communication','Social media.','社交媒体。','medi(中间)+a'],
['mental','/ˈmentl/','adj. 精神的','relating to the mind','Mental health.','心理健康。','ment(心灵)+al'],
['method','/ˈmeθəd/','n. 方法','a way of doing things','Research method.','研究方法。'],
['migrate','/maɪˈɡreɪt/','v. 迁移','to move from one place','Birds migrate south.','鸟向南迁徙。','migr(移动)+ate'],
['militant','/ˈmɪlɪtənt/','adj. 好战的','aggressive or forceful','Militant approach.','激进方法。','milit(士兵)+ant'],
['ministry','/ˈmɪnɪstri/','n. 部门','a government department','Ministry of Education.','教育部。','minist(服务)+ry'],
['moderate','/ˈmɒdərət/','adj. 适度的','average or reasonable','Moderate pace.','适度速度。','moder(适度)+ate'],
['modify','/ˈmɒdɪfaɪ/','v. 修改','to change slightly','Modify the plan.','修改计划。','mod(方式)+ify'],
['monitor','/ˈmɒnɪtə/','n./v. 监控','to observe and check','Monitor progress.','监控进度。','monit(警告)+or'],
['motivate','/ˈməʊtɪveɪt/','v. 激励','to give reason for doing','Motivate students.','激励学生。','mot(移动)+ivate'],
['mutual','/ˈmjuːtʃuəl/','adj. 相互的','shared between two','Mutual respect.','相互尊重。','mut(改变)+ual'],
// N词族
['narrow','/ˈnærəʊ/','adj./v. 狭窄的','limited in width','Narrow gap.','狭窄的差距。'],
['neglect','/nɪˈɡlekt/','v./n. 忽视','to fail to care for','Neglect duties.','忽视职责。','neg(不)+lect(选择)'],
['negotiate','/nɪˈɡəʊʃieɪt/','v. 谈判','to discuss to reach agreement','Negotiate a deal.','谈判交易。','neg+oti(暇)+ate'],
['neutral','/ˈnjuːtrəl/','adj. 中立的','not supporting either side','Neutral position.','中立立场。','neutr(两者都不)+al'],
['nevertheless','/ˌnevəðəˈles/','adv. 然而','in spite of that','Expensive; nevertheless worth it.','贵但值得。','never+the+less'],
['norm','/nɔːm/','n. 标准','a standard or pattern','Social norms.','社会规范。'],
['notion','/ˈnəʊʃn/','n. 概念','a belief or idea','Notion of freedom.','自由概念。','not(知道)+ion'],
['notwithstanding','/ˌnɒtwɪθˈstændɪŋ/','adv. 尽管','in spite of','Notwithstanding the rain.','尽管下雨。'],
['novel','/ˈnɒvl/','adj. 新颖的','new and original','Novel approach.','新方法。','nov(新)+el'],
['nuclear','/ˈnjuːkliə/','adj. 核能的','relating to atomic nucleus','Nuclear energy.','核能。','nucle(核)+ar'],
['numerous','/ˈnjuːmərəs/','adj. 许多的','great in number','Numerous studies.','大量研究。','numer(数字)+ous'],
];
let id = 224;
for (const w of d) {
  const [word,phonetic,meaning,meaningEn,example,exampleTranslation,roots,association] = w;
  const nid = 'w'+String(id).padStart(3,'0');
  c += `  { id: "${nid}", word: "${word}", phonetic: "${phonetic}", meaning: "${meaning}", meaningEn: "${meaningEn}", example: "${example}", exampleTranslation: "${exampleTranslation}"${roots ? `, roots: "${roots}"` : ''}${association ? `, association: "${association}"` : ''}, level: "core" as const, tags: ["高频"] },\n`;
  id++;
}
c += '];\n';
fs.writeFileSync(p,c,'utf8');
console.log('Added '+d.length+' words, total up to w'+String(id-1).padStart(3,'0'));
