const fs = require('fs');
const p = 'D:\\Claude cli\\MyApp\\yingo\\src\\data\\vocab-sample.ts';
let c = fs.readFileSync(p,'utf8').replace(/\];\s*$/,'');
const d = [
// S词族
['sacrifice','/ˈsækrɪfaɪs/','n./v. 牺牲','to give up for others','Sacrifice for future.','为未来牺牲。','sacr(神圣)+fice(做)'],
['sake','/seɪk/','n. 理由','for the purpose of','For safety\'s sake.','为了安全。'],
['sample','/ˈsɑːmpl/','n. 样本','a representative part','Random sample.','随机样本。'],
['scale','/skeɪl/','n. 规模','the size or extent','Large scale.','大规模。'],
['scandal','/ˈskændl/','n. 丑闻','a disgraceful event','Political scandal.','政治丑闻。'],
['scheme','/skiːm/','n. 计划','a plan or arrangement','Government scheme.','政府计划。'],
['scope','/skəʊp/','n. 范围','the extent of something','Limited scope.','范围有限。'],
['sector','/ˈsektə/','n. 部门','a distinct area','Private sector.','私营部门。','sect(切割)+or'],
['secure','/sɪˈkjʊə/','adj./v. 安全的','to make safe','Secure position.','安全位置。','se+cure(关心)'],
['seek','/siːk/','v. 寻找','to try to find','Seek knowledge.','寻求知识。'],
['segment','/ˈseɡmənt/','n. 部分','a distinct part','Market segment.','市场细分。','seg(切割)+ment'],
['sensible','/ˈsensəbl/','adj. 明智的','having good sense','Sensible decision.','明智决定。','sens(感觉)+ible'],
['significant','/sɪɡˈnɪfɪkənt/','adj. 重要的','sufficiently great','Significant impact.','重大影响。','sign+ific+ant'],
['similar','/ˈsɪmələ/','adj. 相似的','alike in appearance','Similar approach.','相似方法。','simil(相似)+ar'],
['simplify','/ˈsɪmplɪfaɪ/','v. 简化','to make simpler','Simplify process.','简化过程。','simpl(简单)+ify'],
['simulate','/ˈsɪmjuleɪt/','v. 模拟','to imitate','Simulate conditions.','模拟条件。','simul(相同)+ate'],
['site','/saɪt/','n. 地点','a location','Construction site.','建筑工地。'],
['skeptical','/ˈskeptɪkl/','adj. 怀疑的','not easily convinced','Skeptical about results.','对结果持怀疑态度。','scept(观察)+ical'],
['solution','/səˈluːʃn/','n. 解决方案','a way to solve problem','Find solution.','找到解决方案。','solu(松开)+tion'],
['somewhat','/ˈsʌmwɒt/','adv. 有点','to some extent','Somewhat difficult.','有点困难。','some+what'],
['sophisticated','/səˈfɪstɪkeɪtɪd/','adj. 复杂的','highly developed','Sophisticated technology.','复杂技术。','soph(智慧)+istic+ated'],
['source','/sɔːs/','n. 来源','where something comes from','Reliable source.','可靠来源。'],
['specific','/spəˈsɪfɪk/','adj. 具体的','clearly defined','Specific details.','具体细节。','spec(看)+ific'],
['sphere','/sfɪə/','n. 领域；球体','an area of activity','Political sphere.','政治领域。'],
['stable','/ˈsteɪbl/','adj. 稳定的','not likely to change','Stable economy.','稳定经济。','stab(站)+le'],
['standard','/ˈstændəd/','n./adj. 标准','a level of quality','High standard.','高标准。','stand+ard'],
['status','/ˈsteɪtəs/','n. 状态','current situation','Social status.','社会地位。'],
['stimulate','/ˈstɪmjuleɪt/','v. 刺激','to encourage activity','Stimulate growth.','刺激增长。','stimul(刺)+ate'],
['strategy','/ˈstrætədʒi/','n. 策略','a plan of action','Business strategy.','商业策略。','strat(层)+egy'],
['stress','/stres/','n./v. 压力','pressure or emphasis','Reduce stress.','减少压力。'],
['structure','/ˈstrʌktʃə/','n. 结构','the arrangement of parts','Social structure.','社会结构。','struct(建造)+ure'],
['subject','/ˈsʌbdʒɪkt/','n./adj. 主题','a topic of discussion','Main subject.','主要主题。','sub+ject(投)'],
['subsequent','/ˈsʌbsɪkwənt/','adj. 随后的','coming after','Subsequent events.','后续事件。','sub+sequ(跟随)+ent'],
['substance','/ˈsʌbstəns/','n. 物质','a material','Chemical substance.','化学物质。','sub+stance(站)'],
['substitute','/ˈsʌbstɪtjuːt/','n./v. 替代品','something used in place of another','Substitute teacher.','代课老师。','sub+stitute(建立)'],
['suburb','/ˈsʌbɜːb/','n. 郊区','outlying area of city','Live in suburbs.','住在郊区。','sub(下面)+urb(城市)'],
['sufficient','/səˈfɪʃnt/','adj. 足够的','enough for a purpose','Sufficient evidence.','充足证据。','suf+fic(做)+ient'],
['suggest','/səˈdʒest/','v. 建议','to put forward for consideration','Suggest improvement.','建议改进。','sug+gest(带)'],
['summary','/ˈsʌməri/','n. 摘要','a brief account','Executive summary.','执行摘要。','sum(最高)+mary'],
['summit','/ˈsʌmɪt/','n. 峰会；顶点','a meeting of leaders','International summit.','国际峰会。','sum(最高)+mit'],
['supply','/səˈplaɪ/','n./v. 供应','to provide','Supply and demand.','供需。','sup+ply(填满)'],
['supreme','/suːˈpriːm/','adj. 最高的','highest in rank','Supreme authority.','最高权威。','sup+reme(高)'],
['survey','/ˈsɜːveɪ/','n./v. 调查','a comprehensive study','Conduct survey.','进行调查。','sur+vey(看)'],
['survive','/səˈvaɪv/','v. 幸存','to continue to live','Survived the crisis.','从危机中幸存。','sur+vive(活)'],
['suspect','/səˈspekt/','v./n. 怀疑','to believe something is true','Suspect fraud.','怀疑欺诈。','sus+pect(看)'],
['suspend','/səˈspend/','v. 暂停','to temporarily stop','Suspend operation.','暂停运营。','sus+pend(挂)'],
['sustain','/səˈsteɪn/','v. 维持','to keep going','Sustain growth.','维持增长。','sus+tain(持有)'],
['symbol','/ˈsɪmbl/','n. 象征','a representative mark','National symbol.','国家象征。','sym(共同)+bol(投)'],
['sympathy','/ˈsɪmpəθi/','n. 同情','feelings of sorrow','Show sympathy.','表示同情。','sym(共同)+path(感觉)+y'],
['symptom','/ˈsɪmptəm/','n. 症状','a sign of illness','Early symptoms.','早期症状。','sym(共同)+ptom(落下)'],
['system','/ˈsɪstəm/','n. 系统','a set of parts working together','Operating system.','操作系统。','sys(站)+tem'],
// T词族
['tackle','/ˈtækl/','v. 处理','to deal with a problem','Tackle issues.','处理问题。'],
['target','/ˈtɑːɡɪt/','n./v. 目标','an intended result','Set target.','设定目标。'],
['technique','/tekˈniːk/','n. 技术','a way of doing something','New technique.','新技术。','techn(技术)+ique'],
['temporary','/ˈtemprəri/','adj. 临时的','lasting for a short time','Temporary solution.','临时方案。','tempor(时间)+ary'],
['tendency','/ˈtendənsi/','n. 趋势','a natural inclination','Growing tendency.','增长趋势。','tend(伸)+ency'],
['terminal','/ˈtɜːmɪnl/','n./adj. 终点','an end or conclusion','Airport terminal.','机场航站楼。','termin(界限)+al'],
['territory','/ˈterətəri/','n. 领土','an area of land','National territory.','国家领土。','terr(地)+itory'],
['theme','/θiːm/','n. 主题','a subject or topic','Main theme.','主要主题。'],
['theory','/ˈθɪəri/','n. 理论','a system of ideas','Scientific theory.','科学理论。','theo(神)+ry'],
['therapeutic','/ˌθerəˈpjuːtɪk/','adj. 治疗的','relating to healing','Therapeutic effect.','治疗效果。','therap(治疗)+eutic'],
['threshold','/ˈθreʃhəʊld/','n. 门槛','the point of entering','Below threshold.','低于门槛。'],
['thrive','/θraɪv/','v. 繁荣','to prosper and grow','Business thrives.','生意兴隆。'],
['trend','/trend/','n. 趋势','a general direction','Current trend.','当前趋势。'],
['trigger','/ˈtrɪɡə/','v./n. 触发','to cause to happen','Trigger response.','触发反应。'],
['triumph','/ˈtraɪʌmf/','n./v. 胜利','a great victory','Triumph over adversity.','战胜逆境。','tri(三)+umph'],
['typical','/ˈtɪpɪkl/','adj. 典型的','having usual features','Typical example.','典型例子。','typ(型)+ical'],
// U-V词族
['ultimate','/ˈʌltɪmət/','adj. 最终的','being the last or final','Ultimate goal.','最终目标。','ultim(最后)+ate'],
['undergo','/ˌʌndəˈɡəʊ/','v. 经历','to experience','Undergo change.','经历变化。','under+go(走)'],
['undertake','/ˌʌndəˈteɪk/','v. 承担','to take on responsibility','Undertake task.','承担任务。','under+take(拿)'],
['uniform','/ˈjuːnɪfɔːm/','adj./n. 统一的','the same throughout','Uniform standard.','统一标准。','uni(一)+form(形)'],
['unique','/juːˈniːk/','adj. 独特的','being the only one','Unique feature.','独特特征。','uni(一)+que'],
['universal','/ˌjuːnɪˈvɜːsl/','adj. 普遍的','relating to everyone','Universal access.','普遍访问。','uni+vers(转)+al'],
['urban','/ˈɜːbən/','adj. 城市的','relating to cities','Urban area.','城市地区。','urb(城市)+an'],
['urge','/ɜːdʒ/','v./n. 强烈要求','to strongly encourage','Urged action.','敦促行动。'],
['utilise','/ˈjuːtəlaɪz/','v. 利用','to make use of','Utilise resources.','利用资源。','util(使用)+ise'],
['valid','/ˈvælɪd/','adj. 有效的','having a sound basis','Valid argument.','有效论点。','val(价值)+id'],
['vary','/ˈveəri/','v. 变化','to differ or change','Prices vary.','价格变化。','var(变化)+y'],
['vast','/vɑːst/','adj. 广阔的','very large in extent','Vast majority.','绝大多数。'],
['vehicle','/ˈviːɪkl/','n. 车辆；媒介','a means of transport','Electric vehicle.','电动车。','veh(运载)+icle'],
['venture','/ˈventʃə/','n./v. 冒险','a risky business','Joint venture.','合资企业。','vent(来)+ure'],
['verbal','/ˈvɜːbl/','adj. 口头的','relating to words','Verbal communication.','口头交流。','verb(词语)+al'],
['verify','/ˈverɪfaɪ/','v. 核实','to make sure something is true','Verify information.','核实信息。','ver(真实)+ify'],
['version','/ˈvɜːʃn/','n. 版本','a form of something','Latest version.','最新版本。','vers(转)+ion'],
['vessel','/ˈvesl/','n. 容器；船','a ship or container','Blood vessel.','血管。'],
['viable','/ˈvaɪəbl/','adj. 可行的','able to work successfully','Viable option.','可行选项。','vi(活)+able'],
['violate','/ˈvaɪəleɪt/','v. 违反','to break a rule','Violate law.','违法。','viol(力量)+ate'],
['virtual','/ˈvɜːtʃuəl/','adj. 虚拟的','simulated by computer','Virtual reality.','虚拟现实。','virt(力量)+ual'],
['visible','/ˈvɪzəbl/','adj. 可见的','able to be seen','Visible results.','可见结果。','vis(看)+ible'],
['vital','/ˈvaɪtl/','adj. 至关重要的','absolutely necessary','Vital importance.','至关重要。','vit(生命)+al'],
['vivid','/ˈvɪvɪd/','adj. 生动的','producing strong mental image','Vivid description.','生动描述。','viv(活)+id'],
['volume','/ˈvɒljuːm/','n. 体积；音量','the amount of space','Volume of trade.','贸易量。','volu(转)+me'],
['voluntary','/ˈvɒləntri/','adj. 自愿的','done by choice','Voluntary action.','自愿行动。','volunt(意志)+ary'],
['vote','/vəʊt/','n./v. 投票','to express a choice','Cast vote.','投票。'],
['vulnerable','/ˈvʌlnərəbl/','adj. 脆弱的','susceptible to harm','Vulnerable groups.','弱势群体。','vulner(伤害)+able'],
// W-Z词族
['wage','/weɪdʒ/','n. 工资','money earned for work','Minimum wage.','最低工资。'],
['welfare','/ˈwelfeə/','n. 福利','well-being and happiness','Social welfare.','社会福利。','welf(好)+fare(走)'],
['whereas','/weərˈæz/','conj. 然而','in contrast to','Rich whereas poor.','富与穷的对比。'],
['widespread','/ˈwaɪdspred/','adj. 广泛的','found over large area','Widespread use.','广泛使用。','wide+spread(传播)'],
['witness','/ˈwɪtnəs/','n./v. 目击者','to see happen','Witnessed change.','见证变化。'],
['yield','/jiːld/','v./n. 产量','to produce or give way','High yield.','高产量。'],
['zone','/zəʊn/','n. 地区','an area with particular features','Free trade zone.','自由贸易区。'],
];
let id = 428;
for (const w of d) {
  const [word,phonetic,meaning,meaningEn,example,exampleTranslation,roots,association] = w;
  const nid = 'w'+String(id).padStart(3,'0');
  c += `  { id: "${nid}", word: "${word}", phonetic: "${phonetic}", meaning: "${meaning}", meaningEn: "${meaningEn}", example: "${example}", exampleTranslation: "${exampleTranslation}"${roots ? `, roots: "${roots}"` : ''}${association ? `, association: "${association}"` : ''}, level: "core" as const, tags: ["高频"] },\n`;
  id++;
}
c += '];\n';
fs.writeFileSync(p,c,'utf8');
console.log('Added '+d.length+' words, total up to w'+String(id-1).padStart(3,'0'));
