import re
VOCAB = r'D:\Claude cli\MyApp\yingo\src\data\vocab-sample.ts'
with open(VOCAB,'r',encoding='utf-8') as f:
    c = f.read()
c = re.sub(r'];\s*$', '', c)
ids = re.findall(r'id:\s*"w(\d+)"', c)
cid = max(int(x) for x in ids) if ids else 0
print(f'Current: w{cid}')
d = [
('discourse','/ˈdɪskɔːs/','n. 话语','formal discussion','Academic discourse is valued.','学术话语受重视。','dis+course'),
('rhetoric','/ˈretərɪk/','n. 修辞','art of persuasion','Political rhetoric is common.','政治修辞很常见。'),
('lexicon','/ˈleksɪkən/','n. 词汇表','word collection','Expand your lexicon.','扩展你的词汇表。'),
('syntax','/ˈsɪntæks/','n. 句法','sentence structure','English syntax differs from Chinese.','英语句法不同于中文。','syn+tax(排列)'),
('semantics','/sɪˈmæntɪks/','n. 语义学','study of meaning','Semantics is complex.','语义学很复杂。'),
('phonetics','/fəˈnetɪks/','n. 语音学','study of sounds','English phonetics is tricky.','英语语音学很难。'),
('morphology','/mɔːˈfɒlədʒi/','n. 形态学','study of word forms','Morphology studies word formation.','形态学研究构词。','morph(形态)+ology'),
('pragmatics','/præɡˈmætɪks/','n. 语用学','language in context','Pragmatics is about context.','语用学是关于语境的。'),
('bilingual','/ˌbaɪˈlɪŋɡwəl/','adj. 双语的','speaking two languages','Bilingual education benefits children.','双语教育有益儿童。','bi+lingu(语言)+al'),
('multilingual','/ˌmʌltɪˈlɪŋɡwəl/','adj. 多语的','many languages','A multilingual society.','多语社会。'),
('vernacular','/vəˈnækjələ/','n. 本地话','local language','Speak in the vernacular.','说本地话。'),
('jargon','/ˈdʒɑːɡən/','n. 行业术语','specialized language','Technical jargon is confusing.','技术术语让人困惑。'),
('colloquial','/kəˈləʊkwiəl/','adj. 口语的','informal speech','Colloquial expressions.','口语表达。','col+loqu(说)+ial'),
('articulate','/ɑːˈtɪkjulət/','adj. 善于表达的','clearly expressed','An articulate speaker.','善于表达的演讲者。'),
('inaudible','/ɪnˈɔːdəbl/','adj. 听不见的','not audible','The sound was inaudible.','声音听不见。'),
('illegible','/ɪˈledʒəbl/','adj. 难以辨认的','not readable','The handwriting is illegible.','字迹难以辨认。'),
('incomprehensible','/ɪnˌkɒmprɪˈhensəbl/','adj. 难以理解的','not understandable','The jargon is incomprehensible.','术语难以理解。'),
('unprecedented','/ʌnˈpresɪdentɪd/','adj. 史无前例的','never before','An unprecedented event.','史无前例的事件。'),
('unanimous','/juːˈnænɪməs/','adj. 一致同意的','in complete agreement','A unanimous decision.','一致同意的决定。','un+anim(精神)+ous'),
('autonomous','/ɔːˈtɒnəməs/','adj. 自治的','self-governing','An autonomous region.','自治区。'),
('anonymous','/əˈnɒnɪməs/','adj. 匿名的','unnamed','An anonymous donor.','匿名捐赠者。','an+onym(名字)+ous'),
('synonymous','/sɪˈnɒnɪməs/','adj. 同义的','meaning the same','Wealth is not synonymous with happiness.','财富不等于幸福。'),
('simultaneous','/ˌsɪmlˈteɪniəs/','adj. 同步的','at the same time','Simultaneous translation.','同声翻译。'),
('spontaneous','/spɒnˈteɪniəs/','adj. 自然发生的','unplanned','A spontaneous reaction.','自发反应。'),
('miscellaneous','/ˌmɪsəˈleɪniəs/','adj. 各种各样的','mixed','Miscellaneous items.','各种物品。'),
('heterogeneous','/ˌhetərəˈdʒiːniəs/','adj. 多样的','diverse','A heterogeneous group.','多样化群体。'),
('homogeneous','/ˌhɒməˈdʒiːniəs/','adj. 同质的','uniform','A homogeneous mixture.','均匀混合物。'),
('extraneous','/ɪkˈstreɪniəs/','adj. 无关的','irrelevant','Remove extraneous details.','删除无关细节。'),
('erroneous','/ɪˈrəʊniəs/','adj. 错误的','incorrect','An erroneous assumption.','错误假设。'),
('courteous','/ˈkɜːtiəs/','adj. 有礼貌的','polite','Be courteous to others.','对他人有礼貌。'),
('righteous','/ˈraɪtʃəs/','adj. 正义的','morally right','A righteous cause.','正义事业。'),
('righteousness','/ˈraɪtʃəsnəs/','n. 正义','moral virtue','Fight for righteousness.','为正义而战。'),
('hospitality','/ˌhɒspɪˈtæləti/','n. 好客','welcoming guests','Southern hospitality.','南方的好客。'),
('integrity','/ɪnˈteɡrəti/','n. 正直','moral uprightness','Personal integrity.','个人正直。'),
('dignity','/ˈdɪɡnəti/','n. 尊严','self-respect','Human dignity is sacred.','人的尊严神圣不可侵犯。'),
('humility','/hjuːˈmɪləti/','n. 谦逊','modesty','Show humility.','展现谦逊。'),
('credibility','/ˌkredəˈbɪləti/','n. 可信度','trustworthiness','Maintain credibility.','保持可信度。'),
('legitimacy','/lɪˈdʒɪtɪməsi/','n. 合法性','lawfulness','Question the legitimacy.','质疑合法性。'),
('confidentiality','/ˌkɒnfɪˌdenʃiˈæləti/','n. 保密性','secrecy','Maintain confidentiality.','保持保密性。'),
('accountability','/əˌkaʊntəˈbɪləti/','n. 问责制','responsibility','Government accountability.','政府问责制。'),
('sustainability','/səˌsteɪnəˈbɪləti/','n. 可持续性','environmental balance','Environmental sustainability.','环境可持续性。'),
('vulnerability','/ˌvʌlnərəˈbɪləti/','n. 脆弱性','weakness','System vulnerability.','系统脆弱性。'),
('accessibility','/əkˌsesəˈbɪləti/','n. 可及性','ease of access','Improve accessibility.','提高可及性。'),
('feasibility','/ˌfiːzəˈbɪləti/','n. 可行性','practicality','Feasibility study.','可行性研究。'),
('liability','/ˌlaɪəˈbɪləti/','n. 责任','legal responsibility','Limited liability.','有限责任。'),
('compatibility','/kəmˌpætəˈbɪləti/','n. 兼容性','ability to work together','Device compatibility.','设备兼容性。'),
('affordability','/əˌfɔːdəˈbɪləti/','n. 可负担性','cost-effectiveness','Housing affordability.','住房可负担性。'),
('durability','/ˌdjʊərəˈbɪləti/','n. 耐用性','longevity','Product durability.','产品耐用性。'),
('reliability','/rɪˌlaɪəˈbɪləti/','n. 可靠性','dependability','System reliability.','系统可靠性。'),
('adaptability','/əˌdæptəˈbɪləti/','n. 适应性','flexibility','Human adaptability.','人类适应性。'),
('accountability','/əˌkaʊntəˈbɪləti/','n. 负责','answerability','Personal accountability.','个人负责。'),
('inevitability','/ɪnˌevɪtəˈbɪləti/','n. 必然性','certainty','The inevitability of change.','变革的必然性。'),
('irreversibility','/ˌɪrɪˌvɜːsəˈbɪləti/','n. 不可逆性','cannot undo','Irreversibility of damage.','损害的不可逆性。'),
('interdependence','/ˌɪntədɪˈpendəns/','n. 相互依赖','mutual reliance','Global interdependence.','全球相互依赖。'),
('coexistence','/ˌkəʊɪɡˈzɪstəns/','n. 共存','living together','Peaceful coexistence.','和平共处。'),
('interconnectivity','/ˌɪntəkənekˈtɪvəti/','n. 互联互通','linked together','Digital interconnectivity.','数字互联互通。'),
('interplay','/ˈɪntəpleɪ/','n. 相互作用','interaction','The interplay of factors.','因素间的相互作用。'),
('synergy','/ˈsɪnədʒi/','n. 协同效应','combined effect','Team synergy.','团队协同效应。'),
('dichotomy','/daɪˈkɒtəmi/','n. 二分法','division into two','A false dichotomy.','假二分法。','dicho(二)+tom(切)'),
('paradigm','/ˈpærədaɪm/','n. 范式','model','A paradigm shift.','范式转变。'),
('dilemma','/dɪˈlemə/','n. 困境','difficult choice','A moral dilemma.','道德困境。'),
('predicament','/prɪˈdɪkəmənt/','n. 窘境','difficult situation','A financial predicament.','财务窘境。'),
('quandary','/ˈkwɒndəri/','n. 困惑','state of uncertainty','In a quandary.','困惑中。'),
('catalyst','/ˈkætəlɪst/','n. 催化剂','trigger for change','Education is a catalyst.','教育是催化剂。'),
('impetus','/ˈɪmpɪtəs/','n. 推动力','driving force','The impetus for reform.','改革的推动力。'),
('cornerstone','/ˈkɔːnəstəʊn/','n. 基石','foundation','Trust is the cornerstone.','信任是基石。'),
('linchpin','/ˈlɪntʃpɪn/','n. 关键','essential element','The linchpin of the plan.','计划的关键。'),
('catalyst','/ˈkætəlɪst/','n. 促进因素','something causing change','Technology as a catalyst.','技术作为促进因素。'),
('watershed','/ˈwɔːtəʃed/','n. 分水岭','turning point','A watershed moment.','分水岭时刻。'),
('landmark','/ˈlændmɑːk/','n. 里程碑','significant event','A landmark decision.','里程碑式决定。'),
('benchmark','/ˈbentʃmɑːk/','n. 标杆','standard','Industry benchmark.','行业标杆。'),
('hallmark','/ˈhɔːlmɑːk/','n. 特征','distinguishing quality','A hallmark of excellence.','卓越的标志。'),
('milestone','/ˈmaɪlstəʊn/','n. 里程碑','key achievement','A major milestone.','一个重要里程碑。'),
('criterion','/kraɪˈtɪəriən/','n. 准则','standard','Admission criteria.','录取准则。'),
('parameter','/pəˈræmɪtə/','n. 参数','limiting factor','Within these parameters.','在这些参数范围内。'),
('constraint','/kənˈstreɪnt/','n. 约束','limitation','Budget constraints.','预算约束。'),
('prerequisite','/priːˈrekwɪzɪt/','n. 前提','required condition','A basic prerequisite.','基本前提。'),
('stipulation','/ˌstɪpjuˈleɪʃn/','n. 条款','condition','Legal stipulations.','法律条款。'),
('provision','/prəˈvɪʒn/','n. 条款','clause','Contract provisions.','合同条款。'),
('amendment','/əˈmendmənt/','n. 修正案','change','Constitutional amendment.','宪法修正案。'),
('statute','/ˈstætʃuːt/','n. 法令','written law','Federal statute.','联邦法令。'),
('ordinance','/ˈɔːdɪnəns/','n. 条例','local law','City ordinance.','城市条例。'),
('mandate','/ˈmændeɪt/','n. 授权','official order','Government mandate.','政府授权。'),
('injunction','/ɪnˈdʒʌŋkʃn/','n. 禁令','court order','Obtain an injunction.','获得禁令。'),
('verdict','/ˈvɜːdɪkt/','n. 判决','court decision','Deliver a verdict.','宣布判决。'),
('testimony','/ˈtestɪməni/','n. 证言','sworn evidence','Expert testimony.','专家证言。'),
('affidavit','/ˌæfɪˈdeɪvɪt/','n. 宣誓书','sworn statement','Sign an affidavit.','签署宣誓书。'),
('deposition','/ˌdepəˈzɪʃn/','n. 证词','testimony taken under oath','Take a deposition.','取证词。'),
('indictment','/ɪnˈdaɪtmənt/','n. 起诉书','formal charge','Issue an indictment.','发出起诉书。'),
('acquittal','/əˈkwɪtl/','n. 无罪释放','not guilty verdict','Complete acquittal.','完全无罪释放。'),
('conviction','/kənˈvɪkʃn/','n. 定罪','guilty verdict','Criminal conviction.','刑事定罪。'),
('parole','/pəˈrəʊl/','n. 假释','early release','Released on parole.','假释出狱。'),
('probation','/prəˈbeɪʃn/','n. 缓刑','supervised release','On probation.','缓刑中。'),
('litigation','/ˌlɪtɪˈɡeɪʃn/','n. 诉讼','lawsuit','Civil litigation.','民事诉讼。'),
('arbitration','/ˌɑːbɪˈtreɪʃn/','n. 仲裁','dispute resolution','Binding arbitration.','有约束力的仲裁。'),
('mediation','/ˌmiːdiˈeɪʃn/','n. 调解','negotiation help','Family mediation.','家庭调解。'),
('reconciliation','/ˌrekənsɪliˈeɪʃn/','n. 和解','restoration of relations','National reconciliation.','全国和解。'),
('restoration','/ˌrestəˈreɪʃn/','n. 恢复','bringing back','Economic restoration.','经济恢复。'),
('restitution','/ˌrestɪˈtjuːʃn/','n. 赔偿','compensation','Make restitution.','赔偿。'),
('reparation','/ˌrepəˈreɪʃn/','n. 补偿','payment for damage','War reparations.','战争赔款。'),
('amnesty','/ˈæmnəsti/','n. 大赦','pardon','Grant amnesty.','给予大赦。'),
('pardon','/ˈpɑːdn/','n./v. 赦免','forgiveness','Presidential pardon.','总统赦免。'),
]
for w in d:
    cid += 1
    wr,ph,m,me,ex,et = w[0],w[1],w[2],w[3],w[4],w[5]
    r = w[6] if len(w) > 6 else ''
    rs = f', roots: "{r}"' if r else ''
    c += f'  {{ id: "w{cid:03d}", word: "{wr}", phonetic: "{ph}", meaning: "{m}", meaningEn: "{me}", example: "{ex}", exampleTranslation: "{et}"{rs}, level: "core" as const, tags: ["高频"] }},\n'
c += '];\n'
with open(VOCAB,'w',encoding='utf-8') as f:
    f.write(c)
print(f'Added {len(d)} words, total: {cid}')