import re
VOCAB = r'D:\Claude cli\MyApp\yingo\src\data\vocab-sample.ts'
with open(VOCAB,'r',encoding='utf-8') as f:
    c = f.read()
c = re.sub(r'];\s*$', '', c)
ids = re.findall(r'id:\s*"w(\d+)"', c)
cid = max(int(x) for x in ids) if ids else 0
print(f'Current: w{cid}')
d = [
('itinerary','/aɪˈtɪnərəri/','n. 行程','travel plan','Follow the itinerary.','按照行程走。','itiner(旅行)+ary'),
('excursion','/ɪkˈskɜːʃn/','n. 远足','short trip','Day excursion to the island.','去岛上游览一天。','ex+curs(跑)+ion'),
('expedition','/ˌekspɪˈdɪʃn/','n. 远征','long journey','Arctic expedition was dangerous.','北极远征很危险。','ex+ped(脚)+ition'),
('pilgrimage','/ˈpɪlɡrɪmɪdʒ/','n. 朝圣之旅','spiritual journey','A pilgrimage to Mecca.','去麦加朝圣。'),
('cruise','/kruːz/','n. 邮轮旅行','sea voyage','Mediterranean cruise.','地中海邮轮旅行。'),
('commute','/kəˈmjuːt/','v. 通勤','travel to work','She commutes by train.','她乘火车通勤。','com+mut(改变)+e'),
('embark','/ɪmˈbɑːk/','v. 登船;开始','to board or begin','Embark on a new journey.','开始新旅程。','em+bark(船)'),
('disembark','/ˌdɪsɪmˈbɑːk/','v. 下船','to leave a ship','Passengers disembarked.','乘客下船了。'),
('layover','/ˈleɪəʊvə/','n. 中途停留','brief stop','Six-hour layover in Dubai.','在迪拜停留六小时。'),
('accommodation','/əˌkɒməˈdeɪʃn/','n. 住宿','place to stay','Book accommodation early.','提前预订住宿。'),
('reservation','/ˌrezəˈveɪʃn/','n. 预订','booking','Make a reservation.','预订。'),
('boarding','/ˈbɔːdɪŋ/','n. 登机','getting on plane','Boarding begins at gate 5.','5号登机口开始登机。'),
('customs','/ˈkʌstəmz/','n. 海关','border control','Go through customs.','通过海关。'),
('luggage','/ˈlʌɡɪdʒ/','n. 行李','bags and suitcases','Check your luggage.','托运行李。'),
('souvenir','/ˌsuːvəˈnɪə/','n. 纪念品','travel keepsake','Buy souvenirs for friends.','给朋友买纪念品。'),
('destination','/ˌdestɪˈneɪʃn/','n. 目的地','place of arrival','Popular tourist destination.','热门旅游目的地。','de+stin(站)+ation'),
('terrain','/təˈreɪn/','n. 地形','land surface','Mountainous terrain is challenging.','山区地形很有挑战性。'),
('landscape','/ˈlændskeɪp/','n. 风景','scenery','Beautiful landscape.','美丽的风景。','land+scape(看)'),
('scenic','/ˈsiːnɪk/','adj. 风景优美的','having nice views','Scenic route through mountains.','穿越山脉的风景路线。'),
('boutique','/buːˈtiːk/','n. 精品店','small shop','Boutique hotel experience.','精品酒店体验。'),
('hostel','/ˈhɒstl/','n. 青年旅舍','budget accommodation','Youth hostel is affordable.','青年旅舍价格实惠。'),
('motel','/məʊˈtel/','n. 汽车旅馆','roadside hotel','Stay at a motel.','住汽车旅馆。'),
('vacancy','/ˈveɪkənsi/','n. 空房','available room','No vacancy sign.','客满标志。','vac(空)+ancy'),
('pedestrian','/pəˈdestriən/','n. 行人','person walking','Pedestrian crossing ahead.','前方行人过街。','ped(脚)+estrian'),
('congestion','/kənˈdʒestʃən/','n. 拥堵','traffic jam','Traffic congestion in rush hour.','高峰时段交通拥堵。'),
('detour','/ˈdiːtʊə/','n. 绕行','alternate route','Take a detour due to construction.','因施工绕行。'),
('intersection','/ˌɪntəˈsekʃn/','n. 十字路口','road crossing','Turn left at the intersection.','在十字路口左转。'),
('highway','/ˈhaɪweɪ/','n. 公路','major road','Highway traffic is heavy.','公路交通繁忙。'),
('boulevard','/ˈbuːləvɑːd/','n. 林荫大道','wide street','Tree-lined boulevard.','林荫大道。'),
('lane','/leɪn/','n. 车道;小路','narrow road','Stay in your lane.','保持在你的车道。'),
('marathon','/ˈmærəθən/','n. 马拉松','long-distance race','Run a marathon.','跑马拉松。'),
('tournament','/ˈtʊənəmənt/','n. 锦标赛','competition event','Tennis tournament.','网球锦标赛。'),
('championship','/ˈtʃæmpiənʃɪp/','n. 冠军赛','title competition','World championship.','世界锦标赛。'),
('athletics','/æθˈletɪks/','n. 田径运动','track and field','Athletics competition.','田径比赛。'),
('gymnastics','/dʒɪmˈnæstɪks/','n. 体操','acrobatic exercise','Artistic gymnastics.','艺术体操。'),
('aquatics','/əˈkwætɪks/','n. 水上运动','water sports','Aquatics center.','水上运动中心。','aqu(水)+atics'),
('swimming','/ˈswɪmɪŋ/','n. 游泳','moving in water','Competitive swimming.','竞技游泳。'),
('cycling','/ˈsaɪklɪŋ/','n. 骑自行车','riding a bicycle','Cycling is good exercise.','骑自行车是很好的锻炼。'),
('boxing','/ˈbɒksɪŋ/','n. 拳击','fighting sport','Boxing requires discipline.','拳击需要纪律。'),
('wrestling','/ˈreslɪŋ/','n. 摔跤','grappling sport','Freestyle wrestling.','自由式摔跤。'),
('fencing','/ˈfensɪŋ/','n. 击剑','sword sport','Fencing is an Olympic sport.','击剑是奥运项目。'),
('archery','/ˈɑːtʃəri/','n. 射箭','bow and arrow sport','Archery requires concentration.','射箭需要专注。'),
('equestrian','/ɪˈkwestriən/','n. 马术','horse riding','Equestrian events at Olympics.','奥运会马术项目。'),
('sailing','/ˈseɪlɪŋ/','n. 帆船运动','wind-powered boats','Sailing on the lake.','在湖上帆船运动。'),
('surfing','/ˈsɜːfɪŋ/','n. 冲浪','riding waves','Surfing in Hawaii.','在夏威夷冲浪。'),
('skiing','/ˈskiːɪŋ/','n. 滑雪','snow sport','Alpine skiing is thrilling.','高山滑雪很刺激。'),
('hiking','/ˈhaɪkɪŋ/','n. 徒步旅行','walking in nature','Mountain hiking is popular.','山地徒步很流行。'),
('camping','/ˈkæmpɪŋ/','n. 露营','outdoor living','Camping in the forest.','在森林露营。'),
('referee','/ˌrefəˈriː/','n. 裁判','sports official','The referee blew the whistle.','裁判吹了哨。'),
('spectator','/ˈspekteɪtə/','n. 观众','person watching','Thousands of spectators attended.','数千名观众参加了。','spect(看)+ator'),
('trophy','/ˈtrəʊfi/','n. 奖杯','award prize','Lift the trophy.','举起奖杯。'),
('medal','/ˈmedl/','n. 奖牌','metal award','Gold medal winner.','金牌得主。'),
('record','/ˈrekɔːd/','n. 纪录','best performance','Break the world record.','打破世界纪录。'),
('doping','/ˈdəʊpɪŋ/','n. 使用兴奋剂','illegal drug use','Doping is strictly banned.','严禁使用兴奋剂。'),
('drawback','/ˈdrɔːbæk/','n. 缺点','disadvantage','The drawback is the cost.','缺点是成本。'),
('upsurge','/ˈʌpsɜːdʒ/','n. 高涨','sharp increase','An upsurge in interest.','兴趣高涨。'),
('setback','/ˈsetbæk/','n. 挫折','reversal','Overcome a setback.','克服挫折。'),
('breakthrough','/ˈbreɪkθruː/','n. 突破','major advance','Scientific breakthrough.','科学突破。'),
('turnover','/ˈtɜːnəʊvə/','n. 营业额;人员流动','revenue or staff change','High staff turnover.','人员流动率高。'),
('outlook','/ˈaʊtlʊk/','n. 前景;观点','future prospect','Economic outlook is positive.','经济前景看好。'),
('threshold','/ˈθreʃhəʊld/','n. 门槛;起点','entry point','Below the threshold.','低于门槛。'),
('juncture','/ˈdʒʌŋktʃə/','n. 关键时刻','critical point','At this juncture.','在这个关键时刻。'),
('backdrop','/ˈbækdrɒp/','n. 背景','setting','Against the backdrop of change.','在变革的背景下。'),
('aftermath','/ˈɑːftəmæθ/','n. 后果','consequence','Aftermath of the crisis.','危机的后果。'),
('climax','/ˈklaɪmæks/','n. 顶点','highest point','The climax of his career.','他职业生涯的顶点。'),
('downfall','/ˈdaʊnfɔːl/','n. 坍台','sudden fall','His downfall was greed.','他的坍台是因为贪婪。'),
('lifespan','/ˈlaɪfspæn/','n. 寿命','length of life','Human lifespan has increased.','人类寿命延长了。'),
('livelihood','/ˈlaɪvlihʊd/','n. 生计','means of living','Earn a livelihood.','谋生。'),
('hardship','/ˈhɑːdʃɪp/','n. 困苦','severe suffering','Financial hardship.','经济困难。'),
('hustle','/ˈhʌsl/','v. 奔忙','to work hard','Hustle to succeed.','努力奋斗才能成功。'),
('strive','/straɪv/','v. 奋斗','to try hard','Strive for excellence.','追求卓越。'),
('thrive','/θraɪv/','v. 繁荣','to prosper','Businesses thrive in cities.','企业在城市繁荣发展。'),
('linger','/ˈlɪŋɡə/','v. 逗留','to stay longer','The memory lingers.','记忆萦绕。'),
('stumble','/ˈstʌmbl/','v. 绊倒','to trip','Stumble over obstacles.','绊倒在障碍物上。'),
('tumble','/ˈtʌmbl/','v. 跌倒','to fall','Stock prices tumbled.','股价暴跌了。'),
('plunge','/plʌndʒ/','v. 骤降','to drop sharply','Temperatures plunged.','温度骤降。'),
('soar','/sɔː/','v. 飙升','to rise rapidly','Prices soared.','价格飙升了。'),
('surge','/sɜːdʒ/','v./n. 激增','sudden increase','Demand surged.','需求激增了。'),
('plummet','/ˈplʌmɪt/','v. 暴跌','to fall sharply','Sales plummeted.','销售额暴跌了。'),
('fluctuate','/ˈflʌktʃueɪt/','v. 波动','to vary','Prices fluctuate daily.','价格每天波动。','fluctu(流动)+ate'),
('stabilize','/ˈsteɪbəlaɪz/','v. 稳定','to become stable','Economy has stabilized.','经济已稳定。'),
('escalate','/ˈeskəleɪt/','v. 升级','to intensify','Conflict may escalate.','冲突可能升级。'),
('diminish','/dɪˈmɪnɪʃ/','v. 减少','to decrease','Pain will diminish.','疼痛会减轻。','di+min(小)+ish'),
('amplify','/ˈæmplɪfaɪ/','v. 放大','to increase','Amplify the signal.','放大信号。','ampl(大)+ify'),
('deteriorate','/dɪˈtɪəriəreɪt/','v. 恶化','to worsen','Health deteriorated.','健康恶化了。'),
('prosper','/ˈprɒspə/','v. 兴旺','to succeed','The business prospered.','企业兴旺发达。'),
('dwindle','/ˈdwaɪndl/','v. 缩减','to gradually decrease','Resources dwindled.','资源缩减了。'),
('falter','/ˈfɔːltə/','v. 蹒跚;动摇','to hesitate','His confidence faltered.','他的信心动摇了。'),
('triumph','/ˈtraɪʌmf/','n. 胜利','great victory','A triumph of science.','科学的胜利。'),
('fiasco','/fiˈæskəʊ/','n. 惨败','complete failure','The event was a fiasco.','活动是一场惨败。'),
('ordeal','/ɔːˈdiːl/','n. 严酷考验','difficult experience','Survive the ordeal.','熬过严酷考验。'),
('endeavor','/ɪnˈdevə/','n. 努力','earnest attempt','A noble endeavor.','一次崇高的努力。'),
]
for w in d:
    cid += 1
    wr,ph,m,me,ex,et = w[0],w[1],w[2],w[3],w[4],w[5]
    r = w[6] if len(w) > 6 else ''
    rs = f', roots: "{r}"' if r else ''
    c += f'  {{ id: "w{cid:03d}", word: "{wr}", phonetic: "{ph}", meaning: "{m}", meaningEn: "{me}", example: "{ex}", exampleTranslation: "{et}"{rs}, level: "core" as const, tags: ["高频"] }},\n'
c += '];\n'
with open(VOCAB,'w',encoding='utf-8') as f:
    f.write(c)
print(f'Added {len(d)} words, total: {cid}')