import re
VOCAB = r'D:\Claude cli\MyApp\yingo\src\data\vocab-sample.ts'
with open(VOCAB,'r',encoding='utf-8') as f:
    c = f.read()
c = re.sub(r'];\s*$', '', c)
ids = re.findall(r'id:\s*"w(\d+)"', c)
cid = max(int(x) for x in ids) if ids else 0
print(f'Current: w{cid}')
d = [
('accommodate','/əˈkɒmədeɪt/','v. 容纳','to provide space','The hotel accommodates 200 guests.','酒店容纳200位客人。','ac+commod(合适)+ate'),
('acquaint','/əˈkweɪnt/','v. 使熟悉','to make familiar','Acquaint yourself with the rules.','让自己熟悉规则。'),
('adhere','/ədˈhɪə/','v. 遵守','to stick to','Adhere to the guidelines.','遵守指南。'),
('allocate','/ˈæləkeɪt/','v. 分配','to distribute','Allocate resources wisely.','明智分配资源。','al+loc(地方)+ate'),
('anticipate','/ænˈtɪsɪpeɪt/','v. 预料','to expect','Anticipate future needs.','预料未来需求。'),
('apprehend','/ˌæprɪˈhend/','v. 逮捕;理解','to arrest or understand','Police apprehended the suspect.','警察逮捕了嫌疑人。'),
('ascertain','/ˌæsəˈteɪn/','v. 查明','to find out','Ascertain the facts.','查明事实。'),
('berate','/bɪˈreɪt/','v. 严厉指责','to scold','He berated himself.','他严厉自责。'),
('bolster','/ˈbəʊlstə/','v. 增强','to support','Bolster the argument.','增强论点。'),
('circumvent','/ˌsɜːkəmˈvent/','v. 规避','to avoid','Circumvent the rules.','规避规则。','circum(绕)+vent(来)'),
('coerce','/kəʊˈɜːs/','v. 强迫','to force','Do not coerce others.','不要强迫他人。'),
('commemorate','/kəˈmeməreɪt/','v. 纪念','to honor','Commemorate the event.','纪念事件。'),
('compel','/kəmˈpel/','v. 迫使','to force','Compelled to act.','被迫行动。'),
('concede','/kənˈsiːd/','v. 承认','to admit','Concede the point.','承认这一点。'),
('condemn','/kənˈdem/','v. 谴责','to criticize strongly','Condemn violence.','谴责暴力。'),
('confiscate','/ˈkɒnfɪskeɪt/','v. 没收','to seize','Confiscate illegal items.','没收非法物品。'),
('confront','/kənˈfrʌnt/','v. 面对','to face','Confront the problem.','面对问题。'),
('consent','/kənˈsent/','n. 同意','agreement','Give informed consent.','给予知情同意。'),
('consolidate','/kənˈsɒlɪdeɪt/','v. 巩固','to strengthen','Consolidate gains.','巩固收益。'),
('contemplate','/ˈkɒntəmpleɪt/','v. 思考','to think deeply','Contemplate the options.','思考选项。'),
('contradict','/ˌkɒntrəˈdɪkt/','v. 反驳','to oppose','Contradict the statement.','反驳声明。'),
('contribute','/kənˈtrɪbjuːt/','v. 贡献','to give','Contribute to society.','对社会做贡献。'),
('controversy','/ˈkɒntrəvɜːsi/','n. 争论','disagreement','Political controversy.','政治争论。'),
('convince','/kənˈvɪns/','v. 说服','to persuade','Convince the jury.','说服陪审团。'),
('critique','/krɪˈtiːk/','n. 评论','critical review','A literary critique.','文学评论。'),
('decipher','/dɪˈsaɪfə/','v. 破译','to decode','Decipher the code.','破译密码。'),
('delegate','/ˈdelɪɡeɪt/','v. 委派','to assign authority','Delegate responsibility.','委派责任。'),
('deliberate','/dɪˈlɪbəreɪt/','v. 商议','to discuss','Deliberate on the issue.','商议问题。'),
('depict','/dɪˈpɪkt/','v. 描绘','to portray','The painting depicts a scene.','画描绘了一个场景。'),
('deprive','/dɪˈpraɪv/','v. 剥夺','to take away','Deprive of rights.','剥夺权利。'),
('detect','/dɪˈtekt/','v. 发现','to discover','Detect a pattern.','发现规律。','de+tect(遮盖)'),
('deter','/dɪˈtɜː/','v. 威慑','to discourage','Deter crime.','威慑犯罪。'),
('detract','/dɪˈtrækt/','v. 减损','to reduce value','Detract from the quality.','减损质量。'),
('devise','/dɪˈvaɪz/','v. 想出','to invent','Devise a plan.','想出计划。'),
('differentiate','/ˌdɪfəˈrenʃieɪt/','v. 区分','to distinguish','Differentiate between them.','区分它们。'),
('diminish','/dɪˈmɪnɪʃ/','v. 削弱','to reduce','Diminish the impact.','削弱影响。'),
('disclose','/dɪsˈkləʊz/','v. 披露','to reveal','Disclose information.','披露信息。'),
('discern','/dɪˈsɜːn/','v. 辨别','to perceive','Discern the difference.','辨别差异。'),
('dispose','/dɪˈspəʊz/','v. 处理','to get rid of','Dispose of waste.','处理废物。'),
('disregard','/ˌdɪsrɪˈɡɑːd/','v. 忽视','to ignore','Disregard the noise.','忽视噪音。'),
('dissolve','/dɪˈzɒlv/','v. 解散','to break up','Dissolve the partnership.','解散合伙关系。'),
('distort','/dɪˈstɔːt/','v. 歪曲','to twist','Distort the truth.','歪曲真相。'),
('dominate','/ˈdɒmɪneɪt/','v. 主导','to control','Dominate the market.','主导市场。'),
('dwell','/dwel/','v. 居住;细想','to live or think about','Do not dwell on mistakes.','不要细想错误。'),
('elaborate','/ɪˈlæbəreɪt/','v. 详述','to explain in detail','Elaborate on your point.','详述你的观点。'),
('eliminate','/ɪˈlɪmɪneɪt/','v. 消除','to remove','Eliminate errors.','消除错误。'),
('embark','/ɪmˈbɑːk/','v. 着手','to begin','Embark on a project.','着手项目。'),
('emerge','/ɪˈmɜːdʒ/','v. 浮现','to appear','New evidence emerged.','新证据浮现了。'),
('emit','/ɪˈmɪt/','v. 发出','to send out','Emit light.','发出光。'),
('enforce','/ɪnˈfɔːs/','v. 执行','to impose','Enforce the law.','执行法律。'),
('engage','/ɪnˈɡeɪdʒ/','v. 参与','to participate','Engage in discussion.','参与讨论。'),
('ensure','/ɪnˈʃʊə/','v. 确保','to make sure','Ensure safety.','确保安全。'),
('erode','/ɪˈrəʊd/','v. 侵蚀','to wear away','Trust has eroded.','信任被侵蚀了。'),
('escalate','/ˈeskəleɪt/','v. 升级','to intensify','Tensions escalate.','紧张局势升级。'),
('evolve','/ɪˈvɒlv/','v. 演变','to develop','Technology evolves.','技术演变。'),
('exceed','/ɪkˈsiːd/','v. 超出','to surpass','Exceed expectations.','超出预期。'),
('exclude','/ɪkˈskluːd/','v. 排除','to leave out','Exclude irrelevant data.','排除不相关数据。'),
('exert','/ɪɡˈzɜːt/','v. 施加','to apply','Exert pressure.','施加压力。'),
('exploit','/ɪkˈsplɔɪt/','v. 利用','to use','Exploit resources.','利用资源。'),
('extract','/ɪkˈstrækt/','v. 提取','to remove','Extract information.','提取信息。'),
('fabricate','/ˈfæbrɪkeɪt/','v. 捏造','to invent falsely','Fabricate a story.','捏造故事。'),
('fluctuate','/ˈflʌktʃueɪt/','v. 起伏','to vary','Temperatures fluctuate.','温度起伏。'),
('formulate','/ˈfɔːmjuleɪt/','v. 构想','to create','Formulate a strategy.','构想策略。'),
('generate','/ˈdʒenəreɪt/','v. 产生','to produce','Generate electricity.','发电。'),
('grasp','/ɡrɑːsp/','v. 理解','to understand','Grasp the concept.','理解概念。'),
('halt','/hɔːlt/','v. 停止','to stop','Halt production.','停止生产。'),
('hinder','/ˈhɪndə/','v. 妨碍','to obstruct','Hinder progress.','妨碍进展。'),
('identify','/aɪˈdentɪfaɪ/','v. 识别','to recognize','Identify the problem.','识别问题。'),
('illustrate','/ˈɪləstreɪt/','v. 说明','to show','Illustrate with examples.','用例子说明。'),
('immerse','/ɪˈmɜːs/','v. 沉浸','to submerge','Immerse in the culture.','沉浸文化中。'),
('impair','/ɪmˈpeə/','v. 损害','to damage','Impair vision.','损害视力。'),
('impose','/ɪmˈpəʊz/','v. 强加','to force','Impose restrictions.','强加限制。'),
('incur','/ɪnˈkɜː/','v. 招致','to cause','Incur costs.','招致成本。'),
('inhibit','/ɪnˈhɪbɪt/','v. 抑制','to restrain','Inhibit growth.','抑制增长。'),
('instill','/ɪnˈstɪl/','v. 灌输','to implant','Instill values.','灌输价值观。'),
('integrate','/ˈɪntɪɡreɪt/','v. 整合','to combine','Integrate systems.','整合系统。'),
('interfere','/ˌɪntəˈfɪə/','v. 干涉','to intervene','Do not interfere.','不要干涉。'),
('intervene','/ˌɪntəˈviːn/','v. 介入','to step in','Intervene in crisis.','危机中介入。'),
('invoke','/ɪnˈvəʊk/','v. 引用','to cite','Invoke the law.','引用法律。'),
('isolate','/ˈaɪsəleɪt/','v. 隔离','to separate','Isolate the variable.','隔离变量。'),
('justify','/ˈdʒʌstɪfaɪ/','v. 证明合理','to give reasons','Justify the expense.','证明支出合理。'),
('manipulate','/məˈnɪpjuleɪt/','v. 操纵','to control','Manipulate data.','操纵数据。'),
('minimize','/ˈmɪnɪmaɪz/','v. 最小化','to reduce','Minimize risks.','最小化风险。'),
('modify','/ˈmɒdɪfaɪ/','v. 修改','to change','Modify the plan.','修改计划。'),
('neglect','/nɪˈɡlekt/','v. 忽视','to ignore','Neglect responsibilities.','忽视责任。'),
('negotiate','/nɪˈɡəʊʃieɪt/','v. 谈判','to discuss terms','Negotiate a deal.','谈判交易。'),
('obligate','/ˈɒblɪɡeɪt/','v. 使有义务','to require','Obligated to comply.','有义务遵守。'),
('obtain','/əbˈteɪn/','v. 获得','to acquire','Obtain a license.','获得许可证。'),
('omit','/əˈmɪt/','v. 省略','to leave out','Omit unnecessary details.','省略不必要细节。'),
('perceive','/pəˈsiːv/','v. 察觉','to notice','Perceive a change.','察觉变化。'),
('persist','/pəˈsɪst/','v. 坚持','to continue','Persist in efforts.','坚持努力。'),
('persuade','/pəˈsweɪd/','v. 说服','to convince','Persuade the audience.','说服观众。'),
('preclude','/prɪˈkluːd/','v. 排除','to prevent','Preclude the possibility.','排除可能性。'),
('presume','/prɪˈzjuːm/','v. 假定','to assume','Presume innocence.','假定无罪。'),
('prevail','/prɪˈveɪl/','v. 盛行','to be widespread','Common sense prevailed.','常识占了上风。'),
('proclaim','/prəˈkleɪm/','v. 宣告','to announce','Proclaim independence.','宣告独立。'),
('prolong','/prəˈlɒŋ/','v. 延长','to extend','Prolong the deadline.','延长截止日期。'),
('propel','/prəˈpel/','v. 推动','to drive','Propel the economy.','推动经济。'),
]
for w in d:
    cid += 1
    wr,ph,m,me,ex,et = w[0],w[1],w[2],w[3],w[4],w[5]
    r = w[6] if len(w) > 6 else ''
    rs = f', roots: "{r}"' if r else ''
    c += f'  {{ id: "w{cid:03d}", word: "{wr}", phonetic: "{ph}", meaning: "{m}", meaningEn: "{me}", example: "{ex}", exampleTranslation: "{et}"{rs}, level: "core" as const, tags: ["高频"] }},\n'
c += '];\n'
with open(VOCAB,'w',encoding='utf-8') as f:
    f.write(c)
print(f'Added {len(d)} words, total: {cid}')