const fs = require('fs');
const p = 'D:\\Claude cli\\MyApp\\yingo\\src\\data\\vocab-sample.ts';
let c = fs.readFileSync(p,'utf8').replace(/\];\s*$/,'');
const d = [
// O词族
['obey','/əˈbeɪ/','v. 服从','to follow rules','Obey the law.','服从法律。'],
['object','/ˈɒbdʒɪkt/','n./v. 反对','to express disapproval','Object to the plan.','反对计划。','ob(对面)+ject(投)'],
['objective','/əbˈdʒektɪv/','n./adj. 目标','a goal or aim','Main objective.','主要目标。','object+ive'],
['obligation','/ˌɒblɪˈɡeɪʃn/','n. 义务','a duty or commitment','Legal obligation.','法律义务。','ob+lig(绑)+ation'],
['obscure','/əbˈskjʊə/','adj. 模糊的','not clearly expressed','Obscure reference.','模糊的引用。','ob+scure(覆盖)'],
['observe','/əbˈzɜːv/','v. 观察','to watch carefully','Observe the pattern.','观察模式。','ob+serv(看)'],
['obtain','/əbˈteɪn/','v. 获得','to get or acquire','Obtain permission.','获得许可。','ob+tain(持有)'],
['obvious','/ˈɒbviəs/','adj. 明显的','easily seen or understood','Obvious answer.','明显答案。','ob+vi(路)+ous'],
['occupy','/ˈɒkjupaɪ/','v. 占据','to take up space','Occupies most time.','占大部分时间。','oc+cup(抓)+y'],
['occur','/əˈkɜː/','v. 发生','to happen','Accidents occur.','事故频发。','oc+cur(跑)'],
['odd','/ɒd/','adj. 奇怪的','strange or unusual','Odd behavior.','奇怪行为。'],
['offend','/əˈfend/','v. 冒犯','to cause anger','Offended by comment.','被评论冒犯。','of+fend(打击)'],
['operate','/ˈɒpəreɪt/','v. 操作','to work or function','Operate machinery.','操作机器。','oper(工作)+ate'],
['opponent','/əˈpəʊnənt/','n. 对手','one who competes','Strong opponent.','强对手。','op+pon(放置)+ent'],
['oppose','/əˈpəʊz/','v. 反对','to resist or combat','Oppose the decision.','反对决定。','op+pose(放置)'],
['optimistic','/ˌɒptɪˈmɪstɪk/','adj. 乐观的','hopeful about future','Optimistic about growth.','对增长乐观。','optim(最好)+istic'],
['option','/ˈɒpʃn/','n. 选择','a choice','Available options.','可用选项。','opt(选择)+ion'],
['orient','/ˈɔːriənt/','v. 使适应','to align or adjust','Orient new employees.','使新员工适应。','ori(升起)+ent'],
['origin','/ˈɒrɪdʒɪn/','n. 起源','where something begins','Origin of species.','物种起源。','orig(开始)+in'],
['outcome','/ˈaʊtkʌm/','n. 结果','a result or consequence','Final outcome.','最终结果。','out+come(来)'],
['output','/ˈaʊtpʊt/','n. 产量','amount produced','Annual output.','年产量。','out+put(放)'],
['overall','/ˌəʊvərˈɔːl/','adj./adv. 总体的','in all parts','Overall performance.','总体表现。','over+all'],
['overcome','/ˌəʊvəˈkʌm/','v. 克服','to succeed despite','Overcome obstacles.','克服障碍。','over+come(来)'],
['overlap','/ˌəʊvəˈlæp/','v./n. 重叠','to partly cover','Skills overlap.','技能重叠。','over+lap(重叠)'],
['overseas','/ˌəʊvəˈsiːz/','adj./adv. 海外的','in a foreign country','Overseas market.','海外市场。','over+seas(海)'],
// P词族
['parallel','/ˈpærəlel/','adj./n. 平行的','side by side','Parallel lines.','平行线。','para(旁边)+llel'],
['participate','/pɑːˈtɪsɪpeɪt/','v. 参加','to take part in','Participate in study.','参加研究。','parti(部分)+cip(拿)+ate'],
['passage','/ˈpæsɪdʒ/','n. 通道；段落','a section of text','Reading passage.','阅读段落。','pass(通过)+age'],
['passion','/ˈpæʃn/','n. 热情','strong feeling','Passion for teaching.','教学热情。','pass(受苦)+ion'],
['passive','/ˈpæsɪv/','adj. 被动的','accepting without resistance','Passive attitude.','被动态度。','pass(受苦)+ive'],
['patent','/ˈpætnt/','n./adj. 专利','an official right','File a patent.','申请专利。'],
['pathway','/ˈpɑːθweɪ/','n. 途径','a way or route','Career pathway.','职业路径。','path(路)+way'],
['patience','/ˈpeɪʃns/','n. 耐心','the ability to wait','Have patience.','要有耐心。','pati(受苦)+ence'],
['pattern','/ˈpætn/','n. 模式','a repeated design','Behavior pattern.','行为模式。'],
['penalty','/ˈpenəlti/','n. 惩罚','a punishment','Financial penalty.','经济处罚。','penal(惩罚)+ty'],
['perceive','/pəˈsiːv/','v. 感知','to become aware of','Perceive danger.','感知危险。','per+ceive(拿)'],
['period','/ˈpɪəriəd/','n. 时期','a length of time','Time period.','时间段。','peri(周围)+od'],
['permanent','/ˈpɜːmənənt/','adj. 永久的','lasting for an indefinite time','Permanent change.','永久改变。','per(完全)+man(保持)+ent'],
['permit','/pəˈmɪt/','v. 允许','to give permission','Permit entry.','允许进入。','per+mit(送)'],
['persist','/pəˈsɪst/','v. 坚持','to continue despite difficulty','Persist in effort.','坚持努力。','per+sist(站)'],
['perspective','/pəˈspektɪv/','n. 视角','a point of view','Different perspectives.','不同视角。','per+spect(看)+ive'],
['phenomenon','/fəˈnɒmɪnən/','n. 现象','an observable fact','Natural phenomenon.','自然现象。','pheno(出现)+menon'],
['pioneer','/ˌpaɪəˈnɪə/','n. 先驱','an early developer','Pioneer in technology.','技术先驱。'],
['policy','/ˈpɒləsi/','n. 政策','a course of action','Government policy.','政府政策。'],
['portion','/ˈpɔːʃn/','n. 部分','a part of whole','Large portion.','大部分。','port(部分)+ion'],
['pose','/pəʊz/','v. 造成；提出','to present or constitute','Pose a threat.','构成威胁。'],
['positive','/ˈpɒzətɪv/','adj. 积极的','constructive or optimistic','Positive attitude.','积极态度。','pos(放置)+itive'],
['possess','/pəˈzes/','v. 拥有','to have or own','Possess strong skills.','拥有强大技能。','pos+sess(坐)'],
['potential','/pəˈtenʃl/','adj./n. 潜在的','having possibility','Potential danger.','潜在危险。','pot(力量)+ential'],
['poverty','/ˈpɒvəti/','n. 贫穷','the state of being poor','Reduce poverty.','减少贫穷。','pover(贫穷)+ty'],
['practical','/ˈpræktɪkl/','adj. 实际的','concerned with reality','Practical solution.','实际解决方案。','pract(练习)+ical'],
['precede','/prɪˈsiːd/','v. 先于','to come before','Success precedes failure.','成功先于失败。','pre+cede(走)'],
['precise','/prɪˈsaɪs/','adj. 精确的','exact and accurate','Precise measurements.','精确测量。','pre+cise(切)'],
['predict','/prɪˈdɪkt/','v. 预测','to say what will happen','Predict outcomes.','预测结果。','pre+dict(说)'],
['preserve','/prɪˈzɜːv/','v. 保护','to maintain or protect','Preserve environment.','保护环境。','pre+serve(保持)'],
['priority','/praɪˈɒrɪti/','n. 优先事项','most important thing','Top priority.','首要任务。','prior(先)+ity'],
['prohibit','/prəˈhɪbɪt/','v. 禁止','to forbid by law','Prohibit smoking.','禁止吸烟。','pro+hibit(持有)'],
['promote','/prəˈməʊt/','v. 促进','to encourage or support','Promote health.','促进健康。','pro+mote(移动)'],
['proportion','/prəˈpɔːʃn/','n. 比例','a part in relation to whole','Large proportion.','大比例。','pro+port(部分)+ion'],
['prospect','/ˈprɒspekt/','n. 前景','future possibility','Bright prospects.','光明前景。','pro+spect(看)'],
['prosperity','/prɒˈsperɪti/','n. 繁荣','successful state','Economic prosperity.','经济繁荣。','prosper(繁荣)+ity'],
['protest','/ˈprəʊtest/','n./v. 抗议','a strong objection','Public protest.','公众抗议。','pro+test(见证)'],
['provoke','/prəˈvəʊk/','v. 激怒','to cause anger','Provoked debate.','引发辩论。','pro+voc(叫)'],
['pursue','/pəˈsjuː/','v. 追求','to follow or chase','Pursue goals.','追求目标。','pur(完全)+sue(跟随)'],
// Q-R词族
['qualify','/ˈkwɒlɪfaɪ/','v. 使合格','to meet requirements','Qualify as doctor.','有资格当医生。','qual(品质)+ify'],
['quote','/kwəʊt/','v./n. 引用','to repeat words','Quote a source.','引用来源。'],
['radical','/ˈrædɪkl/','adj. 根本的','relating to root or fundamental','Radical change.','根本性改变。','radic(根)+al'],
['range','/reɪndʒ/','n. 范围','a variety of limits','Wide range.','广泛范围。'],
['ratio','/ˈreɪʃiəʊ/','n. 比率','a relationship between numbers','Cost ratio.','成本比率。','rat(计算)+io'],
['rational','/ˈræʃnəl/','adj. 理性的','based on reason','Rational thinking.','理性思维。','ration(理性)+al'],
['reaction','/riˈækʃn/','n. 反应','a response','Chemical reaction.','化学反应。','re+act+ion'],
['reality','/riˈælɪti/','n. 现实','the state of things','Face reality.','面对现实。','real+ity'],
['reasonable','/ˈriːznəbl/','adj. 合理的','fair and sensible','Reasonable price.','合理价格。','reason+able'],
['recover','/rɪˈkʌvə/','v. 恢复','to return to normal','Recover from illness.','从疾病中恢复。','re+cover(盖)'],
['reduce','/rɪˈdjuːs/','v. 减少','to make smaller','Reduce costs.','降低成本。','re+duce(引导)'],
['refine','/rɪˈfaɪn/','v. 精炼','to improve by removing flaws','Refine the process.','改进过程。','re+fine(界限)'],
['reform','/rɪˈfɔːm/','v./n. 改革','to improve by change','Economic reform.','经济改革。','re+form(形)'],
['region','/ˈriːdʒən/','n. 地区','an area','Rural region.','农村地区。','reg(统治)+ion'],
['regulate','/ˈreɡjuleɪt/','v. 管理','to control by rule','Regulate industry.','管理工业。','regul(规则)+ate'],
['reinforce','/ˌriːɪnˈfɔːs/','v. 加强','to make stronger','Reinforce learning.','加强学习。','re+in+force(力量)'],
['reject','/rɪˈdʒekt/','v. 拒绝','to refuse to accept','Reject the proposal.','拒绝提案。','re+ject(投)'],
['relate','/rɪˈleɪt/','v. 关联','to have connection','Relate to topic.','与主题相关。','re+late(搬运)'],
['release','/rɪˈliːs/','v./n. 释放','to set free','Release information.','发布信息。','re+lease(松)'],
['relevant','/ˈreləvənt/','adj. 相关的','closely connected','Relevant information.','相关信息。','re+lev(举)+ant'],
['reliable','/rɪˈlaɪəbl/','adj. 可靠的','trustworthy','Reliable source.','可靠来源。','re+li(依靠)+able'],
['reluctant','/rɪˈlʌktənt/','adj. 不情愿的','unwilling','Reluctant to change.','不情愿改变。','re+luct(挣扎)+ant'],
['rely','/rɪˈlaɪ/','v. 依赖','to depend on','Rely on data.','依赖数据。','re+ly(信任)'],
['remarkable','/rɪˈmɑːkəbl/','adj. 显著的','worthy of attention','Remarkable achievement.','显著成就。','re+mark(标记)+able'],
['remove','/rɪˈmuːv/','v. 移除','to take away','Remove obstacles.','移除障碍。','re+move(移动)'],
['renew','/rɪˈnjuː/','v. 更新','to make new again','Renew contract.','续签合同。','re+new(新)'],
['replace','/rɪˈpleɪs/','v. 取代','to take the place of','Replace old system.','取代旧系统。','re+place(放置)'],
['represent','/ˌreprɪˈzent/','v. 代表','to stand for','Represent the company.','代表公司。','re+present(呈现)'],
['reproduce','/ˌriːprəˈdjuːs/','v. 复制','to make a copy','Reproduce results.','复制结果。','re+produce(产生)'],
['reputation','/ˌrepjuˈteɪʃn/','n. 名誉','what people think','Good reputation.','好名声。','re+put(想)+ation'],
['require','/rɪˈkwaɪə/','v. 需要','to need','Require attention.','需要关注。','re+quire(寻求)'],
['research','/rɪˈsɜːtʃ/','n./v. 研究','systematic investigation','Conduct research.','进行研究。','re+search(搜索)'],
['reside','/rɪˈzaɪd/','v. 居住','to live in','Reside in city.','住在城市。','re+sid(坐)+e'],
['resign','/rɪˈzaɪn/','v. 辞职','to give up position','Resigned from job.','辞职。','re+sign(标记)'],
['resist','/rɪˈzɪst/','v. 抵抗','to fight against','Resist temptation.','抵抗诱惑。','re+sist(站)'],
['resolve','/rɪˈzɒlv/','v. 解决','to find solution','Resolve conflict.','解决冲突。','re+solve(松)'],
['resource','/rɪˈsɔːs/','n. 资源','a supply of something','Natural resources.','自然资源。','re+source(来源)'],
['respond','/rɪˈspɒnd/','v. 回应','to answer or react','Respond to change.','回应变化。','re+spond(承诺)'],
['restore','/rɪˈstɔː/','v. 恢复','to bring back','Restore balance.','恢复平衡。','re+store(储存)'],
['restrain','/rɪˈstreɪn/','v. 抑制','to prevent from doing','Restrain emotions.','抑制情绪。','re+strain(拉紧)'],
['restrict','/rɪˈstrɪkt/','v. 限制','to limit','Restrict access.','限制访问。','re+strict(拉紧)'],
['retain','/rɪˈteɪn/','v. 保留','to keep','Retain talent.','保留人才。','re+tain(持有)'],
['reveal','/rɪˈviːl/','v. 揭示','to make known','Reveal truth.','揭示真相。','re+veal(遮盖)'],
['revenue','/ˈrevənjuː/','n. 收入','income or profit','Annual revenue.','年收入。','re+ven(来)+ue'],
['reverse','/rɪˈvɜːs/','v./adj. 相反的','opposite direction','Reverse trend.','逆转趋势。','re+vers(转)+e'],
['revise','/rɪˈvaɪz/','v. 修改','to re-examine and alter','Revise the essay.','修改文章。','re+vis(看)+e'],
['revolution','/ˌrevəˈluːʃn/','n. 革命','a fundamental change','Industrial revolution.','工业革命。','re+volu(转)+tion'],
['reward','/rɪˈwɔːd/','n./v. 奖励','a return for effort','Reward system.','奖励系统。','re+ward(守卫)'],
['rival','/ˈraɪvl/','n./v. 竞争者','a competitor','Rival company.','竞争公司。'],
['robust','/rəˈbʌst/','adj. 强健的','strong and healthy','Robust economy.','强劲经济。'],
['routine','/ruːˈtiːn/','n./adj. 常规','a regular procedure','Daily routine.','日常惯例。','rout(路)+ine'],
];
let id = 313;
for (const w of d) {
  const [word,phonetic,meaning,meaningEn,example,exampleTranslation,roots,association] = w;
  const nid = 'w'+String(id).padStart(3,'0');
  c += `  { id: "${nid}", word: "${word}", phonetic: "${phonetic}", meaning: "${meaning}", meaningEn: "${meaningEn}", example: "${example}", exampleTranslation: "${exampleTranslation}"${roots ? `, roots: "${roots}"` : ''}${association ? `, association: "${association}"` : ''}, level: "core" as const, tags: ["高频"] },\n`;
  id++;
}
c += '];\n';
fs.writeFileSync(p,c,'utf8');
console.log('Added '+d.length+' words, total up to w'+String(id-1).padStart(3,'0'));
