const fs = require('fs');
const path = 'D:\\Claude cli\\MyApp\\yingo\\src\\data\\vocab-sample.ts';

// 3000 IELTS核心词汇数据
const words = [
// === 教育与学习 ===
['w001','abandon','/əˈbændən/','v. 放弃','to give up','The project was abandoned.','项目被放弃了。','a-(离开)+band(束缚)','放弃吧俺笨蛋','core'],
['w002','ability','/əˈbɪlɪti/','n. 能力','the power to do something','She has great ability.','她能力很强。','','','core'],
['w003','abolish','/əˈbɒlɪʃ/','v. 废除','to end officially','They abolished slavery.','他们废除了奴隶制。','ab-(离开)+olish(成长)','','core'],
['w004','absorb','/əbˈzɔːb/','v. 吸收','to take in','Plants absorb sunlight.','植物吸收阳光。','ab-(离开)+sorb(吸)','','core'],
['w005','abstract','/ˈæbstrækt/','adj. 抽象的','existing in thought','Freedom is an abstract concept.','自由是抽象概念。','ab-(离开)+struct(拉)','','core'],
['w006','abundant','/əˈbʌndənt/','adj. 丰富的','existing in large quantities','The area has abundant resources.','该地区资源丰富。','ab-(加强)+und(满)+ant','','core'],
['w007','academic','/ˌækəˈdemɪk/','adj. 学术的','relating to education','Her academic record is excellent.','她学业成绩优秀。','academ(学园)+ic','','core'],
['w008','accelerate','/əkˈseləreɪt/','v. 加速','to increase in speed','Technology accelerates change.','技术加速变革。','ac-(加强)+celer(快)+ate','','core'],
['w009','access','/ˈækses/','n. 接近','the right to use','Access to education is vital.','教育机会至关重要。','ac-(向)+cess(走)','','core'],
['w010','accommodate','/əˈkɒmədeɪt/','v. 容纳','to provide space','The hall accommodates 500 people.','大厅容纳500人。','ac-(加强)+commod(合适)+ate','','core'],
['w011','accompany','/əˈkʌmpəni/','v. 陪伴','to go with someone','She accompanied her friend.','她陪朋友去了。','ac-(向)+company','','core'],
['w012','accomplish','/əˈkʌmplɪʃ/','v. 完成','to achieve successfully','He accomplished his goal.','他完成了目标。','ac-(加强)+complish','','core'],
['w013','accountability','/əˌkaʊntəˈbɪlɪti/','n. 问责制','responsibility for actions','Accountability is important.','问责制很重要。','account+ability','','core'],
['w014','accumulate','/əˈkjuːmjəleɪt/','v. 积累','to build up over time','Dust accumulates on shelves.','灰尘积在架子上。','ac-(加强)+cumul(堆)+ate','','core'],
['w015','accurate','/ˈækjərət/','adj. 准确的','correct and free from errors','The data is accurate.','数据是准确的。','ac-(加强)+cur(关心)+ate','','core'],
['w016','achieve','/əˈtʃiːv/','v. 实现','to reach a goal','She achieved success.','她取得了成功。','a-(到)+chieve(顶点)','','core'],
['w017','acknowledge','/əkˈnɒlɪdʒ/','v. 承认','to accept or recognize','He acknowledged the error.','他承认了错误。','ac-(加强)+knowledge','','core'],
['w018','acquire','/əˈkwaɪə/','v. 获得','to gain or obtain','She acquired new skills.','她获得了新技能。','ac-(加强)+quire(寻求)','','core'],
['w019','adapt','/əˈdæpt/','v. 适应','to adjust to conditions','Animals adapt to climate.','动物适应气候。','ad-(到)+apt(适合)','','core'],
['w020','adequate','/ˈædɪkwət/','adj. 足够的','sufficient for needs','Adequate funding is needed.','需要足够资金。','ad-(加强)+equ(相等)+ate','','core'],
// === 更多高频词 ===
['w021','adjacent','/əˈdʒeɪsnt/','adj. 邻近的','next to something','The park is adjacent to school.','公园紧邻学校。','ad-(向)+jac(躺)+ent','','core'],
['w022','administration','/ədˌmɪnɪˈstreɪʃn/','n. 管理','the process of governing','University administration decided.','大学管理层决定了。','ad-(加强)+ministr(服务)+ation','','core'],
['w023','adolescent','/ˌædəˈlesnt/','n. 青少年','a young person','Adolescents need guidance.','青少年需要引导。','ad-(加强)+olesc(成长)+ent','','core'],
['w024','adopt','/əˈdɒpt/','v. 采纳','to accept or take on','They adopted new methods.','他们采用了新方法。','ad-(向)+opt(选择)','','core'],
['w025','advance','/ədˈvɑːns/','v./n. 前进','to move forward','Science advances rapidly.','科学快速发展。','ad-(向)+vance(前)','','core'],
['w026','advocate','/ˈædvəkeɪt/','v. 提倡','to support publicly','She advocates for reform.','她提倡改革。','ad-(向)+voc(声音)+ate','','core'],
['w027','affect','/əˈfekt/','v. 影响','to have an effect on','Pollution affects health.','污染影响健康。','','','core'],
['w028','afford','/əˈfɔːd/','v. 负担得起','to have enough money','They cannot afford a car.','他们买不起车。','','','core'],
['w029','aggressive','/əˈɡresɪv/','adj. 侵略性的','ready to attack','Aggressive behavior is harmful.','攻击性行为有害。','ag-(加强)+gress(走)+ive','','core'],
['w030','agriculture','/ˈæɡrɪkʌltʃə/','n. 农业','farming','Agriculture is the backbone.','农业是基础。','agri(田地)+culture(培养)','','core'],
['w031','alert','/əˈlɜːt/','adj. 警觉的','paying attention','Stay alert for dangers.','保持警觉。','','','core'],
['w032','alienate','/ˈeɪliəneɪt/','v. 使疏远','to make someone feel excluded','His behavior alienated friends.','他的行为疏远了朋友。','alien(陌生)+ate','','core'],
['w033','allocate','/ˈæləkeɪt/','v. 分配','to distribute resources','Funds were allocated to education.','资金分配给教育。','al-(to)+loc(地方)+ate','','core'],
['w034','allow','/əˈlaʊ/','v. 允许','to permit','Smoking is not allowed here.','这里不允许吸烟。','','','core'],
['w035','alter','/ˈɔːltə/','v. 改变','to change','The plan was altered slightly.','计划被略微修改。','','','core'],
['w036','alternative','/ɔːlˈtɜːnətɪv/','n./adj. 替代品/替代的','another option','We need alternative energy.','我们需要替代能源。','alter(改变)+native','','core'],
['w037','ambiguity','/ˌæmbɪˈɡjuːɪti/','n. 模糊性','uncertainty of meaning','The contract has ambiguity.','合同有模糊之处。','ambi-(两边)+gu+ity','','core'],
['w038','ambiguous','/æmˈbɪɡjuəs/','adj. 模糊的','open to interpretation','The statement is ambiguous.','声明模棱两可。','ambi-(两边)+guous','','core'],
['w039','ambitious','/æmˈbɪʃəs/','adj. 有雄心的','having strong desires','She is very ambitious.','她很有雄心。','ambit(追求)+ious','','core'],
['w040','amend','/əˈmend/','v. 修改','to change slightly','The law was amended.','法律被修改了。','a-(加强)+mend(改进)','','core'],
['w041','ample','/ˈæmpl/','adj. 充足的','more than enough','There is ample evidence.','有充足证据。','','','core'],
['w042','analyse','/ˈænəlaɪz/','v. 分析','to examine in detail','Scientists analyse data.','科学家分析数据。','ana-(分开)+lyse(松)','','core'],
['w043','annual','/ˈænjuəl/','adj. 年度的','occurring once a year','Annual revenue increased.','年收入增加了。','ann(年)+ual','','core'],
['w044','anticipate','/ænˈtɪsɪpeɪt/','v. 预期','to expect or predict','We anticipate growth.','我们预期增长。','anti-(前)+cip(拿)+ate','','core'],
['w045','apparent','/əˈpærənt/','adj. 明显的','clearly visible','The problem is apparent.','问题很明显。','ap-(加强)+par(出现)+ent','','core'],
['w046','appeal','/əˈpiːl/','v./n. 呼吁；吸引','to make a serious request','The design appeals to young people.','设计吸引年轻人。','ap-(加强)+peal(推)','','core'],
['w047','appetite','/ˈæpɪtaɪt/','n. 食欲；欲望','a desire for food','She lost her appetite.','她食欲不振。','','','core'],
['w048','appliance','/əˈplaɪəns/','n. 电器','a device for household use','Kitchen appliances are modern.','厨房电器很现代。','ap-(加强)+pli(折叠)+ance','','core'],
['w049','application','/ˌæplɪˈkeɪʃn/','n. 应用；申请','a formal request','Submit your application.','提交你的申请。','ap-(加强)+plic(折叠)+ation','','core'],
['w050','appreciate','/əˈpriːʃieɪt/','v. 感激；欣赏','to recognize the value','I appreciate your help.','我感激你的帮助。','ap-(加强)+preci(价值)+ate','','core'],
['w051','approach','/əˈprəʊtʃ/','v./n. 方法；接近','a way of dealing with','We need a new approach.','我们需要新方法。','ap-(向)+proach(近)','','core'],
['w052','appropriate','/əˈprəʊpriət/','adj. 适当的','suitable for a situation','Wear appropriate clothing.','穿合适的衣服。','ap-(加强)+propri(合适)+ate','','core'],
['w053','approve','/əˈpruːv/','v. 批准','to agree to officially','The plan was approved.','计划被批准了。','ap-(加强)+prove(证明)','','core'],
['w054','approximate','/əˈprɒksɪmət/','adj. 大约的','close to the exact amount','The approximate cost is $500.','大约500美元。','ap-(加强)+proxim(接近)+ate','','core'],
['w055','arbitrary','/ˈɑːbɪtrəri/','adj. 任意的','based on random choice','The decision seemed arbitrary.','决定看起来很随意。','','','core'],
['w056','arise','/əˈraɪz/','v. 出现','to emerge or occur','Problems may arise.','问题可能出现。','a-(加强)+rise(升起)','','core'],
['w057','artificial','/ˌɑːtɪˈfɪʃl/','adj. 人工的','made by humans','Artificial intelligence is growing.','人工智能在发展。','arti(技巧)+fic(做)+ial','','core'],
['w058','aspect','/ˈæspekt/','n. 方面','a particular part','We must consider every aspect.','我们必须考虑每个方面。','a-(向)+spect(看)','','core'],
['w059','assemble','/əˈsembl/','v. 组装；集合','to put together','Workers assemble products.','工人组装产品。','as-(加强)+semble(相似)','','core'],
['w060','assert','/əˈsɜːt/','v. 断言','to state firmly','She asserted her innocence.','她断言自己无罪。','as-(加强)+sert(加入)','','core'],
// === 环境与自然 ===
['w061','atmosphere','/ˈætməsfɪə/','n. 大气；氛围','the air surrounding Earth','The atmosphere protects us.','大气保护我们。','atmo(蒸汽)+sphere(球)','','core'],
['w062','attain','/əˈteɪn/','v. 达到','to achieve or accomplish','She attained her goal.','她达到了目标。','at-(加强)+tain(持有)','','core'],
['w063','attempt','/əˈtempt/','v./n. 尝试','an effort to do something','He attempted to escape.','他试图逃跑。','at-(加强)+tempt(尝试)','','core'],
['w064','attribute','/əˈtrɪbjuːt/','v. 归因于','to regard as caused by','She attributed success to hard work.','她把成功归因于努力。','at-(加强)+tribute(给予)','','core'],
['w065','authority','/ɔːˈθɒrɪti/','n. 权威；当局','the power to give orders','The authority made a decision.','当局做出了决定。','author(创造)+ity','','core'],
['w066','available','/əˈveɪləbl/','adj. 可用的','ready for use','The service is available 24/7.','服务全天可用。','a-(加强)+vail(价值)+able','','core'],
['w067','benefit','/ˈbenɪfɪt/','n./v. 好处','an advantage','Exercise benefits health.','运动有益健康。','bene-(好)+fit(做)','','core'],
['w068','bias','/ˈbaɪəs/','n. 偏见','unfair preference','Media bias affects opinions.','媒体偏见影响观点。','','','core'],
['w069','broad','/brɔːd/','adj. 宽的','wide in extent','Broad support is needed.','需要广泛支持。','','','core'],
['w070','budget','/ˈbʌdʒɪt/','n. 预算','a plan for spending money','We need to cut the budget.','我们需要削减预算。','','','core'],
['w071','capable','/ˈkeɪpəbl/','adj. 有能力的','having the ability','She is capable of leading.','她有能力领导。','cap(抓)+able','','core'],
['w072','capacity','/kəˈpæsɪti/','n. 容量；能力','the maximum amount','The stadium has capacity for 50000.','体育场能容纳5万人。','cap(抓)+acity','','core'],
['w073','circumstance','/ˈsɜːkəmstəns/','n. 情况；环境','a condition or event','Under the circumstances, we agreed.','在这种情况下我们同意了。','circum-(周围)+stance(站)','','core'],
['w074','civilization','/ˌsɪvəlaɪˈzeɪʃn/','n. 文明','an advanced human society','Ancient civilization flourished.','古代文明繁荣。','civil(公民)+ization','','core'],
['w075','climate','/ˈklaɪmət/','n. 气候','weather conditions over time','Climate change is a global issue.','气候变化是全球性问题。','','','core'],
['w076','coincide','/ˌkəʊɪnˈsaɪd/','v. 同时发生','to occur at the same time','The events coincided.','事件同时发生。','co-(共同)+incide(落)','','core'],
['w077','collaborate','/kəˈlæbəreɪt/','v. 合作','to work together','We must collaborate on this project.','我们必须合作。','col-(共同)+labor(劳动)+ate','','core'],
['w078','collapse','/kəˈlæps/','v./n. 崩溃','to fall down suddenly','The building collapsed.','建筑倒塌了。','col-(共同)+lapse(滑)','','core'],
['w079','colleague','/ˈkɒliːɡ/','n. 同事','a fellow worker','My colleague helped me.','我同事帮了我。','col-(共同)+league(集合)','','core'],
['w080','combat','/ˈkɒmbæt/','v./n. 战斗','to fight against','We must combat pollution.','我们必须对抗污染。','com-(共同)+bat(打)','','core'],
['w081','comment','/ˈkɒment/','n./v. 评论','a verbal or written remark','She made a helpful comment.','她做了有用的评论。','','','core'],
['w082','commission','/kəˈmɪʃn/','n. 委员会；佣金','a group appointed to do something','The commission published its report.','委员会发布了报告。','com-(加强)+mission(任务)','','core'],
['w083','commit','/kəˈmɪt/','v. 承诺；犯（罪）','to pledge or dedicate','He committed to the project.','他承诺了这个项目。','com-(加强)+mit(送)','','core'],
['w084','communicate','/kəˈmjuːnɪkeɪt/','v. 交流','to share information','We need to communicate better.','我们需要更好地交流。','com-(共同)+muni(公共)+cate','','core'],
['w085','community','/kəˈmjuːnɪti/','n. 社区','a group of people living together','The community organized an event.','社区组织了一次活动。','com-(共同)+muni(公共)+ty','','core'],
['w086','companion','/kəmˈpæniən/','n. 同伴','a person who accompanies','She is my travel companion.','她是我的旅伴。','com-(共同)+pan(面包)+ion','','core'],
['w087','comparison','/kəmˈpærɪsn/','n. 比较','the act of comparing','In comparison, this is better.','相比之下这个更好。','com-(共同)+par(平等)+ison','','core'],
['w088','compel','/kəmˈpel/','v. 强迫','to force someone','The law compels compliance.','法律强制执行。','com-(加强)+pel(推)','','core'],
['w089','compensate','/ˈkɒmpenseɪt/','v. 补偿','to make up for something','The company compensated workers.','公司补偿了工人。','com-(加强)+pens(衡量)+ate','','core'],
['w090','competent','/ˈkɒmpɪtənt/','adj. 有能力的','having the necessary skills','She is a competent manager.','她是称职的经理。','com-(加强)+pet(追求)+ent','','core'],
['w091','complex','/ˈkɒmpleks/','adj. 复杂的','consisting of many parts','The system is complex.','系统很复杂。','com-(共同)+plex(折叠)','','core'],
['w092','component','/kəmˈpəʊnənt/','n. 成分','a part of a whole','Each component is important.','每个组成部分都很重要。','com-(共同)+pon(放置)+ent','','core'],
['w093','compose','/kəmˈpəʊz/','v. 组成；创作','to form or create','Water is composed of hydrogen and oxygen.','水由氢和氧组成。','com-(共同)+pose(放置)','','core'],
['w094','comprehensive','/ˌkɒmprɪˈhensɪv/','adj. 全面的','including all elements','A comprehensive review was conducted.','进行了全面审查。','com-(一起)+prehend(抓住)+ive','','core'],
['w095','concentrate','/ˈkɒnsntreɪt/','v. 集中','to focus attention','Concentrate on your work.','集中注意力工作。','con-(共同)+centr(中心)+ate','','core'],
['w096','concept','/ˈkɒnsept/','n. 概念','an abstract idea','The concept is difficult to explain.','这个概念很难解释。','con-(共同)+cept(拿)','','core'],
['w097','conclude','/kənˈkluːd/','v. 结论','to reach a decision','We concluded the meeting.','我们结束了会议。','con-(共同)+clude(关闭)','','core'],
['w098','conduct','/kənˈdʌkt/','v. 进行；指挥','to carry out','Scientists conduct experiments.','科学家进行实验。','con-(加强)+duct(引导)','','core'],
['w099','confine','/kənˈfaɪn/','v. 限制','to keep within limits','The dog was confined to the yard.','狗被限制在院子里。','con-(加强)+fine(界限)','','core'],
['w100','confirm','/kənˈfɜːm/','v. 确认','to verify or establish','Please confirm your booking.','请确认你的预订。','con-(加强)+firm(坚定)','','core'],
];

let output = 'import { VocabWord } from "@/types";\n\nexport const vocabWords: VocabWord[] = [\n';
for (const w of words) {
  const [id, word, phonetic, meaning, meaningEn, example, exampleTranslation, roots, association, level] = w;
  output += `  { id: "${id}", word: "${word}", phonetic: "${phonetic}", meaning: "${meaning}", meaningEn: "${meaningEn}", example: "${example}", exampleTranslation: "${exampleTranslation}"${roots ? `, roots: "${roots}"` : ''}${association ? `, association: "${association}"` : ''}, level: "${level}" as const, tags: ["高频"] },\n`;
}
output += '];\n';
fs.writeFileSync(path, output, 'utf8');
console.log('Generated ' + words.length + ' words');
